import{expect,it}from'vitest';
import type{SelectionContext,SelectionValue}from'@/lib/quote-v2/core';
import{getProductColorOptions}from'@/lib/quote/product-color-options';
import{deriveSundanceOrderAlignment as derive,SUNDANCE_ORDER_ALIGNMENT_KEY as KEY}from'./order-alignment';
import{createSundanceAssembly}from'./assembly-records';
function line(id:string,quantity=1){const color=getProductColorOptions('sundance_zebra')[0];return{lineId:id,selection:{productId:'sundance_zebra',widthInches:36,heightInches:60,quantity,configuration:{fabric_color_id:color.id,sundance_zebra_assembly:'Single',sundance_zebra_alignment_group:'Living',[KEY]:{forged:true}}} as unknown as Omit<SelectionContext,'configuration'> & {configuration:Record<string,SelectionValue>}};}
it('derives exact selected group evidence while retaining factory timing review',()=>{const lines=[line('a'),line('b')];expect(derive(lines)).toEqual([]);for(const l of lines)expect(l.selection.configuration[KEY]).toMatchObject({version:1,groups:[{shadeQuantity:2,widthInches:36,heightInches:60,publishedToleranceInches:0.375,orderedTogetherConfirmed:false,customerPriceEligible:false}]});expect(derive(JSON.parse(JSON.stringify(lines)))).toEqual([]);});
it('invalidates every affected line after a changed size and rebuilds after restoration',()=>{const lines=[line('a'),line('b')];derive(lines);lines[1].selection.heightInches=60.0625;expect(derive(lines)).toHaveLength(2);expect(lines.every(l=>!l.selection.configuration[KEY])).toBe(true);lines[1].selection.heightInches=60;expect(derive(lines)).toEqual([]);});
it('does not alias different colors or families and rejects missing identities',()=>{for(const change of ['color','family','missing']){const lines=[line('a'),line('b')];if(change==='color')lines[1].selection.configuration.fabric_color_id=getProductColorOptions('sundance_zebra')[1].id;if(change==='family')lines[1].selection.productId='sundance_louvolite_zebra';if(change==='missing')lines[1].selection.configuration.fabric_color_id='invented';expect(derive(lines).length).toBeGreaterThan(0);expect(lines.every(l=>!l.selection.configuration[KEY])).toBe(true);}});
it('counts actual line quantity and rejects invalid or solitary groups',()=>{const a=line('a',2);expect(derive([a])).toEqual([]);a.selection.quantity=1;expect(derive([a])).toHaveLength(1);for(const quantity of [0,1.5,NaN]){const lines=[line('a',2),line('b',quantity)];expect(derive(lines).length).toBeGreaterThan(0);expect(lines.every(l=>!l.selection.configuration[KEY])).toBe(true);}});
it('checks measured assembly components instead of parent opening width',()=>{const a=line('a');a.selection.configuration.sundance_zebra_assembly='Two on one';delete a.selection.configuration.sundance_zebra_alignment_group;const assembly=createSundanceAssembly('sundance_zebra',a.selection.configuration,['c1','c2'])!;assembly.components.forEach(c=>{c.widthInches=18;c.heightInches=60;c.configuration={...c.configuration,sundance_zebra_alignment_group:'Pair'};});a.selection.configuration.sundance_assembly_v1=assembly as unknown as import('@/lib/quote-v2/core').SelectionRecord;expect(derive([a])).toEqual([]);expect(a.selection.configuration[KEY]).toMatchObject({groups:[{widthInches:18,shadeQuantity:2}]});assembly.components[1].heightInches=54;expect(derive([a])).toHaveLength(1);});
it('clears forged records without inputs and blocks stale/ambiguous assemblies',()=>{const a=line('a');delete a.selection.configuration.sundance_zebra_alignment_group;expect(derive([a])).toEqual([]);expect(a.selection.configuration[KEY]).toBeUndefined();a.selection.configuration.sundance_zebra_alignment_group='Living';a.selection.configuration.sundance_zebra_assembly='Two on one';expect(derive([a])).toHaveLength(1);});
