import {describe,expect,it} from "vitest";
import {mobileCustomerMatchesLetter,mobileMapTarget,mobilePhoneTarget,mobileSmsTarget,projectMobileCustomers} from "./mobile-customers";
describe("mobile customer info/payments",()=>{
  const jobs=[{id:"j1",customer_name:"Ada",phone:"805-555-1212",address:"1 Main St",city:"Ventura",state:"CA",zip:"93001"}];
  const quotes=[{id:"q1",job_id:"j1",status:"closed",quote_total:1000,deposit_required:500},{id:"q2",job_id:"j1",status:"archived",quote_total:800,deposit_required:400}];
  it("keeps closed work active until explicitly archived",()=>{expect(projectMobileCustomers({jobs,quotes,scope:"active"}).map(r=>r.id)).toEqual(["q1"]);expect(projectMobileCustomers({jobs,quotes,scope:"archived"}).map(r=>r.id)).toEqual(["q2"])});
  it("projects authoritative ledger balances",()=>{expect(projectMobileCustomers({jobs,quotes:quotes.slice(0,1),payments:[{quote_id:"q1",amount:200,payment_label:"Deposit"}],scope:"active"})[0]).toMatchObject({deposit:300,balance:500,contractTotal:1000})});
  it("creates safe native call, text, and map targets",()=>{expect(mobilePhoneTarget("(805) 555-1212")).toBe("tel:+18055551212");expect(mobileSmsTarget("(805) 555-1212")).toBe("sms:+18055551212");expect(mobilePhoneTarget("bad")).toBeNull();expect(mobileSmsTarget("bad")).toBeNull();expect(mobileSmsTarget(null)).toBeNull();expect(mobileMapTarget("1 Main St, Ventura, CA")).toContain("1%20Main%20St%2C%20Ventura%2C%20CA");expect(mobileMapTarget(" ")).toBeNull()});
  it("includes brand-new jobs without quotes only in active results",()=>{const newJob={...jobs[0],id:"new",estimated_total:500,deposit_paid:100};expect(projectMobileCustomers({jobs:[newJob],quotes:[],scope:"active"})[0]).toMatchObject({jobId:"new",quoteId:null,contractTotal:500,deposit:100,balance:400});expect(projectMobileCustomers({jobs:[newJob],quotes:[],scope:"archived"})).toEqual([])});
  it("matches the first or last customer name case-insensitively",()=>{expect(mobileCustomerMatchesLetter("Ada Lovelace","a")).toBe(true);expect(mobileCustomerMatchesLetter("Ada Lovelace","L")).toBe(true);expect(mobileCustomerMatchesLetter("Ada Lovelace","Z")).toBe(false);expect(mobileCustomerMatchesLetter("","A")).toBe(false)});
  it("keeps letter-filtered archived and active records in their requested scope",()=>{const matching=[{...jobs[0],customer_name:"Grace Hopper"}];expect(projectMobileCustomers({jobs:matching,quotes,scope:"active"}).every(row=>row.id!=="q2")).toBe(true);expect(projectMobileCustomers({jobs:matching,quotes,scope:"archived"}).map(row=>row.id)).toEqual(["q2"])});
  it("treats archived_at as authoritative even when a legacy status was not updated",()=>{const legacyArchived=[{...quotes[0],archived_at:"2026-07-30T12:00:00Z"}];expect(projectMobileCustomers({jobs,quotes:legacyArchived,scope:"active"})).toEqual([]);expect(projectMobileCustomers({jobs,quotes:legacyArchived,scope:"archived"})).toHaveLength(1)});
  it("never leaks explicitly archived quotes into active results or active quotes into archived results",()=>{const results={active:projectMobileCustomers({jobs,quotes,scope:"active"}),archived:projectMobileCustomers({jobs,quotes,scope:"archived"})};expect(results.active.map(row=>row.id)).toEqual(["q1"]);expect(results.archived.map(row=>row.id)).toEqual(["q2"])});
});
