import {describe,it,expect} from "vitest";
import {getProductColorOptions} from "@/lib/quote/product-color-options";
import {CITYLIGHTS_CURRENT_COLORS} from "@/lib/quote/norman-current-assortment";
import {citylightsWand,citylightsBrackets,citylightsLadders} from "@/lib/quote/norman-citylights";
import {citylightsComponents,deriveCitylightsMatching} from "./norman-citylights";
import {deriveNormanOrderRecords} from "./norman-assemblies";
import {quoteV2CatalogVersionFor} from "./catalog";
import {priceQuoteV2Selection,authoritativeAutomaticSurchargeSelections} from "./engine";
import type {SelectionContext} from "./core";
const colors=getProductColorOptions("citylights_aluminum");
function blind(c:SelectionContext["configuration"]={},w=36,h=60):SelectionContext{const row=colors.find(r=>r.colorCode==="7024")!;return{manufacturerId:"norman",productId:"citylights_aluminum",programId:row.programId!,catalogAsOf:"2026-09-19",catalogVersion:quoteV2CatalogVersionFor("citylights_aluminum","2026-09-19"),widthInches:w,heightInches:h,quantity:1,options:{},configuration:{mount_type:"Outside Mount",slat_size:'1"',fabric_color_code:row.colorCode,fabric_color_id:row.id,fabric_color_type:row.fabricType,color:row.colorName,light_control:"Regular Route Holes",lift_system:"Cordless",...c}};}
const rules=(s:SelectionContext)=>citylightsComponents(s)!.issues.map(i=>i.ruleId.split('.').pop());
function price(s:SelectionContext){deriveNormanOrderRecords([{lineId:"a",selection:s}]);return priceQuoteV2Selection({selection:s,priceInput:{productId:s.productId,programId:s.programId!,widthInches:s.widthInches,heightInches:s.heightInches,quantity:s.quantity,surcharges:authoritativeAutomaticSurchargeSelections(s)},includeInternalCost:true});}
describe("CityLights August source assortment and current components",()=>{
 it("prices the production UI selection with implicit cordless operation",()=>{
  const row=colors.find(r=>r.colorCode==="7031")!;
  const s=blind({lift_system:null,material:"CityLights Cordless Aluminum Blinds",supplier:"Norman",slat_size:'2"',light_control:"SmartPrivacy",fabric_color_id:row.id,fabric_color_code:"7031",fabric_color_type:row.fabricType,slat_finish:"matte",control_side:"Right",draw_direction:"Right",citylights_wand_drop:"47.25",citylights_shim_layers:"2",citylights_hold_down:"Yes",mount_depth_inches:null,side_mount_bracket:null,citylights_mount_fit:null,citylights_bracket_installation:null});
  const p=price(s);expect(p.ok,JSON.stringify(p)).toBe(true);
 });
 for(const [slat,codes] of [[1,CITYLIGHTS_CURRENT_COLORS.oneInch],[2,CITYLIGHTS_CURRENT_COLORS.twoInch]] as const)for(const code of codes)it(`prices ${code} with ${slat}-inch slats`,()=>{
  const row=colors.find(r=>r.colorCode===code)!;expect(row?.available).toBe(true);
  const s=blind({slat_size:`${slat}"`,light_control:slat===1?"Regular Route Holes":"SmartPrivacy",fabric_color_id:row.id,fabric_color_code:row.colorCode,fabric_color_type:row.fabricType,color:row.colorName});expect(rules(s)).toEqual([]);const p=price(s);expect(p.ok,JSON.stringify(p)).toBe(true);
 });
 it("rejects discontinued half-inch slats and unavailable color/slat pairs",()=>{expect(rules(blind({slat_size:'1/2"'}))).toContain("slat");expect(rules(blind({slat_size:'2"',fabric_color_code:"7027"}))).toContain("color_slat");expect(rules(blind({fabric_color_code:"7020"}))).toContain("color_slat");});
 it.each([[1,9,10],[1,75,96],[1,78,90],[2,10.5,16],[2,72,96],[2,96,72]])("accepts size limits %s %s %s",(size,w,h)=>expect(rules(blind({slat_size:`${size}"`,light_control:size===1?"Privacy":"SmartPrivacy"},w,h))).toEqual([]));
 it.each([[1,8.9375,60],[1,78.0625,60],[1,78,93],[1,36,9.9375],[2,10.4375,60],[2,96.0625,60],[2,96,72.0625],[2,36,15.9375],[2,36,96.0625]])("rejects invalid size %s %s %s",(size,w,h)=>expect(rules(blind({slat_size:`${size}"`},w,h))).toContain("dimensions"));
 it.each([[1,"Fully Recessed",1.9375],[1,"Minimum Depth",1.25],[2,"Fully Recessed",2.6875],[2,"Minimum Depth",1.625],[2,"Shallow Mounting Holes",.9375]])("checks exact mounting depth %s %s",(slat,fit,depth)=>{const c={slat_size:`${slat}"`,light_control:slat===1?"Privacy":"SmartPrivacy",mount_type:"Inside Mount",citylights_mount_fit:fit,mount_depth_inches:depth};expect(rules(blind(c))).toEqual([]);expect(rules(blind({...c,mount_depth_inches:Number(depth)-.0625}))).toContain("mount_depth");});
 it("enforces narrow center tilt and saves no-lift/handle differences",()=>{expect(citylightsComponents(blind({},14.9375))?.record).toMatchObject({lift:"No Lift",handles:0,wand:{side:"Center"}});expect(rules(blind({control_side:"Left"},14.9375))).toContain("wand_side");expect(citylightsComponents(blind({},15))?.record).toMatchObject({lift:"Cordless",handles:2,wand:{side:"Left"}});});
 it.each([[1,36,17],[1,36.0625,21],[1,48.0625,24],[1,60.0625,30],[1,72.0625,36],[1,84.0625,48],[2,36,17.75],[2,36.0625,24],[2,48.0625,29.75],[2,72.0625,38.25]])("uses source wand default %s %s",(s,h,w)=>expect(citylightsWand(s,h)).toBe(w));
 it.each([[1,37,2],[1,37.0625,3],[1,60,3],[1,60.0625,4],[2,37,2],[2,37.0625,3],[2,47,3],[2,47.0625,4],[2,75,4],[2,75.0625,5]])("counts brackets %s %s",(s,w,n)=>expect(citylightsBrackets(s,w)).toBe(n));
 it("derives shims and finish charges despite client-supplied finish and count",()=>{const s=blind({fabric_color_code:"7031",slat_finish:"Standard",citylights_shim_layers:2,shim_quantity:1000},48,60);expect(authoritativeAutomaticSurchargeSelections(s)).toEqual([{id:"metallic_slats_matte_finishes_perforated_slats",units:1},{id:"shim",units:6}]);expect(citylightsComponents(s)?.record.mounting).toMatchObject({brackets:3,shims:6,shimExtension:.6875,screws:{mounting:6,mountingLength:2}});});
 it("allows wide inside side support with top support only and disallows shallow side kits",()=>{const c={slat_size:'2"',light_control:"SmartPrivacy",mount_type:"Inside Mount",mount_depth_inches:2,side_mount_bracket:"Yes",citylights_bracket_installation:"Side Only"};expect(rules(blind(c,37.375))).toEqual([]);expect(rules(blind(c,37.4375))).toContain("side_mount");expect(rules(blind({...c,citylights_bracket_installation:"Top Support"},60))).toEqual([]);expect(rules(blind({...c,citylights_mount_fit:"Shallow Mounting Holes"}))).toContain("side_mount");});
 it.each<SelectionContext["configuration"]>([{citylights_wand_drop:11.75},{citylights_shim_layers:3},{mount_type:"Inside Mount",mount_depth_inches:3,citylights_shim_layers:1},{side_mount_bracket:"Yes"},{slat_size:'1"',citylights_mount_fit:"Shallow Mounting Holes",mount_type:"Inside Mount",mount_depth_inches:4},{control_side:"Center"},{motor_type:"AutoWand"},{cutout:"Yes"}])("rejects incompatible option %j",c=>expect(rules(blind(c)).length).toBeGreaterThan(0));
 it("retains the unresolved final two-inch inside grid edge",()=>expect(rules(blind({slat_size:'2"',light_control:"SmartPrivacy",mount_type:"Inside Mount",mount_depth_inches:3},96.375,60))).toContain("grid_boundary"));
 it("uses the September 2025 two-inch ladder/cord threshold",()=>{expect(citylightsLadders(2,"SmartPrivacy",67,96)).toEqual({ladder:4,cord:4});expect(citylightsLadders(2,"SmartPrivacy",67.0625,96)).toEqual({ladder:4,cord:8});expect(citylightsLadders(2,"SmartPrivacy",72,84)).toEqual({ladder:4,cord:4});});
 it("persists order membership and rejects mismatched matching groups",()=>{const rows=[{lineId:"a",selection:blind({citylights_matching_group:"1"})},{lineId:"b",selection:blind({citylights_matching_group:"1"},48)}];expect(deriveCitylightsMatching(rows)).toEqual([]);deriveNormanOrderRecords(rows);const reopened=JSON.parse(JSON.stringify(rows));deriveNormanOrderRecords(reopened);expect(reopened).toEqual(rows);rows[1].selection.configuration={...rows[1].selection.configuration,light_control:"Privacy"};expect(deriveCitylightsMatching(rows)).toHaveLength(2);expect(deriveCitylightsMatching([rows[0]])).toHaveLength(1);});
 it("does not change historical catalogs",()=>{const old=blind();old.catalogAsOf="2026-09-18";expect(citylightsComponents(old)).toBeNull();});
});
