import {describe,it,expect} from "vitest";
import {getProductColorOptions} from "@/lib/quote/product-color-options";
import {WOOD_CODES,woodWandDrop,woodBrackets,woodLadders} from "@/lib/quote/norman-wood";
import {woodComponents,woodValancePriceWidth} from "./norman-wood";
import {deriveWoodAssemblies} from "./norman-wood-assemblies";
import {deriveNormanOrderRecords} from "./norman-assemblies";
import {quoteV2CatalogVersionFor} from "./catalog";
import {priceQuoteV2Selection,authoritativeAutomaticSurchargeSelections} from "./engine";
import type {SelectionContext} from "./core";
const colors=getProductColorOptions("wood_blinds");
function blind(c:SelectionContext["configuration"]={},w=36,h=60):SelectionContext{const row=colors.find(r=>r.colorCode===(c.fabric_color_code??"ND001"))!;return{manufacturerId:"norman",productId:"wood_blinds",programId:row?.programId??null,catalogAsOf:"2026-09-19",catalogVersion:quoteV2CatalogVersionFor("wood_blinds","2026-09-19"),widthInches:w,heightInches:h,quantity:1,options:{},configuration:{mount_type:"Outside Mount",slat_size:'2"',fabric_color_code:row?.colorCode,fabric_color_id:row?.id,fabric_color_type:row?.fabricType,color:row?.colorName,valance:"No Valance",lift_system:null,...c}};}
const rules=(s:SelectionContext)=>woodComponents(s)!.issues.map(i=>i.ruleId.split('.').pop());
function price(s:SelectionContext){deriveNormanOrderRecords([{lineId:"a",selection:s}]);return priceQuoteV2Selection({selection:s,priceInput:{productId:s.productId,programId:s.programId!,widthInches:s.widthInches,heightInches:s.heightInches,quantity:s.quantity,valanceWidthInches:woodValancePriceWidth(s),surcharges:authoritativeAutomaticSurchargeSelections(s)},includeInternalCost:true});}
describe("Normandy September assortment and hardware",()=>{
 for(const slat of ['2"','2.5"'])for(const code of WOOD_CODES)it(`prices ${code} with ${slat} slats`,()=>{const s=blind({slat_size:slat,fabric_color_code:code});expect(colors.find(r=>r.colorCode===code)?.available).toBe(true);expect(rules(s)).toEqual([]);const p=price(s);expect(p.ok,JSON.stringify(p)).toBe(true);});
 it("retains historical color but rejects new ordering",()=>{expect(colors.find(r=>r.colorCode==="ND118")?.available).toBe(false);expect(rules(blind({fabric_color_code:"ND118"}))).toContain("legacy_color_conflict");});
 it.each([[6.5,16],[96,96],[36,96]])("accepts net bounds %s × %s",(w,h)=>expect(rules(blind({},w,h))).toEqual([]));
 it.each([[6.4375,60],[96.0625,60],[36,15.9375],[36,96.0625]])("blocks invalid net bounds %s × %s",(w,h)=>expect(rules(blind({},w,h))).toContain("dimensions"));
 it("uses the inside deduction but holds the final grid edge",()=>{expect(rules(blind({mount_type:"Inside Mount",mount_depth_inches:3},6.875,60))).toEqual([]);expect(rules(blind({mount_type:"Inside Mount",mount_depth_inches:3},96.375,60))).toContain("grid_boundary");});
 it.each([["No Valance","Fully Recessed",2.6875],["Linear","Fully Recessed",4.0625],["Contempo","Fully Recessed",4.0625],["Designer Crown","Bracket Flush",2.6875],["No Valance","Minimum Depth",1.375],["Linear","Minimum Depth",1.625],["Linear","Shallow Mounting Holes",.9375]])("checks mounting %s %s",(valance,fit,depth)=>{const c={mount_type:"Inside Mount",valance,wood_mount_fit:fit,mount_depth_inches:depth};expect(rules(blind(c))).toEqual([]);expect(rules(blind({...c,mount_depth_inches:Number(depth)-.0625})).length).toBeGreaterThan(0);});
 it("retains the conflicting minimum mounting range with valance",()=>expect(rules(blind({mount_type:"Inside Mount",valance:"Linear",wood_mount_fit:"Minimum Depth",mount_depth_inches:1.5}))).toContain("mount_depth_source_conflict"));
 it.each([[36,17.75],[48,17.75],[48.0625,29.75],[72,29.75],[72.0625,38.25]])("uses wood-specific wand default %s",(h,n)=>expect(woodWandDrop(h)).toBe(n));
 it("rejects faux-only wands and never splits metal wood wands",()=>{for(const wand of [11.75,24,25])expect(rules(blind({wood_wand_drop:wand}))).toContain("wand_drop");expect(woodComponents(blind({wood_wand_drop:60}))?.record).toMatchObject({wandDrop:60,splitWand:false,wandMaterial:"Metal"});});
 it.each([[37,2],[37.0625,3],[47,3],[47.0625,4],[75,4],[75.0625,5]])("counts installation brackets at %s",(w,n)=>expect(woodBrackets(w)).toBe(n));
 it.each([[32,false,2,4],[32.0625,false,3,4],[39.9375,false,3,4],[40,false,3,6],[52,false,3,6],[52.0625,false,4,8],[78.0625,false,5,8],[36.5,true,2,4],[36.5625,true,3,4],[54,true,3,6],[54.0625,true,4,8],[75.0625,true,5,8]])("counts ladders/cords at %s large %s",(w,large,ladders,cords)=>expect(woodLadders(Number(w),Boolean(large))).toEqual({ladders,cords}));
 it("derives all hardware counts and ignores supplied surcharge counts",()=>{const s=blind({wood_shim_layers:2,shim_quantity:999,wood_hold_down:"Yes",wood_wand_drop:60,valance:"Linear",wood_keystone_count:1},48);expect(woodComponents(s)?.record.components[0]).toMatchObject({brackets:4,shims:8,holdDowns:2,screws:{mounting:8,mountingLength:2,holdDown:2,holdDownLength:.75},valance:{width:49,returnSize:3.5625,returnConnectors:4,clips:3}});expect(authoritativeAutomaticSurchargeSelections(s)).toEqual([{id:"shim",units:8},{id:"valance_surcharge_contempo",units:1},{id:"keystone",units:1}]);});
 it("supports side kits with wide top support but limits side-only support",()=>{const c={mount_type:"Inside Mount",mount_depth_inches:3,side_mount_bracket:"Yes",wood_bracket_installation:"Side Only"};expect(rules(blind(c,37.375))).toEqual([]);expect(rules(blind(c,37.4375))).toContain("side_mount");expect(rules(blind({...c,wood_bracket_installation:"Top Support"},72))).toEqual([]);expect(rules(blind({...c,wood_mount_fit:"Shallow Mounting Holes"}))).toContain("side_mount");});
 it("counts return connectors and permits dealer-confirmed custom and keystone charges",()=>{for(const [style,n] of [["Contempo",2],["Linear",4],["Designer Crown",4]])expect(woodComponents(blind({valance:style}))?.record.components[0].valance?.returnConnectors).toBe(n);expect(rules(blind({valance:"Linear",wood_valance_width_inches:40}))).toEqual([]);expect(rules(blind({valance:"Linear",wood_keystone_count:2},60))).toEqual([]);});
 it("serializes partial measurements without non-finite values",()=>{const record=woodComponents(blind({wood_cutout_left_type:"Side (Middle)"}))?.record;expect(JSON.parse(JSON.stringify(record))).toEqual(record);});
 it("rebuilds matching membership and blocks mismatched colors",()=>{const rows=[{lineId:"a",selection:blind({wood_matching_group:"1"})},{lineId:"b",selection:blind({wood_matching_group:"1"},48)}];expect(deriveWoodAssemblies(rows)).toEqual([]);deriveNormanOrderRecords(rows);const reopened=JSON.parse(JSON.stringify(rows));deriveNormanOrderRecords(reopened);expect(reopened).toEqual(rows);rows[1].selection.configuration={...rows[1].selection.configuration,fabric_color_code:"ND003"};expect(deriveWoodAssemblies(rows).map(i=>i.ruleId)).toEqual(["norman.wood_blinds.matching_specifications","norman.wood_blinds.matching_specifications"]);});
 it("retains common widths, gaps and shortest wand",()=>{const c={wood_common_group:"1",valance:"Linear"};const rows=[{lineId:"a",selection:blind({...c,wood_common_position:1,wood_common_gap_after:1},36,48)},{lineId:"b",selection:blind({...c,wood_common_position:2,wood_common_gap_after:0},48,60)}];expect(deriveWoodAssemblies(rows)).toEqual([]);deriveNormanOrderRecords(rows);expect(rows[0].selection.configuration.wood_common_valance_v1).toMatchObject({orderedWidths:[36,48],gaps:[1,0],finishedWidth:86,defaultWandDrop:17.75});for(const r of rows)expect(rules(r.selection)).toEqual([]);rows[0].selection.configuration={...rows[0].selection.configuration,wood_cutout_right_type:"Corner (Bottom)"};expect(deriveWoodAssemblies(rows).some(i=>i.ruleId.endsWith("cutout_location"))).toBe(true);});
 it("holds common valances beyond three supported splices",()=>{const rows=Array.from({length:4},(_,i)=>({lineId:String(i),selection:blind({wood_common_group:"1",wood_common_position:i+1,wood_common_gap_after:i===3?0:12,valance:"Linear"},96)}));deriveNormanOrderRecords(rows);expect(rules(rows[0].selection)).toContain("valance_splices");});

 it.each([[24,62],[24.125,68],[36,87],[36.125,99],[96,223],[96.125,248],[108,248],[108.125,273]])("prices shared finished width %s at retail %s",(width,charge)=>{
  const count=width>100?3:2,w=width/count;
  const rows=Array.from({length:count},(_,i)=>({lineId:String(i),selection:blind({valance:"Linear",wood_common_group:"1",wood_common_position:i+1,wood_common_gap_after:i<count-1?.375:0,wood_valance_width_inches:width},w)}));
  deriveNormanOrderRecords(rows);
  const priced=rows.map(({selection:s})=>priceQuoteV2Selection({selection:s,priceInput:{productId:s.productId,programId:s.programId!,widthInches:s.widthInches,heightInches:s.heightInches,quantity:1,valanceWidthInches:woodValancePriceWidth(s),surcharges:authoritativeAutomaticSurchargeSelections(s)},includeInternalCost:true}));
  for(const p of priced)expect(p.ok,JSON.stringify(p)).toBe(true);
  expect(priced.flatMap(p=>p.ok?p.surchargeLines:[]).filter(c=>c.id==="valance_surcharge_contempo").map(c=>c.amount)).toEqual([charge]);
 });
 it("matches independent custom and multiple-keystone dealer samples",()=>{
  const custom=price(blind({valance:"Linear",wood_valance_width_inches:40}));expect(custom.ok&&custom.total).toBe(634);
  const multiple=price(blind({valance:"Linear",wood_keystone_count:2},60));expect(multiple.ok&&multiple.total).toBe(1118);
  const three=price(blind({valance:"Linear",wood_keystone_count:3},84));expect(three.ok&&three.surchargeLines.find(c=>c.id==="keystone")?.amount).toBe(243);
  expect(rules(blind({valance:"Linear",wood_keystone_count:3},60))).toContain("keystone_spacing");
 });
 it("preserves older catalog behavior",()=>{const s=blind();s.catalogAsOf="2026-09-18";expect(woodComponents(s)).toBeNull();});
});
