import { describe, expect, it } from "vitest";
import { getProduct, getProgram } from "@/lib/quote/catalog";
import type { SalesQuoteDesign, SalesQuoteLineItem } from "@mts/types/quote";
import {
  repriceExactQuoteBuilderForQuoteLabPreview,
  type ExactQuoteBuilderRepriceInput,
} from "@/lib/quote-lab/exact-backend";
import portalFixture from "./fixtures/norman-805-portal-2026-07-21.json";
import { NORMAN_805_DEALER_POLICY } from "./norman-dealer-policy";
import type { AuthoritativePriceComponent } from "./price-components";
import { QUOTE_V2_SOURCE_MANIFEST } from "./source-manifest";

/**
 * Independent golden acceptance suite for the existing-interface V2 backend.
 *
 * Scale: 20 quotes x 20 different measured items = 400 final priced lines.
 * Every line is also repriced through four progressive controls:
 *   1. documented base grid;
 *   2. selected fabric grid;
 *   3. accessories;
 *   4. operating system / motorization.
 *
 * The expected grid values below are literal transcriptions from the pinned
 * July 2026 Norman Retail Guide, not values generated by the runtime catalog or
 * pricing engine. The suite first compares those literals to the checked-in
 * catalog, then uses an integer-cents oracle to audit the V2 result.
 */

const PRICE_BOOK_SHA256 =
  "ae102c19b833e5c20070c11ecaad61d68a79bf6b52b5402fad55415e2602d2f3";
const MOTOR_GUIDE_SHA256 =
  "57692a04ac4abe2e8774f8b248f4516141929124580edc2527e85f29d4feb290";
const QUOTE_COUNT = 20;
const ITEMS_PER_QUOTE = 20;
// Literal current-account values captured from the live, unsubmitted dealer
// drafts. Keep these independent of the runtime policy object so changing the
// implementation cannot silently rewrite the oracle's expected arithmetic.
const STANDARD_FACTOR_NUMERATOR = 3_300;
const SLOW_FACTOR_NUMERATOR = 2_970;
const FACTOR_DENOMINATOR = 10_000;
const PROCESSING_FEE_BASIS_POINTS = 200;

const GRID_WIDTHS = [24, 30, 36, 42, 48] as const;
const GRID_HEIGHTS = [36, 48, 60, 72] as const;

const PROGRAMS = [
  {
    id: "roller_cordless_fabric_price_group_1_pg1",
    name: "Cordless Fabric - Price Group 1",
    collection: "Brook",
    colorCode: "F1120",
    colorName: "Pewter",
    sourcePage: 18,
  },
  {
    id: "roller_cordless_fabric_price_group_2_pg2",
    name: "Cordless Fabric - Price Group 2",
    collection: "Amelia",
    colorCode: "F1484",
    colorName: "Mist Gray",
    sourcePage: 18,
  },
  {
    id: "roller_cordless_fabric_price_group_3_pg3",
    name: "Cordless Fabric - Price Group 3",
    collection: "Caroline",
    colorCode: "F0867",
    colorName: "White sand",
    sourcePage: 19,
  },
] as const;

type ProgramFixture = (typeof PROGRAMS)[number];

// Physical PDF pages 18-19 (printed pages 17-18).
const SOURCE_GRIDS: Readonly<Record<ProgramFixture["id"], readonly (readonly number[])[]>> = {
  roller_cordless_fabric_price_group_1_pg1: [
    [254, 273, 291, 312, 333],
    [274, 298, 318, 345, 368],
    [296, 318, 346, 377, 414],
    [313, 345, 382, 420, 457],
  ],
  roller_cordless_fabric_price_group_2_pg2: [
    [278, 299, 323, 341, 367],
    [301, 328, 353, 377, 406],
    [325, 353, 384, 420, 462],
    [349, 383, 422, 467, 509],
  ],
  roller_cordless_fabric_price_group_3_pg3: [
    [307, 337, 365, 396, 424],
    [337, 372, 407, 443, 482],
    [366, 407, 449, 497, 545],
    [398, 444, 498, 554, 613],
  ],
};

type AccessoryFixture = Readonly<{
  key: string;
  id: string | null;
  label: string;
  sourceUnitDollars: number;
  units: number;
  sourcePage: number | null;
}>;

const ACCESSORIES: readonly AccessoryFixture[] = [
  {
    key: "none",
    id: null,
    label: "None",
    sourceUnitDollars: 0,
    units: 1,
    sourcePage: null,
  },
  {
    key: "shim-1",
    id: "shim",
    label: "Shim",
    sourceUnitDollars: 7,
    units: 1,
    sourcePage: 20,
  },
  {
    key: "shim-2",
    id: "shim",
    label: "Shim",
    sourceUnitDollars: 7,
    units: 2,
    sourcePage: 20,
  },
  {
    key: "hold-down-1",
    id: "magnetic_hold_down",
    label: "Magnetic hold down",
    sourceUnitDollars: 28,
    units: 1,
    sourcePage: 20,
  },
  {
    key: "hold-down-2",
    id: "magnetic_hold_down",
    label: "Magnetic hold down",
    sourceUnitDollars: 28,
    units: 2,
    sourcePage: 20,
  },
  {
    key: "premium-hem-bar",
    id: "premium_hem_bar",
    label: "Premium hem bar",
    sourceUnitDollars: 16,
    units: 1,
    sourcePage: 20,
  },
  {
    key: "keystone",
    id: "keystone",
    label: "Keystone",
    sourceUnitDollars: 73,
    units: 1,
    sourcePage: 20,
  },
] as const;

type MotorSelectionFixture = Readonly<{
  groupId: string;
  optionId: string;
  role:
    | "base_motor"
    | "controller"
    | "hub"
    | "sensor"
    | "power_supply"
    | "accessory";
  units: number;
}>;

type OperationFixture = Readonly<{
  key: string;
  liftSystem: string;
  tube: string;
  motorType: string | null;
  powerConfiguration: string | null;
  automaticSurchargeId: string | null;
  operatingCatalogDollars: number;
  operatingSourcePage: number | null;
  motorizationSelections: readonly MotorSelectionFixture[];
  secondaryCatalogLines: readonly Readonly<{
    id: string;
    catalogUnitDollars: number;
    units: number;
    sourcePage: number;
  }>[];
}>;

const OPERATIONS: readonly OperationFixture[] = [
  {
    key: "cordless",
    liftSystem: "Cordless",
    tube: "All Tubes",
    motorType: null,
    powerConfiguration: null,
    automaticSurchargeId: null,
    operatingCatalogDollars: 0,
    operatingSourcePage: null,
    motorizationSelections: [],
    secondaryCatalogLines: [],
  },
  {
    key: "smartrelease",
    liftSystem: "SmartRelease",
    tube: '1 3/4" (43mm) Tube',
    motorType: null,
    powerConfiguration: null,
    automaticSurchargeId: "smartrelease",
    operatingCatalogDollars: 89,
    operatingSourcePage: 20,
    motorizationSelections: [],
    secondaryCatalogLines: [],
  },
  {
    key: "autowand",
    liftSystem: "Motorized",
    tube: '2" (52mm) Tube',
    motorType: "Autowand",
    powerConfiguration: "AutoWand",
    automaticSurchargeId: null,
    operatingCatalogDollars: 166,
    operatingSourcePage: 8,
    motorizationSelections: [
      {
        groupId: "autowand",
        optionId: "autowand",
        role: "base_motor",
        units: 1,
      },
    ],
    secondaryCatalogLines: [],
  },
  {
    key: "autowand-extension",
    liftSystem: "Motorized",
    tube: '2" (52mm) Tube',
    motorType: "Autowand",
    powerConfiguration: "AutoWand",
    automaticSurchargeId: null,
    operatingCatalogDollars: 166,
    operatingSourcePage: 8,
    motorizationSelections: [
      {
        groupId: "autowand",
        optionId: "autowand",
        role: "base_motor",
        units: 1,
      },
      {
        groupId: "autowand",
        optionId: "extension_cable",
        role: "power_supply",
        units: 1,
      },
    ],
    secondaryCatalogLines: [
      {
        id: "motor:autowand:extension_cable",
        catalogUnitDollars: 43,
        units: 1,
        sourcePage: 8,
      },
    ],
  },
] as const;

const DISCOUNTS = [0, 5, 10, 15, 20] as const;
const STAGES = ["base", "fabric", "accessories", "operation"] as const;
type PricingStage = (typeof STAGES)[number];

type GoldenCell = Readonly<{
  index: number;
  widthIndex: number;
  heightIndex: number;
  matchedWidth: number;
  matchedHeight: number;
  measuredWidth: number;
  measuredHeight: number;
}>;

const GOLDEN_CELLS: readonly GoldenCell[] = GRID_HEIGHTS.flatMap(
  (matchedHeight, heightIndex) =>
    GRID_WIDTHS.map((matchedWidth, widthIndex) => {
      const measuredWidth =
        widthIndex > 0 && (widthIndex + heightIndex) % 2 === 1
          ? GRID_WIDTHS[widthIndex - 1] + 0.125
          : matchedWidth;
      const measuredHeight =
        heightIndex > 0 && (widthIndex + heightIndex) % 3 === 1
          ? GRID_HEIGHTS[heightIndex - 1] + 0.125
          : matchedHeight;
      return {
        index: heightIndex * GRID_WIDTHS.length + widthIndex,
        widthIndex,
        heightIndex,
        matchedWidth,
        matchedHeight,
        measuredWidth,
        measuredHeight,
      };
    }),
);

type GoldenScenario = Readonly<{
  quoteIndex: number;
  lineIndex: number;
  cell: GoldenCell;
  program: ProgramFixture;
  accessory: AccessoryFixture;
  operation: OperationFixture;
  quantity: number;
  discountPercent: number;
  schedulePercent: 28.5 | 30;
}>;

type ComponentExpectation = Readonly<{
  id: string;
  category: "accessory" | "operating_system";
  catalogCents: number;
  wholesaleCents: number;
  customerCents: number;
  sourcePage: number;
}>;

type GoldenExpectation = Readonly<{
  baseCatalogCents: number;
  fabricCatalogCents: number;
  accessoryCatalogCents: number;
  operatingCatalogCents: number;
  catalogPerWindowCents: number;
  baseWholesaleCents: number;
  fabricWholesaleCents: number;
  accessoryWholesaleCents: number;
  operatingWholesaleCents: number;
  wholesalePerWindowCents: number;
  baseCustomerCents: number;
  fabricCustomerCents: number;
  accessoryCustomerCents: number;
  operatingCustomerCents: number;
  customerPerWindowCents: number;
  discountCents: number;
  unitPriceCents: number;
  lineTotalCents: number;
  pricedComponents: readonly ComponentExpectation[];
}>;

type V2Quote = Extract<
  ReturnType<typeof repriceExactQuoteBuilderForQuoteLabPreview>,
  { backend: "v2" }
>;

function dollarsToCents(value: number): number {
  return Math.round(value * 100);
}

function centsToDollars(value: number): number {
  return Math.round(value) / 100;
}

function cents(value: number): number {
  return dollarsToCents(value);
}

function eligibleWholesaleCents(
  catalogCents: number,
  schedulePercent: 28.5 | 30,
): number {
  const numerator =
    schedulePercent === 28.5
      ? SLOW_FACTOR_NUMERATOR
      : STANDARD_FACTOR_NUMERATOR;
  return Math.round((catalogCents * numerator) / FACTOR_DENOMINATOR);
}

function processingFeeCents(basisCents: number): number {
  return Math.round(
    (basisCents * PROCESSING_FEE_BASIS_POINTS) / 10_000,
  );
}

type UnallocatedComponentExpectation = Omit<
  ComponentExpectation,
  "wholesaleCents" | "customerCents"
>;

function largestRemainderAllocation(
  sourceCents: readonly number[],
  numerator: number,
  denominator: number,
): number[] {
  const allocations = sourceCents.map((amount) =>
    Math.floor((amount * numerator) / denominator),
  );
  const target = Math.round(
    (sourceCents.reduce((sum, amount) => sum + amount, 0) * numerator) /
      denominator,
  );
  let remaining = target - allocations.reduce((sum, amount) => sum + amount, 0);
  const remainderOrder = sourceCents
    .map((amount, index) => ({
      index,
      remainder: (amount * numerator) % denominator,
    }))
    .filter(({ index }) => sourceCents[index] !== 0)
    .sort(
      (left, right) =>
        right.remainder - left.remainder || left.index - right.index,
    );
  for (let orderIndex = 0; remaining > 0; orderIndex += 1) {
    const recipient = remainderOrder[orderIndex % remainderOrder.length];
    if (!recipient) {
      throw new Error("Cannot allocate a nonzero portal rounding remainder.");
    }
    allocations[recipient.index] += 1;
    remaining -= 1;
  }
  return allocations;
}

function portalFactorFraction(schedulePercent: 28.5 | 30): {
  numerator: number;
  denominator: 10_000;
} {
  return {
    numerator:
      schedulePercent === 28.5
        ? SLOW_FACTOR_NUMERATOR
        : STANDARD_FACTOR_NUMERATOR,
    denominator: FACTOR_DENOMINATOR,
  };
}

function allocatePortalGroup(
  components: readonly UnallocatedComponentExpectation[],
  schedulePercent: 28.5 | 30,
): readonly ComponentExpectation[] {
  if (components.length === 0) return [];
  const factor = portalFactorFraction(schedulePercent);
  const wholesaleAllocations = largestRemainderAllocation(
    components.map((component) => component.catalogCents),
    factor.numerator,
    factor.denominator,
  );
  return components.map((component, index) => ({
    ...component,
    wholesaleCents: wholesaleAllocations[index],
    customerCents: component.catalogCents,
  }));
}

function sourceGridDollars(programId: ProgramFixture["id"], cell: GoldenCell): number {
  return SOURCE_GRIDS[programId][cell.heightIndex][cell.widthIndex];
}

function decodeScenario(quoteIndex: number, lineIndex: number): GoldenScenario {
  const cell = GOLDEN_CELLS[(lineIndex + quoteIndex) % GOLDEN_CELLS.length];
  let code = quoteIndex * ITEMS_PER_QUOTE + cell.index;
  const program = PROGRAMS[code % PROGRAMS.length];
  code = Math.floor(code / PROGRAMS.length);
  const accessory = ACCESSORIES[code % ACCESSORIES.length];
  code = Math.floor(code / ACCESSORIES.length);
  const operation = OPERATIONS[code % OPERATIONS.length];
  code = Math.floor(code / OPERATIONS.length);
  const discountPercent = DISCOUNTS[code % DISCOUNTS.length];
  return {
    quoteIndex,
    lineIndex,
    cell,
    program,
    accessory,
    operation,
    quantity: ((quoteIndex + cell.index) % 3) + 1,
    discountPercent,
    schedulePercent: quoteIndex % 4 === 3 ? 28.5 : 30,
  };
}

function fixtureForStage(
  scenario: GoldenScenario,
  stage: PricingStage,
): {
  program: ProgramFixture;
  accessory: AccessoryFixture;
  operation: OperationFixture;
} {
  const includeFabric = stage !== "base";
  const includeAccessory = stage === "accessories" || stage === "operation";
  const includeOperation = stage === "operation";
  return {
    program: includeFabric ? scenario.program : PROGRAMS[0],
    accessory: includeAccessory ? scenario.accessory : ACCESSORIES[0],
    operation: includeOperation ? scenario.operation : OPERATIONS[0],
  };
}

function expectedForStage(
  scenario: GoldenScenario,
  stage: PricingStage,
): GoldenExpectation {
  const fixture = fixtureForStage(scenario, stage);
  const baseCatalogCents = cents(sourceGridDollars(PROGRAMS[0].id, scenario.cell));
  const selectedGridCatalogCents = cents(
    sourceGridDollars(fixture.program.id, scenario.cell),
  );
  const fabricCatalogCents = selectedGridCatalogCents - baseCatalogCents;
  const operatingCatalogCents = cents(
    fixture.operation.operatingCatalogDollars,
  );
  const operatingComponentId =
    fixture.operation.key === "smartrelease"
      ? "operating:smartrelease"
      : fixture.operation.motorizationSelections.some(
            (entry) => entry.role === "base_motor",
          )
        ? "operating:motor:autowand:autowand"
        : "operating:cordless";

  // The live portal rounds the selected grid as one base group and every
  // per-window surcharge as a second group. Automatic SmartRelease precedes
  // manual surcharges; motorization follows manual surcharges. Allocate each
  // rounded group by largest fractional remainder with source order as the
  // deterministic tie-break so the visible ledger exactly matches the portal.
  const unallocatedComponents: UnallocatedComponentExpectation[] = [];
  if (fixture.operation.key === "smartrelease") {
    unallocatedComponents.push({
      id: operatingComponentId,
      category: "operating_system",
      catalogCents: operatingCatalogCents,
      sourcePage: fixture.operation.operatingSourcePage as number,
    });
  }
  if (fixture.accessory.id) {
    unallocatedComponents.push({
      id: `accessory:${fixture.accessory.id}`,
      category: "accessory",
      catalogCents:
        cents(fixture.accessory.sourceUnitDollars) * fixture.accessory.units,
      sourcePage: fixture.accessory.sourcePage as number,
    });
  }
  if (
    operatingCatalogCents > 0 &&
    fixture.operation.key !== "smartrelease"
  ) {
    unallocatedComponents.push({
      id: operatingComponentId,
      category: "operating_system",
      catalogCents: operatingCatalogCents,
      sourcePage: fixture.operation.operatingSourcePage as number,
    });
  }
  for (const secondary of fixture.operation.secondaryCatalogLines) {
    unallocatedComponents.push({
      id: secondary.id,
      category: "accessory",
      catalogCents: cents(secondary.catalogUnitDollars) * secondary.units,
      sourcePage: secondary.sourcePage,
    });
  }
  const pricedComponents = allocatePortalGroup(
    unallocatedComponents,
    scenario.schedulePercent,
  );

  const accessoryCatalogCents = pricedComponents
    .filter((component) => component.category === "accessory")
    .reduce((sum, component) => sum + component.catalogCents, 0);

  // The selected fabric grid is the portal's one base-price group. The ledger
  // preserves the independently sourced PG1 baseline lookup and assigns the
  // exact selected-group remainder to the fabric-upgrade row.
  const baseWholesaleCents = eligibleWholesaleCents(
    baseCatalogCents,
    scenario.schedulePercent,
  );
  const selectedGridWholesaleCents = eligibleWholesaleCents(
    selectedGridCatalogCents,
    scenario.schedulePercent,
  );
  const fabricWholesaleCents =
    selectedGridWholesaleCents - baseWholesaleCents;
  const accessoryWholesaleCents = pricedComponents
    .filter((component) => component.category === "accessory")
    .reduce((sum, component) => sum + component.wholesaleCents, 0);
  const operatingWholesaleCents = pricedComponents
    .filter((component) => component.category === "operating_system")
    .reduce((sum, component) => sum + component.wholesaleCents, 0);

  const baseCustomerCents = baseCatalogCents;
  const selectedGridCustomerCents = selectedGridCatalogCents;
  const fabricCustomerCents = selectedGridCustomerCents - baseCustomerCents;
  const accessoryCustomerCents = pricedComponents
    .filter((component) => component.category === "accessory")
    .reduce((sum, component) => sum + component.customerCents, 0);
  const operatingCustomerCents = pricedComponents
    .filter((component) => component.category === "operating_system")
    .reduce((sum, component) => sum + component.customerCents, 0);
  const customerPerWindowCents =
    baseCustomerCents +
    fabricCustomerCents +
    accessoryCustomerCents +
    operatingCustomerCents;
  const discountCents = Math.round(
    (customerPerWindowCents * scenario.discountPercent) / 100,
  );
  const unitPriceCents = customerPerWindowCents - discountCents;

  return {
    baseCatalogCents,
    fabricCatalogCents,
    accessoryCatalogCents,
    operatingCatalogCents,
    catalogPerWindowCents:
      selectedGridCatalogCents +
      accessoryCatalogCents +
      operatingCatalogCents,
    baseWholesaleCents,
    fabricWholesaleCents,
    accessoryWholesaleCents,
    operatingWholesaleCents,
    wholesalePerWindowCents:
      baseWholesaleCents +
      fabricWholesaleCents +
      accessoryWholesaleCents +
      operatingWholesaleCents,
    baseCustomerCents,
    fabricCustomerCents,
    accessoryCustomerCents,
    operatingCustomerCents,
    customerPerWindowCents,
    discountCents,
    unitPriceCents,
    lineTotalCents: unitPriceCents * scenario.quantity,
    pricedComponents,
  };
}

function measurementParts(value: number): {
  whole: number;
  fraction: "0" | "1/8";
} {
  const whole = Math.floor(value);
  const remainder = value - whole;
  if (remainder === 0) return { whole, fraction: "0" };
  if (Math.abs(remainder - 0.125) < 0.000_001) {
    return { whole, fraction: "1/8" };
  }
  throw new Error(`Golden measurement ${value} is not an exact UI eighth.`);
}

function lineForScenario(scenario: GoldenScenario): SalesQuoteLineItem {
  const width = measurementParts(scenario.cell.measuredWidth);
  const height = measurementParts(scenario.cell.measuredHeight);
  return {
    id: `golden-q${scenario.quoteIndex + 1}-line-${scenario.lineIndex + 1}`,
    quote_id: `golden-quote-${scenario.quoteIndex + 1}`,
    room_name: `Golden Room ${scenario.lineIndex + 1}`,
    product_type: "Roller Shades",
    width_whole: width.whole,
    width_fraction: width.fraction,
    height_whole: height.whole,
    height_fraction: height.fraction,
    quantity: scenario.quantity,
    sort_order: scenario.lineIndex,
    created_at: "2026-07-21T00:00:00.000Z",
  };
}

function designForScenario(
  line: SalesQuoteLineItem,
  scenario: GoldenScenario,
  stage: PricingStage,
): SalesQuoteDesign {
  const fixture = fixtureForStage(scenario, stage);
  const manualSurcharges =
    fixture.accessory.id && fixture.accessory.id !== "premium_hem_bar"
    ? [
        {
          id: fixture.accessory.id,
          quantity: fixture.accessory.units,
        },
      ]
    : [];
  const motorized = fixture.operation.liftSystem === "Motorized";
  return {
    id: `${line.id}-design-A`,
    line_item_id: line.id,
    variant: "A",
    product_type: line.product_type,
    supplier: "Norman",
    material: fixture.program.name,
    mount_type: "Inside Mount",
    shade_type: "Single Shade",
    lift_system: fixture.operation.liftSystem,
    valance: "No Valance",
    fabric: fixture.program.collection,
    motor_type: fixture.operation.motorType,
    remote_type: null,
    unit_price: 0,
    options_json: {
      quote_v2_backend: true,
      catalog_product_id: "roller",
      quote_lab_product_id: "roller",
      catalog_program_id: fixture.program.id,
      quote_lab_program_id: fixture.program.id,
      fabric_program_id: fixture.program.id,
      fabric_color_collection: fixture.program.collection,
      fabric_color_code: fixture.program.colorCode,
      fabric_color_name: fixture.program.colorName,
      roller_application: "Single Shade",
      roller_top_treatment: "No Top Treatment",
      top_treatment_class: "No Top Treatment",
      roller_tube: fixture.operation.tube,
      tube_class: fixture.operation.tube,
      hem_bar:
        fixture.accessory.id === "premium_hem_bar"
          ? "Premium Hem Bar"
          : "Fabric Covered",
      roller_power_configuration: fixture.operation.powerConfiguration,
      power_configuration: fixture.operation.powerConfiguration,
      motorization_selections: fixture.operation.motorizationSelections,
      roller_region_scope: "ca_ma",
      shipping_region: "continental_us",
      discount_percent: scenario.discountPercent,
      schedule_discount_percent: scenario.schedulePercent,
      surcharges: manualSurcharges,
    },
    ...(motorized ? {} : { motor_type: null }),
  } as unknown as SalesQuoteDesign;
}

function buildQuote(
  quoteIndex: number,
  stage: PricingStage,
): {
  input: ExactQuoteBuilderRepriceInput;
  scenarios: readonly GoldenScenario[];
} {
  const scenarios = Array.from({ length: ITEMS_PER_QUOTE }, (_, lineIndex) =>
    decodeScenario(quoteIndex, lineIndex),
  );
  const lines = scenarios.map(lineForScenario);
  const designs = scenarios.map((scenario, index) =>
    designForScenario(lines[index], scenario, stage),
  );
  return {
    input: {
      lines,
      designs,
      selectedVariantByLine: Object.fromEntries(
        lines.map((line) => [line.id, "A"]),
      ),
    },
    scenarios,
  };
}

function priceQuote(quoteIndex: number, stage: PricingStage): {
  quote: V2Quote;
  scenarios: readonly GoldenScenario[];
} {
  const built = buildQuote(quoteIndex, stage);
  const priced = repriceExactQuoteBuilderForQuoteLabPreview(built.input);
  if (!("backend" in priced) || priced.backend !== "v2") {
    throw new Error("Golden quote did not use the authoritative V2 backend.");
  }
  return { quote: priced, scenarios: built.scenarios };
}

function priceLineAlone(
  quoteIndex: number,
  lineIndex: number,
  stage: PricingStage,
): V2Quote {
  const scenario = decodeScenario(quoteIndex, lineIndex);
  const line = lineForScenario(scenario);
  const design = designForScenario(line, scenario, stage);
  const priced = repriceExactQuoteBuilderForQuoteLabPreview({
    lines: [line],
    designs: [design],
    selectedVariantByLine: { [line.id]: "A" },
  });
  if (!("backend" in priced) || priced.backend !== "v2") {
    throw new Error(
      `Golden line ${quoteIndex + 1}/${lineIndex + 1} did not use the authoritative V2 backend.`,
    );
  }
  return priced;
}

function componentCents(
  component: AuthoritativePriceComponent,
  key: "catalogAmount" | "wholesaleAmount" | "customerAmount",
): number {
  return cents(component[key]);
}

function pages(component: AuthoritativePriceComponent): readonly number[] {
  return component.source.pages ??
    (component.source.page === undefined ? [] : [component.source.page]);
}

function assertComponentProvenance(
  components: readonly AuthoritativePriceComponent[],
): void {
  for (const component of components) {
    expect(component.source.sourceId, component.id).toBeTruthy();
    expect(component.source.fileName, component.id).toBeTruthy();
    expect(component.source.revision, component.id).toBeTruthy();
    expect(component.source.sha256, component.id).toMatch(/^[a-f0-9]{64}$/);

    const hasPricedDollars =
      component.status === "priced" &&
      (component.catalogAmount !== 0 ||
        component.wholesaleAmount !== 0 ||
        component.customerAmount !== 0);
    if (hasPricedDollars) {
      expect(component.source.sourceId, component.id).toBe(
        "norman-retail-guide-2026-07",
      );
      expect(component.source.sha256, component.id).toBe(PRICE_BOOK_SHA256);
    }

    if (component.id === "accessory:autowand_included_charging_kit") {
      expect(component.status).toBe("included");
      expect(component.source.sourceId).toBe(
        "norman-motorization-guide-2026-05",
      );
      expect(component.source.sha256).toBe(MOTOR_GUIDE_SHA256);
      expect(pages(component)).toContain(83);
    }
  }
}

function comparableComponentAmounts(
  components: readonly AuthoritativePriceComponent[],
): readonly Readonly<{
  id: string;
  category: AuthoritativePriceComponent["category"];
  status: AuthoritativePriceComponent["status"];
  catalogCents: number;
  wholesaleCents: number;
  customerCents: number;
  units: number;
  billingScope: AuthoritativePriceComponent["billingScope"];
}>[] {
  return components
    .map((component) => ({
      id: component.id,
      category: component.category,
      status: component.status,
      catalogCents: componentCents(component, "catalogAmount"),
      wholesaleCents: componentCents(component, "wholesaleAmount"),
      customerCents: componentCents(component, "customerAmount"),
      units: component.units,
      billingScope: component.billingScope,
    }))
    .sort((left, right) => left.id.localeCompare(right.id));
}

function verifyQuote(
  quoteIndex: number,
  stage: PricingStage,
  quote: V2Quote,
  scenarios: readonly GoldenScenario[],
): void {
  expect(quote.designs).toHaveLength(ITEMS_PER_QUOTE);
  expect(quote.customerQuote.lines).toHaveLength(ITEMS_PER_QUOTE);
  expect(quote.sendability.lines).toHaveLength(ITEMS_PER_QUOTE);
  if (!quote.sendability.sendable) {
    const blockedDesigns = quote.designs
      .filter((entry) => !entry.result.ok)
      .map((entry) => ({
        designId: entry.designId,
        issues: entry.result.validationIssues,
      }));
    throw new Error(
      `Golden quote ${quoteIndex + 1} / ${stage} is not sendable:\n${JSON.stringify(
        { reasons: quote.sendability.reasons, blockedDesigns },
        null,
        2,
      )}`,
    );
  }

  let expectedQuoteTotalCents = 0;
  let expectedProductCostCents = 0;
  let expectedFreightCents = 0;
  let expectedProcessingFeeCents = 0;
  let expectedLandedCostCents = 0;
  let physicalUnitsBeforeLine = 0;
  let processingBasisCents = 0;

  scenarios.forEach((scenario, lineIndex) => {
    const expectation = expectedForStage(scenario, stage);
    const designId = `golden-q${quoteIndex + 1}-line-${lineIndex + 1}-design-A`;
    const priced = quote.designs.find((entry) => entry.designId === designId);
    expect(priced, designId).toBeDefined();
    if (!priced) return;
    const result = priced.result;
    if (!result.ok) {
      throw new Error(
        `${designId} / ${stage} blocked:\n${JSON.stringify(
          result.validationIssues,
          null,
          2,
        )}`,
      );
    }

    expect(result.matchedWidth).toBe(scenario.cell.matchedWidth);
    expect(result.matchedHeight).toBe(scenario.cell.matchedHeight);
    expect(result.quantity).toBe(scenario.quantity);
    expect(result.discountPercent).toBe(scenario.discountPercent);

    const base = result.components.find(
      (component) => component.category === "base_grid",
    );
    const fabric = result.components.find(
      (component) => component.category === "fabric_upgrade",
    );
    const operation = result.components.find(
      (component) => component.category === "operating_system",
    );
    expect(base).toBeDefined();
    expect(fabric).toBeDefined();
    expect(operation).toBeDefined();
    if (!base || !fabric || !operation) return;

    expect(componentCents(base, "catalogAmount")).toBe(
      expectation.baseCatalogCents,
    );
    expect(componentCents(base, "wholesaleAmount")).toBe(
      expectation.baseWholesaleCents,
    );
    expect(componentCents(base, "customerAmount")).toBe(
      expectation.baseCustomerCents,
    );
    expect(pages(base)).toContain(18);

    expect(componentCents(fabric, "catalogAmount")).toBe(
      expectation.fabricCatalogCents,
    );
    expect(componentCents(fabric, "wholesaleAmount")).toBe(
      expectation.fabricWholesaleCents,
    );
    expect(componentCents(fabric, "customerAmount")).toBe(
      expectation.fabricCustomerCents,
    );
    expect(pages(fabric)).toContain(
      fixtureForStage(scenario, stage).program.sourcePage,
    );

    expect(componentCents(operation, "catalogAmount")).toBe(
      expectation.operatingCatalogCents,
    );
    expect(componentCents(operation, "wholesaleAmount")).toBe(
      expectation.operatingWholesaleCents,
    );
    expect(componentCents(operation, "customerAmount")).toBe(
      expectation.operatingCustomerCents,
    );

    const pricedAccessories = result.components.filter(
      (component) =>
        component.category === "accessory" && component.status === "priced",
    );
    expect(
      pricedAccessories.reduce(
        (sum, component) => sum + componentCents(component, "catalogAmount"),
        0,
      ),
    ).toBe(expectation.accessoryCatalogCents);
    expect(
      pricedAccessories.reduce(
        (sum, component) => sum + componentCents(component, "wholesaleAmount"),
        0,
      ),
    ).toBe(expectation.accessoryWholesaleCents);
    expect(
      pricedAccessories.reduce(
        (sum, component) => sum + componentCents(component, "customerAmount"),
        0,
      ),
    ).toBe(expectation.accessoryCustomerCents);

    for (const expectedComponent of expectation.pricedComponents) {
      const actual = result.components.find(
        (component) => component.id === expectedComponent.id,
      );
      expect(actual, expectedComponent.id).toBeDefined();
      if (!actual) continue;
      expect(actual.category).toBe(expectedComponent.category);
      expect(componentCents(actual, "catalogAmount")).toBe(
        expectedComponent.catalogCents,
      );
      expect(componentCents(actual, "wholesaleAmount")).toBe(
        expectedComponent.wholesaleCents,
      );
      expect(componentCents(actual, "customerAmount")).toBe(
        expectedComponent.customerCents,
      );
      expect(pages(actual)).toContain(expectedComponent.sourcePage);
    }

    const included = result.components.filter(
      (component) => component.status === "included",
    );
    expect(included.length).toBeGreaterThan(0);
    expect(
      included.every(
        (component) =>
          component.catalogAmount === 0 &&
          component.wholesaleAmount === 0 &&
          component.customerAmount === 0,
      ),
    ).toBe(true);
    if (fixtureForStage(scenario, stage).operation.key.startsWith("autowand")) {
      expect(
        included.some(
          (component) =>
            component.id === "accessory:autowand_included_charging_kit",
        ),
      ).toBe(true);
    }

    assertComponentProvenance(result.components);

    expect(cents(result.componentTotals.catalogPerWindow)).toBe(
      expectation.catalogPerWindowCents,
    );
    expect(cents(result.componentTotals.wholesalePerWindow)).toBe(
      expectation.wholesalePerWindowCents,
    );
    expect(cents(result.componentTotals.customerPerWindow)).toBe(
      expectation.customerPerWindowCents,
    );
    expect(cents(result.discountAmount)).toBe(expectation.discountCents);
    expect(cents(result.unitPrice)).toBe(expectation.unitPriceCents);
    expect(cents(result.total)).toBe(expectation.lineTotalCents);

    expect(result.internalCost).toBeDefined();
    if (!result.internalCost) return;
    expect(cents(result.internalCost.productCostUnit)).toBe(
      expectation.wholesalePerWindowCents,
    );
    const productCostTotalCents =
      expectation.wholesalePerWindowCents * scenario.quantity;
    expect(cents(result.internalCost.productCostTotal)).toBe(
      productCostTotalCents,
    );

    const totalUnitsAfterLine = physicalUnitsBeforeLine + scenario.quantity;
    const freightBefore =
      physicalUnitsBeforeLine === 0
        ? 0
        : cents(25 + 11 * (physicalUnitsBeforeLine - 1));
    const freightAfter = cents(25 + 11 * (totalUnitsAfterLine - 1));
    const lineFreightCents = freightAfter - freightBefore;
    const processingBeforeCents = processingFeeCents(processingBasisCents);
    processingBasisCents += productCostTotalCents + lineFreightCents;
    const lineProcessingFeeCents =
      processingFeeCents(processingBasisCents) - processingBeforeCents;
    expect(cents(result.internalCost.freightAllocated)).toBe(
      lineFreightCents,
    );
    expect(cents(result.internalCost.oversizeAllocated)).toBe(0);
    expect(cents(result.internalCost.processingFeeAllocated)).toBe(
      lineProcessingFeeCents,
    );
    expect(cents(result.internalCost.landedCostTotal)).toBe(
      productCostTotalCents + lineFreightCents + lineProcessingFeeCents,
    );

    physicalUnitsBeforeLine = totalUnitsAfterLine;
    expectedQuoteTotalCents += expectation.lineTotalCents;
    expectedProductCostCents += productCostTotalCents;
    expectedFreightCents += lineFreightCents;
    expectedProcessingFeeCents += lineProcessingFeeCents;
    expectedLandedCostCents +=
      productCostTotalCents + lineFreightCents + lineProcessingFeeCents;
  });

  expect(cents(quote.total)).toBe(expectedQuoteTotalCents);
  expect(cents(quote.customerQuote.total)).toBe(expectedQuoteTotalCents);
  expect(cents(quote.costSummary.productCost)).toBe(
    expectedProductCostCents,
  );
  expect(cents(quote.costSummary.freightHandling)).toBe(
    expectedFreightCents,
  );
  expect(cents(quote.costSummary.oversize)).toBe(0);
  expect(cents(quote.costSummary.processingFee)).toBe(
    expectedProcessingFeeCents,
  );
  expect(cents(quote.costSummary.dealerCostTotal)).toBe(
    expectedLandedCostCents,
  );
  expect(quote.costSummary.status).toBe("complete");

  const customerJson = JSON.stringify(quote.customerQuote);
  expect(customerJson).not.toMatch(
    /wholesale|catalogAmount|dealerFactor|freight|processing|landedCost|margin/i,
  );
}

describe("Norman Roller 20-quote x 20-item source-grid acceptance", () => {
  it("pins the live portal grouping, freight, and processing fixture", () => {
    expect(portalFixture).toMatchObject({
      captureMode: "read_only_unsubmitted_draft",
      accountIdRedacted: true,
      verifiedFacts: expect.arrayContaining([
        "roller_standard_factor",
        "roller_shutter_lead_time_factor",
        "continental_blinds_shades_freight",
        "processing_fee_on_merchandise_plus_freight",
        "portal_surcharge_group_rounding",
      ]),
      notVerified: expect.arrayContaining([
        "oversize_processing_fee_basis",
        "hi_ak_freight",
        "shutter_freight",
      ]),
      list: {
        baseDollars: 254,
        groupedSurchargeDollars: 96,
        subtotalDollars: 350,
      },
      standard: {
        selectedSchedulePercent: 30,
        effectivePortalFactor: 0.33,
        baseDealerNetDollars: 83.82,
        groupedSurchargeDealerNetDollars: 31.68,
        productSubtotalDealerNetDollars: 115.5,
        oneUnit: {
          merchandiseDollars: 115.5,
          freightDollars: 25,
          processingDollars: 2.81,
          grandTotalDollars: 143.31,
        },
        twoUnits: {
          merchandiseDollars: 231,
          freightDollars: 36,
          processingDollars: 5.34,
          grandTotalDollars: 272.34,
        },
      },
      shutterLeadTime: {
        selectedSchedulePercent: 28.5,
        effectivePortalFactor: 0.297,
        baseDealerNetDollars: 75.44,
        groupedSurchargeDealerNetDollars: 28.51,
        productSubtotalDealerNetDollars: 103.95,
        oneUnit: {
          freightDollars: 25,
          processingDollars: 2.58,
          grandTotalDollars: 131.53,
        },
        twoUnits: {
          freightDollars: 36,
          processingDollars: 4.88,
          grandTotalDollars: 248.78,
        },
      },
    });
    expect(
      dollarsToCents(portalFixture.list.baseDollars) +
        dollarsToCents(portalFixture.list.groupedSurchargeDollars),
    ).toBe(dollarsToCents(portalFixture.list.subtotalDollars));

    for (const schedule of [
      portalFixture.standard,
      portalFixture.shutterLeadTime,
    ]) {
      expect(
        dollarsToCents(schedule.baseDealerNetDollars) +
          dollarsToCents(schedule.groupedSurchargeDealerNetDollars),
      ).toBe(dollarsToCents(schedule.productSubtotalDealerNetDollars));
      expect(
        Math.round(
          dollarsToCents(portalFixture.list.baseDollars) *
            schedule.effectivePortalFactor,
        ),
      ).toBe(dollarsToCents(schedule.baseDealerNetDollars));
      expect(
        Math.round(
          dollarsToCents(portalFixture.list.groupedSurchargeDollars) *
            schedule.effectivePortalFactor,
        ),
      ).toBe(dollarsToCents(schedule.groupedSurchargeDealerNetDollars));
      expect(schedule.twoUnits.freightDollars).toBe(
        schedule.oneUnit.freightDollars + 11,
      );
      expect(
        centsToDollars(
          Math.round(
            (dollarsToCents(schedule.productSubtotalDealerNetDollars) +
              dollarsToCents(schedule.oneUnit.freightDollars)) *
              0.02,
          ),
        ),
      ).toBe(schedule.oneUnit.processingDollars);
      expect(
        centsToDollars(
          Math.round(
            (dollarsToCents(schedule.productSubtotalDealerNetDollars) * 2 +
              dollarsToCents(schedule.twoUnits.freightDollars)) *
              0.02,
          ),
        ),
      ).toBe(schedule.twoUnits.processingDollars);
    }

    expect(portalFixture.standard.oneUnit.merchandiseDollars).toBe(
      portalFixture.standard.productSubtotalDealerNetDollars,
    );
    expect(portalFixture.standard.twoUnits.merchandiseDollars).toBe(
      portalFixture.standard.productSubtotalDealerNetDollars * 2,
    );
    expect(
      centsToDollars(
        dollarsToCents(portalFixture.standard.oneUnit.merchandiseDollars) +
          dollarsToCents(portalFixture.standard.oneUnit.freightDollars) +
          dollarsToCents(portalFixture.standard.oneUnit.processingDollars),
      ),
    ).toBe(portalFixture.standard.oneUnit.grandTotalDollars);
    expect(
      centsToDollars(
        dollarsToCents(portalFixture.standard.twoUnits.merchandiseDollars) +
          dollarsToCents(portalFixture.standard.twoUnits.freightDollars) +
          dollarsToCents(portalFixture.standard.twoUnits.processingDollars),
      ),
    ).toBe(portalFixture.standard.twoUnits.grandTotalDollars);
    expect(
      centsToDollars(
        dollarsToCents(
          portalFixture.shutterLeadTime.productSubtotalDealerNetDollars,
        ) +
          dollarsToCents(
            portalFixture.shutterLeadTime.oneUnit.freightDollars,
          ) +
          dollarsToCents(
            portalFixture.shutterLeadTime.oneUnit.processingDollars,
          ),
      ),
    ).toBe(portalFixture.shutterLeadTime.oneUnit.grandTotalDollars);
    expect(
      centsToDollars(
        dollarsToCents(
          portalFixture.shutterLeadTime.productSubtotalDealerNetDollars,
        ) *
          2 +
          dollarsToCents(
            portalFixture.shutterLeadTime.twoUnits.freightDollars,
          ) +
          dollarsToCents(
            portalFixture.shutterLeadTime.twoUnits.processingDollars,
          ),
      ),
    ).toBe(portalFixture.shutterLeadTime.twoUnits.grandTotalDollars);
  });

  it("pins the source PDF identity and all 60 literal grid cells used by the oracle", () => {
    const source = QUOTE_V2_SOURCE_MANIFEST.find(
      (entry) => entry.id === "norman-retail-guide-2026-07",
    );
    expect(source).toMatchObject({
      revision: "2026-07",
      effectiveDate: "2026-07-01",
      sha256: PRICE_BOOK_SHA256,
      pageCount: 40,
    });
    const dealerPortalSource = QUOTE_V2_SOURCE_MANIFEST.find(
      (entry) => entry.id === "norman-dealer-pricing-snapshot-2026-07-20",
    );
    expect(dealerPortalSource).toMatchObject({
      revision: "Other-dealer portal print dated 2026-07-20",
      pageCount: 3,
      authorities: [],
    });
    expect(NORMAN_805_DEALER_POLICY).toMatchObject({
      verifiedOn: "2026-07-21",
      runtimeVerification: {
        channel: "authenticated_live_dealer_portal",
        fixtureId: portalFixture.id,
      },
      publishedFreightSource: {
        sourceId: "norman-retail-guide-2026-07",
        sha256: PRICE_BOOK_SHA256,
        page: 4,
      },
      quarantinedEvidence: {
        sourceId: "norman-dealer-pricing-snapshot-2026-07-20",
        dealer: "redacted_non_805_account",
        runtimeAuthority: false,
      },
      dealerFactors: {
        standard: STANDARD_FACTOR_NUMERATOR / FACTOR_DENOMINATOR,
        shutterLeadTime: SLOW_FACTOR_NUMERATOR / FACTOR_DENOMINATOR,
      },
      freight: {
        continentalUsBlindsAndShades: {
          firstUnit: 25,
          additionalUnit: 11,
        },
      },
    });

    const product = getProduct("roller");
    expect(product?.dealerFactor).toBe(0.3);
    if (!product) return;

    for (const programFixture of PROGRAMS) {
      const program = getProgram(product, programFixture.id);
      expect(program, programFixture.id).toBeDefined();
      if (!program) continue;
      expect(program.pricingFamilyId).toBe("roller_cordless_fabric");
      expect(program.baselineProgramId).toBe(PROGRAMS[0].id);
      expect(program.sourcePages).toContain(programFixture.sourcePage);
      for (const cell of GOLDEN_CELLS) {
        expect(
          program.grid.prices[cell.heightIndex]?.[cell.widthIndex],
          `${program.id} ${cell.matchedWidth}x${cell.matchedHeight}`,
        ).toBe(sourceGridDollars(programFixture.id, cell));
      }
    }
  });

  for (let quoteIndex = 0; quoteIndex < QUOTE_COUNT; quoteIndex += 1) {
    it(`progressively verifies quote ${quoteIndex + 1} across 20 different grid items`, () => {
      const pricedStages = Object.fromEntries(
        STAGES.map((stage) => [stage, priceQuote(quoteIndex, stage)]),
      ) as Record<
        PricingStage,
        { quote: V2Quote; scenarios: readonly GoldenScenario[] }
      >;

      for (const stage of STAGES) {
        verifyQuote(
          quoteIndex,
          stage,
          pricedStages[stage].quote,
          pricedStages[stage].scenarios,
        );
      }

      for (let lineIndex = 0; lineIndex < ITEMS_PER_QUOTE; lineIndex += 1) {
        const scenario = pricedStages.operation.scenarios[lineIndex];
        const designId = `golden-q${quoteIndex + 1}-line-${lineIndex + 1}-design-A`;
        const result = (stage: PricingStage) => {
          const found = pricedStages[stage].quote.designs.find(
            (entry) => entry.designId === designId,
          )?.result;
          if (!found?.ok) {
            throw new Error(`${designId} did not price during ${stage}.`);
          }
          return found;
        };
        const base = result("base");
        const fabric = result("fabric");
        const accessories = result("accessories");
        const operation = result("operation");
        const expectedBase = expectedForStage(scenario, "base");
        const expectedFabric = expectedForStage(scenario, "fabric");
        const expectedAccessories = expectedForStage(scenario, "accessories");
        const expectedOperation = expectedForStage(scenario, "operation");

        // Second route: reprice every stage as its own one-line quote. This
        // proves Base -> Fabric -> Accessories -> Operating is invariant to
        // the other 19 items, not only correct inside the aggregate quote.
        for (const stage of STAGES) {
          const staged = result(stage);
          const standaloneQuote = priceLineAlone(
            quoteIndex,
            lineIndex,
            stage,
          );
          const standalone = standaloneQuote.designs[0]?.result;
          if (!standalone?.ok) {
            throw new Error(
              `${designId} failed the standalone ${stage} reconciliation.`,
            );
          }
          expect(standalone.componentTotals, `${designId}/${stage}`).toEqual(
            staged.componentTotals,
          );
          expect(
            comparableComponentAmounts(standalone.components),
            `${designId}/${stage}`,
          ).toEqual(comparableComponentAmounts(staged.components));
          expect(standalone.discountAmount, `${designId}/${stage}`).toBe(
            staged.discountAmount,
          );
          expect(standalone.unitPrice, `${designId}/${stage}`).toBe(
            staged.unitPrice,
          );
          expect(standalone.total, `${designId}/${stage}`).toBe(staged.total);
          expect(
            standalone.internalCost?.productCostUnit,
            `${designId}/${stage}`,
          ).toBe(staged.internalCost?.productCostUnit);
          expect(
            standalone.internalCost?.productCostTotal,
            `${designId}/${stage}`,
          ).toBe(staged.internalCost?.productCostTotal);
          expect(
            cents(standaloneQuote.customerQuote.total),
            `${designId}/${stage}`,
          ).toBe(cents(staged.total));
        }

        expect(
          cents(fabric.componentTotals.catalogPerWindow) -
            cents(base.componentTotals.catalogPerWindow),
        ).toBe(
          expectedFabric.catalogPerWindowCents -
            expectedBase.catalogPerWindowCents,
        );
        expect(
          cents(accessories.componentTotals.catalogPerWindow) -
            cents(fabric.componentTotals.catalogPerWindow),
        ).toBe(
          expectedAccessories.catalogPerWindowCents -
            expectedFabric.catalogPerWindowCents,
        );
        expect(
          cents(operation.componentTotals.catalogPerWindow) -
            cents(accessories.componentTotals.catalogPerWindow),
        ).toBe(
          expectedOperation.catalogPerWindowCents -
            expectedAccessories.catalogPerWindowCents,
        );
        expect(cents(operation.total) - cents(accessories.total)).toBe(
          expectedOperation.lineTotalCents -
            expectedAccessories.lineTotalCents,
        );
      }

      const expectedStageTotal = (stage: PricingStage) =>
        pricedStages[stage].scenarios.reduce(
          (sum, scenario) => sum + expectedForStage(scenario, stage).lineTotalCents,
          0,
        );
      expect(
        cents(pricedStages.fabric.quote.total) -
          cents(pricedStages.base.quote.total),
      ).toBe(expectedStageTotal("fabric") - expectedStageTotal("base"));
      expect(
        cents(pricedStages.accessories.quote.total) -
          cents(pricedStages.fabric.quote.total),
      ).toBe(
        expectedStageTotal("accessories") - expectedStageTotal("fabric"),
      );
      expect(
        cents(pricedStages.operation.quote.total) -
          cents(pricedStages.accessories.quote.total),
      ).toBe(
        expectedStageTotal("operation") - expectedStageTotal("accessories"),
      );
    });
  }

  it("repeats all 400 final lines as an independent aggregate reconciliation", () => {
    const fingerprints = new Set<string>();
    let checkedLines = 0;
    let aggregateCatalogCents = 0;
    let aggregateBaseCatalogCents = 0;
    let aggregateFabricCatalogCents = 0;
    let aggregateAccessoryCatalogCents = 0;
    let aggregateOperatingCatalogCents = 0;
    let aggregateCustomerCents = 0;
    let aggregateWholesaleCents = 0;
    let aggregateFreightCents = 0;
    let aggregateProcessingFeeCents = 0;
    let aggregateLandedCostCents = 0;

    for (let quoteIndex = 0; quoteIndex < QUOTE_COUNT; quoteIndex += 1) {
      const { quote, scenarios } = priceQuote(quoteIndex, "operation");
      verifyQuote(quoteIndex, "operation", quote, scenarios);
      aggregateCustomerCents += cents(quote.total);
      aggregateWholesaleCents += cents(quote.costSummary.productCost);
      aggregateFreightCents += cents(quote.costSummary.freightHandling);
      aggregateProcessingFeeCents += cents(quote.costSummary.processingFee);
      aggregateLandedCostCents += cents(quote.costSummary.dealerCostTotal);
      for (const [lineIndex, priced] of quote.designs.entries()) {
        if (!priced.result.ok) {
          throw new Error(`${priced.designId} failed the aggregate pass.`);
        }
        const standaloneQuote = priceLineAlone(
          quoteIndex,
          lineIndex,
          "operation",
        );
        const standalone = standaloneQuote.designs[0]?.result;
        if (!standalone?.ok) {
          throw new Error(
            `${priced.designId} failed the standalone reconciliation pass.`,
          );
        }

        // This second route executes the same selection as its own one-line
        // quote. Product and customer calculations must be invariant to the
        // other 19 lines; order-level freight is deliberately excluded.
        expect(standalone.componentTotals, priced.designId).toEqual(
          priced.result.componentTotals,
        );
        expect(standalone.discountAmount, priced.designId).toBe(
          priced.result.discountAmount,
        );
        expect(standalone.unitPrice, priced.designId).toBe(
          priced.result.unitPrice,
        );
        expect(standalone.total, priced.designId).toBe(priced.result.total);
        expect(
          comparableComponentAmounts(standalone.components),
          priced.designId,
        ).toEqual(comparableComponentAmounts(priced.result.components));
        expect(standalone.internalCost?.productCostUnit, priced.designId).toBe(
          priced.result.internalCost?.productCostUnit,
        );
        expect(standalone.internalCost?.productCostTotal, priced.designId).toBe(
          priced.result.internalCost?.productCostTotal,
        );
        expect(cents(standaloneQuote.customerQuote.total), priced.designId).toBe(
          cents(priced.result.total),
        );

        aggregateCatalogCents += cents(
          priced.result.componentTotals.catalogPerWindow,
        );
        for (const component of priced.result.components) {
          const catalogCents = componentCents(component, "catalogAmount");
          if (component.category === "base_grid") {
            aggregateBaseCatalogCents += catalogCents;
          } else if (component.category === "fabric_upgrade") {
            aggregateFabricCatalogCents += catalogCents;
          } else if (component.category === "accessory") {
            aggregateAccessoryCatalogCents += catalogCents;
          } else if (component.category === "operating_system") {
            aggregateOperatingCatalogCents += catalogCents;
          }
        }
        fingerprints.add(priced.result.selectionFingerprint);
        checkedLines += 1;
      }
    }

    expect(checkedLines).toBe(QUOTE_COUNT * ITEMS_PER_QUOTE);
    expect(fingerprints.size).toBe(QUOTE_COUNT * ITEMS_PER_QUOTE);
    expect(aggregateCatalogCents).toBe(
      aggregateBaseCatalogCents +
        aggregateFabricCatalogCents +
        aggregateAccessoryCatalogCents +
        aggregateOperatingCatalogCents,
    );
    // These component and quote checksums are intentionally literal. They make
    // a one-cent mutation to any grid, option, motor, discount, quantity, or
    // freight rule fail even if somebody accidentally changes the oracle
    // alongside it.
    expect({
      base: aggregateBaseCatalogCents,
      fabric: aggregateFabricCatalogCents,
      accessories: aggregateAccessoryCatalogCents,
      operating: aggregateOperatingCatalogCents,
      total: aggregateCatalogCents,
    }).toEqual({
      base: 13_468_000,
      fabric: 1_740_900,
      accessories: 1_471_300,
      operating: 4_088_500,
      total: 20_768_700,
    });
    expect(aggregateCustomerCents).toBe(37_601_165);
    expect(aggregateWholesaleCents).toBe(13_308_877);
    expect(aggregateFreightCents).toBe(908_000);
    expect(aggregateProcessingFeeCents).toBe(284_339);
    expect(aggregateLandedCostCents).toBe(
      aggregateWholesaleCents +
        aggregateFreightCents +
        aggregateProcessingFeeCents,
    );
    expect(aggregateLandedCostCents).toBe(14_501_216);
  });
});
