import type { ValidationIssue } from './core';
import { isNonNormanOrderingOnlyRule } from '@/lib/quote/non-norman-ordering-only';

/** Owner policy: quotes use grids and priced options; fabrication checks are separate. */
export const GRID_OPTION_QUOTING_EFFECTIVE_FROM = '2026-09-21';

// These rules do not supply a grid identity, billable dimension or option charge.
// Keep unknown rules blocking: a new price-dependent rule must never silently disappear.
const ORDER_ONLY_RULES = new Set([
// Current Norman quote-only audit. Unknown rule IDs remain hard blocks.
  // Roman September guide pp13–24; motorization guide pp24/76/85. No charge varies with these installation/control dimensions.
  'roman.hardware.chain_length',
  'roman.hardware.chain_color',
  'roman.hardware.chain_location',
  'roman.hardware.pole_length',
  'roman.hardware.shim_mount',
  'roman.hardware.hold_down_mount',
  'roman.hardware.magnet_color',
  'roman.hardware.banding_layout',
  'roman.hardware.valance_returns',
  'roman.accessory.remote_channel',
  'roman.accessory.network',
  'roman.accessory.wand_length',
  'roman.accessory.wand_color',
  'roman.accessory.wand_only',
  'roman.accessory.extension_color',
  'roman.fabric_limits.f0031_height',
  'roman.fabric_limits.no_vertical_seam_width',
  'roman.fabric_limits.matched_headrail',
  'roman.dimension.width',
  'roman.dimension.height',
  'roman.dimension.area',
  'roman.day_night.rear_fabric.max_width',
  'roman.day_night.max_ratio',
  'roman.fabric.not_joinable',
  'roman.f0031.railroad.max_height',
  'roman.side_by_side.configuration_exclusion',
  'roman.common_valance.max_total_width',
  // Honeycomb guide pp6/37–49; each Butt Together shade is priced separately (p38).
  'honeycomb.hardware.installation',
  'honeycomb.hardware.plate',
  'honeycomb.hardware.plate_required',
  'honeycomb.hardware.pole_length',
  'honeycomb.hardware.magnet_color',
  'honeycomb.hardware.light_guard_color',
  'honeycomb.hardware.skylight_guard_color',
  'honeycomb.mounting.holder',
  'honeycomb.accessory.channel',
  'honeycomb.accessory.network',
  'honeycomb.accessory.cable_exit',
  'honeycomb.accessory.wand_length',
  'honeycomb.accessory.wand_color',
  'honeycomb.accessory.extension_color',
  'honeycomb.vertical.pair_mode',
  'honeycomb.vertical.pair_group',
  'honeycomb.vertical.pair_position',
  'honeycomb.vertical.pair_operation',
  'honeycomb.vertical.pair_stack',
  'honeycomb.vertical.pair_mount_type',
  'honeycomb.vertical.pair_quantity',
  'honeycomb.vertical.pair_members',
  'honeycomb.vertical.pair_height',
  'honeycomb.vertical.pair_mount',
  'honeycomb.matrix.smartrise_tall_min_width',
  'honeycomb.matrix.tdbu_tall_min_width',
  'honeycomb.matrix.cord_loop_td_day_night_tall_min_width',
  'honeycomb.matrix.woven_narrow_max_height',
  'honeycomb.matrix.woven_ashton_86_envelope',
  'honeycomb.matrix.vertical_fr_max_height',
  'honeycomb.matrix.side_mount.inside_only',
  'honeycomb.matrix.side_mount.system_ineligible',
  'honeycomb.matrix.side_mount.max_width',
  'honeycomb.matrix.side_by_side.system_ineligible',
  'honeycomb.matrix.side_by_side.exact_match_required',
  'honeycomb.matrix.slope_angle',
  'honeycomb.matrix.frame.notch_required',
  'honeycomb.matrix.frame.notch_dimensions',
  'honeycomb.matrix.specialty.net_measurements',
  'honeycomb.matrix.specialty.windsong_net_max',
  'honeycomb.matrix.specialty.inside_only',
  'honeycomb.matrix.specialty.templates_not_accepted',
  'honeycomb.matrix.specialty.non_operable',
  'honeycomb.matrix.specialty.perfect_arch_ratio',
  'honeycomb.matrix.specialty.eyebrow_ratio',
  'honeycomb.matrix.specialty.quarter_round_ratio',
  'honeycomb.matrix.specialty.half_eyebrow_ratio',
  'honeycomb.matrix.specialty.elongated_eyebrow_legs',
  'honeycomb.matrix.specialty.arch_on_top_leg',
  'honeycomb.matrix.cutout.width',
  'honeycomb.matrix.cutout.height',
  'honeycomb.matrix.cutout.vertical_height',
  'honeycomb.matrix.two_on_one.max_per_shade_width',
  'honeycomb.matrix.two_on_one.max_per_shade_area',
  'honeycomb.matrix.two_on_one.smartrise_tall_per_shade_min_width',
  'honeycomb.matrix.two_on_one.smartrise_tall_min_width',
  'honeycomb.motorization.charging_wand.side_mount_incompatible',
  // SmartFold September pp22–23/34; PerfectSheer pp32–33; SmartDrape pp6/17–23.
  'norman.smartfold.size',
  'norman.smartfold.ratio',
  'norman.smartfold.cordless_narrow',
  'norman.smartfold.louise_cordless_height',
  'norman.smartfold.full_fold_height',
  'norman.smartfold.fabric_size',
  'norman.smartfold.louise_valance',
  'norman.smartfold.chain_length',
  'norman.smartfold.outside_bracket',
  'norman.smartfold.premium_hem_end_cap',
  'norman.smartfold.plain_hem_end_cap',
  'norman.perfectsheer.dimensions',
  'norman.perfectsheer.ratio',
  'norman.perfectsheer.chain_length',
  'norman.perfectsheer.chain_control',
  'norman.smartdrape.dimensions',
  'norman.smartdrape.area',
  'norman.smartdrape.motor_position',
  'norman.smartdrape.wand_length',
  'norman.smartdrape.ceiling_pocket',
  'norman.smartdrape.pocket_dimensions',
  'norman.smartdrape.pocket_table_gap',
  'norman.smartdrape.pair_id',
  'norman.smartdrape.pair_position',
  'norman.smartdrape.pair_stack',
  'norman.smartdrape.stale_pair',
  'norman.smartdrape.height',
  'norman.smartdrape.operation',
  'norman.smartdrape.room',
  'norman.smartdrape.mount',
  'smartdrape.motorization.position',
  // Blind guides: CityLights pp7–8/16–19; Wood pp7–8/15–20; Ultimate Faux pp6–7/10–15; SmartPrivacy pp7–11.
  'norman.citylights.dimensions',
  'norman.citylights.wand_side',
  'norman.citylights.wand_drop',
  'norman.citylights.installation',
  'norman.citylights.side_mount',
  'norman.citylights.matching_group',
  'norman.citylights.matching',
  'norman.wood_blinds.dimensions',
  'norman.wood_blinds.wand_side',
  'norman.wood_blinds.wand_drop',
  'norman.wood_blinds.wand_running_change',
  'norman.wood_blinds.returns',
  'norman.wood_blinds.return_size',
  'norman.wood_blinds.side_mount',
  'norman.wood_blinds.bracket_installation',
  'norman.wood_blinds.cutout_left_width',
  'norman.wood_blinds.cutout_left_height',
  'norman.wood_blinds.cutout_right_width',
  'norman.wood_blinds.cutout_right_height',
  'norman.wood_blinds.keystone_layout',
  'norman.wood_blinds.keystone_spacing',
  'norman.ultimate_faux.dimensions',
  'norman.ultimate_faux.wand_side',
  'norman.ultimate_faux.wand_drop',
  'norman.ultimate_faux.returns',
  'norman.ultimate_faux.return_size',
  'norman.ultimate_faux.side_mount',
  'norman.ultimate_faux.bracket_installation',
  'norman.ultimate_faux.cutout_width',
  'norman.ultimate_faux.cutout_height',
  'norman.ultimate_faux.keystone_layout',
  'norman.ultimate_faux.keystone_spacing',
  'norman.smartprivacy.dimensions',
  'norman.smartprivacy.wand_side',
  'norman.smartprivacy.wand',
  'norman.smartprivacy.returns',
  'norman.smartprivacy.return_size',
  'norman.smartprivacy.side_mount',
  'norman.smartprivacy.bracket_installation',
  // Synchrony pp6–7/10–12 and Palladian p5: grid identities/counts are independent of these installation facts.
  'vertical.required.stack_option',
  'vertical.required.draw_direction',
  'vertical.dimension.width',
  'vertical.dimension.height',
  'vertical.stack_draw',
  'vertical.hardware_color',
  'vertical.wand_drop.invalid',
  'vertical.side_by_side.wand_orientation_required',
  'vertical.side_by_side.center_opening_prohibited',
  'vertical.shims.outside_mount_only',
  'norman.palladian_shelf.depth',
  'norman.palladian_shelf.depth_increment',
  'norman.palladian_shelf.load',
  'norman.palladian_shelf.mount',
  // Shutter binders: construction schedules only. Frame pricing and unknown custom charges remain strict.
  'norman.shutter.assortment.hinge',
  'norman.shutter.assortment.mixed_panel_width',
  'norman.shutter.assortment.panel_width',
  'norman.shutter.assortment.construction_layout',
  'norman.shutter.assortment.stile_profile',
  'norman.shutter.assortment.stile_width',
  'norman.shutter.assortment.stile_join',
  'norman.shutter.assortment.single_panel_join',
  'norman.shutter.assortment.panel_closure',
  'norman.shutter.bifold90.special_layout',
  'norman.shutter.bifold90.layout_mismatch',
  'norman.shutter.bifold90.mount',
  'norman.shutter.bifold90.panel_count',
  'norman.shutter.bifold90.panel_width',
  'norman.shutter.bifold90.stile',
  'norman.shutter.bifold90.floating_side_boards',
  'norman.shutter.bifold90.stopper_positions',
  'norman.shutter.bifold90.header',
  'norman.shutter.bifold90.fascia',
  'norman.shutter.bifold90.flat_surface',
  'norman.shutter.bifold90.extension',
  'norman.shutter.bifold90.frame_hinged_details',
  'norman.shutter.bifold90.frame_buildout',
  'norman.shutter.bifold90.bottom',
  'norman.shutter.bifold90.frame_hinge',
  'norman.shutter.bifold90.door',
  'norman.shutter.bifold90.ring_pull',
  'norman.shutter.bifold90.stale_ring_pull',
  'norman.shutter.bifold90.unequal_stack_anchors',
  'norman.shutter.bifold90.uneven_panel_width',
  'norman.shutter.bifold180.schedule_required',
  'norman.shutter.bifold180.layout',
  'norman.shutter.bifold180.layout_mismatch',
  'norman.shutter.bifold180.outside_mount',
  'norman.shutter.bifold180.flat_surface',
  'norman.shutter.bifold180.stile',
  'norman.shutter.bifold180.construction_required',
  'norman.shutter.bifold180.measurement_basis',
  'norman.shutter.bifold180.header',
  'norman.shutter.bifold180.fascia',
  'norman.shutter.bifold180.header_extension',
  'norman.shutter.bifold180.baseboard',
  'norman.shutter.bifold180.pivot',
  'norman.shutter.bifold180.light_block',
  'norman.shutter.bifold180.panel_count',
  'norman.shutter.bifold180.panel_width',
  'norman.shutter.bifold90.schedule_required',
  'norman.shutter.bifold90.subtype_geometry',
  'norman.shutter.bifold90.layout',
  'norman.shutter.bifold90.layout_mismatch',
  'norman.shutter.bifold90.mount',
  'norman.shutter.bifold90.measurement_basis',
  'norman.shutter.bifold90.casing_basis',
  'norman.shutter.bifold90.flat_surface',
  'norman.shutter.bifold90.header',
  'norman.shutter.bifold90.fascia',
  'norman.shutter.bifold90.extension',
  'norman.shutter.bifold90.stile',
  'norman.shutter.bifold90.panel_count',
  'norman.shutter.bifold90.panel_width',
  'norman.shutter.support.record_required',
  'norman.shutter.support.missing_support',
  'norman.shutter.support.gap',
  'norman.shutter.support.frequent_open',
  'norman.shutter.bypass.record_required',
  'norman.shutter.bypass.layout_geometry',
  'norman.shutter.bypass.front_panel',
  'norman.shutter.bypass.panel_count',
  'norman.shutter.bypass.mount',
  'norman.shutter.bypass.side_frames',
  'norman.shutter.bypass.measurement',
  'norman.shutter.bypass.outside_width_geometry',
  'norman.shutter.bypass.bottom_guide',
  'norman.shutter.bypass.panel_width',
  'norman.shutter.dividers.record_required',
  'norman.shutter.dividers.section_louvers',
  'norman.shutter.dividers.equal_louver_counts',
  'norman.shutter.dividers.split_mode',
  'norman.shutter.dividers.split_location_required',
  'norman.shutter.dividers.split_geometry',
  'norman.shutter.dividers.rail_identity',
  'norman.shutter.dividers.split_reference',
  'norman.shutter.dividers.measurement_basis',
  'norman.shutter.dividers.rail_required',
  'norman.shutter.dividers.size',
  'norman.shutter.dividers.location',
  'norman.shutter.dividers.center_geometry',
  'norman.shutter.dividers.position',
  'norman.shutter.dividers.split_identity',
  'norman.shutter.dividers.split_position',
  'norman.shutter.dividers.duplicate_position',
  'norman.shutter.dividers.louver_clearance',
  'norman.shutter.double_hung.record_required',
  'norman.shutter.double_hung.row_layout',
  'norman.shutter.double_hung.layout_identity',
  'norman.shutter.double_hung.panel_count',
  'norman.shutter.double_hung.panel_width',
  'norman.shutter.double_hung.width_summary',
  'norman.shutter.double_hung.division',
  'norman.shutter.double_hung.custom_division',
  'norman.shutter.double_hung.tpost_choice',
  'norman.shutter.double_hung.tpost_length',
  'norman.shutter.double_hung.tpost_inactive',
  'norman.shutter.double_hung.wide_woodlore_tpost',
  'norman.shutter.double_hung.extra_hinge',
  'norman.shutter.french_door.record_required',
  'norman.shutter.french_door.one_panel',
  'norman.shutter.french_door.panel_width',
  'norman.shutter.french_door.top_shape',
  'norman.shutter.french_door.measurement_form',
  'norman.shutter.french_door.panel_lock',
  'norman.shutter.french_door.batten_top',
  'norman.shutter.french_door.batten_frame',
  'norman.shutter.french_door.batten_louver',
  'norman.shutter.french_door.batten_dimensions',
  'norman.shutter.french_door.narrow_stile',
  'norman.shutter.french_door.mount',
  'norman.shutter.panels.record_required',
  'norman.shutter.panels.application_geometry',
  'norman.shutter.panels.panel_count',
  'norman.shutter.panels.height',
  'norman.shutter.panels.divider_choice',
  'norman.shutter.panels.divider_required',
  'norman.shutter.panels.divider_geometry',
  'norman.shutter.regular.panel_schedule',
  'norman.shutter.regular.panel_width',
  'norman.shutter.regular.width_summary',
  'norman.shutter.regular.hang_strip',
  'norman.shutter.regular.narrow_join',
  'norman.shutter.single_louver.count',
  'norman.shutter.single_louver.double_hung',
  'norman.shutter.single_louver.division',
  'norman.shutter.single_louver.mouse_hole',
  'norman.shutter.specialty.record_required',
  'norman.shutter.specialty.construction_required',
  'norman.shutter.specialty.curved_tilt',
  'norman.shutter.specialty.curved_top_louver',
  'norman.shutter.specialty.frame_construction_curve',
  'norman.shutter.specialty.frame_construction',
  'norman.shutter.specialty.frame_in_rail_shape',
  'norman.shutter.specialty.fixed_frame',
  'norman.shutter.specialty.hang_strip',
  'norman.shutter.specialty.hub',
  'norman.shutter.specialty.arch_style',
  'norman.shutter.specialty.continuous_arch',
  'norman.shutter.specialty.continuous_stile',
  'norman.shutter.specialty.panel_count',
  'norman.shutter.specialty.frame_sides',
  'norman.shutter.specialty.sunburst_divider',
  'norman.shutter.specialty.horizontal_section',
  'norman.shutter.specialty.horizontal_divider',
  'norman.shutter.specialty.net_dimensions',
  'norman.shutter.specialty.round_net_range',
  'norman.shutter.specialty.geometry',

  'norman.san_clemente_honeycomb.dimensions', 'norman.san_clemente_honeycomb.tall_width',
  'norman.san_clemente_faux_wood.dimensions', 'norman.san_clemente_faux_wood.installation',
  'norman.san_clemente_faux_wood.side_mount', 'norman.san_clemente_faux_wood.side_width',
  'norman.contract.dimensions', 'norman.contract.wand_drop', 'norman.contract.return_size',
  // Roller guide p44 and September retail p20: standard/stainless chain have no extra charge.
  'roller.matrix.minWidth',
  'roller.matrix.maxWidth',
  'roller.matrix.minHeight',
  'roller.matrix.maxHeight',
  'roller.matrix.totalMaxAreaTwoShadesSqft',
  'roller.matrix.maxAreaEachShadeSqft',
  'roller.matrix.totalMaxAreaCoupledPairSqft',
  'roller.matrix.maxAreaSingleShadeSqft',
  'roller.chain.application',
  'roller.chain.record',
  'roller.chain.height',
  'roller.chain.custom_length',
  'roller.chain.minimum',
  'roller.chain.maximum',
  'roller.chain.stale_custom',
  'norman.wood_blinds.matching_count',
  'norman.wood_blinds.matching_single_lines',
  'norman.wood_blinds.matching_specifications',
  'norman.ultimate_faux.matching_count',
  'norman.ultimate_faux.matching_single_lines',
  'norman.ultimate_faux.matching_specifications',
  'roman.side_by_side.september.lift',
  'roman.side_by_side.september.mount',
  'roman.side_by_side.september.style',
  'roman.side_by_side.september.fabric',
  'roman.side_by_side.september.lining',
  'roman.side_by_side.september.cut',
  'roman.side_by_side.september.pattern',
  'roman.side_by_side.september.valance',
  'roman.side_by_side.september.returns',
  'roman.side_by_side.september.motor',
  'roman.side_by_side.september.power',
  'norman.smartfold.side_by_side_members',
  'norman.smartfold.side_by_side_mount',
  'norman.smartfold.side_by_side_fabric',
  'norman.smartfold.side_by_side_lift',
  'norman.smartfold.side_by_side_fold',
  'norman.smartfold.side_by_side_motor',
  'norman.smartfold.side_by_side_power',
  'norman.smartfold.side_by_side_valance',
  'norman.smartfold.side_by_side_returns',
  'norman.smartfold.side_by_side_returnSize',
  // Selected motor/tube capacity is manufacturing evidence; retail still needs a real grid cell.
  'roller.matrix.maxAreaSqft',
  'roman.hardware.mount_fit', 'roman.hardware.mount_depth',
  'roman.continuous_loop.headrail_required',
  'roman.hardware.chain_clearance', 'roman.hardware.chain_obstruction_choice',
  'norman.perfectsheer.chain_clearance', 'roller.valance_only.control_clearance',
  'roller.chain.device_clearance', 'roller.chain.obstruction', 'roller.chain.safety_device',
  'roller.accessories.magnet_left', 'roller.accessories.magnet_right', 'roller.accessories.magnet_bottom',
  'honeycomb.mounting.fit', 'honeycomb.mounting.source_scope',
  'honeycomb.mounting.unavailable', 'honeycomb.mounting.depth_required',
  'honeycomb.mounting.depth',
  'honeycomb.charging_clearance.recess', 'honeycomb.charging_clearance.opening_height',
  'honeycomb.charging_clearance.obstruction', 'honeycomb.charging_clearance.ac_required',
  'norman.smartdrape.ceiling_attachment', 'norman.smartdrape.stale_ceiling_attachment',
  'norman.smartdrape.stale_pocket', 'norman.smartdrape.replacement.original_work_order',
  'norman.smartfold.side_by_side_room', 'norman.perfectsheer.side_by_side_room',
  'roman.side_by_side.september.room',
  'norman.shutter.bifold90.flat_surface', 'norman.shutter.bifold180.flat_surface',
  'norman.smartfold.outside_clearance_required',
  'norman.smartfold.outside_mounting_area', 'norman.smartfold.outside_mounting_space',
  'norman.smartfold.inside_fascia_fit', 'norman.smartfold.inside_fascia_route',
  'norman.smartfold.inside_fascia_depth_required', 'norman.smartfold.inside_fascia_depth',
  'norman.smartfold.inside_light_guard_fit', 'norman.smartfold.inside_light_guard_route',
  'norman.smartfold.inside_light_guard_depth_required', 'norman.smartfold.inside_light_guard_depth',
  'roman.fabric.orientation_ack_required', 'roman.side_by_side.match_required',
  'onyx.source.current_effective_revision_missing',
  'onyx.program.not_in_binder',
  'onyx.required.frame_extension_inches',
  'onyx.non_vinyl.rules_not_normalized',
  'onyx.us_made_vinyl.restriction_identity_unverified',
  'onyx.hinge.assortment_source_incomplete',
  'onyx.panel.maximum_area_source_incomplete',
  'onyx.panel.widths.required', 'onyx.panel.heights.required',
  'onyx.required.available_depth_inches',
  'onyx.required.opening_diagonal_difference_inches',
  'onyx.tilt.hidden.section_lengths_required',
  'onyx.t_post.positions_required',
  'onyx.divider_rail.custom_positions',
  'onyx.divider_rail.location_mode',
  'onyx.divider_rail.minimum_required',
  'onyx.french_door.flat_area.minimum',
  'onyx.french_door.hardware_centers_required',
  'onyx.french_door.hardware_clearance_required',
]);

export function isOrderingOnlyIssue(issue: ValidationIssue): boolean {
  // Without purchased shims, this attachment changes only included mounting hardware.
  const unpricedVerticalAttachment = issue.ruleId === 'honeycomb.vertical.mounting' &&
    Number(issue.selectedValues?.vertical_shim_layers ?? 0) === 0;
  return unpricedVerticalAttachment || ORDER_ONLY_RULES.has(issue.ruleId) || isNonNormanOrderingOnlyRule(issue.ruleId) ||
    // Source dimension profiles express manufacturing capacity; grid lookup still enforces actual cells.
    /^(?:honeycomb\.matrix\.(?:[a-z0-9_-]+\.)*|(?:honeycomb|roman|smartfold|perfectsheer)\.motorization\.dimension\.[a-z0-9_.-]+\.)(?:min_width|max_width|min_height|max_height|max_area|min_area)(?:\.rear)?$/.test(issue.ruleId) ||
    /^(?:honeycomb|roman|smartfold|perfectsheer)\.motorization\.motor_position_(?:required|invalid)$/.test(issue.ruleId) ||
    /(?:^|[._])(?:mount_depth|mounting_depth|recess_depth|available_depth|mount_fit|opening_diagonal_difference|out_of_square|minimum_depth|flush_depth|mounting_clearance|inside_clearance)(?:[._]|$)/.test(issue.ruleId) ||
    /^norman\.(?:smartfold|perfectsheer|roman)\.magnet_(?:left|right|bottom)_clearance_inches$/.test(issue.ruleId) ||
    issue.ruleId.startsWith('onyx.depth.') ||
    issue.ruleId === 'onyx.mount.inside.out_of_square';
}

/** Preserve order evidence for staff without making it a prerequisite for a quote price. */
export function quotePricingValidationIssues(issues: readonly ValidationIssue[]): ValidationIssue[] {
  return issues.map(issue => issue.severity === 'hard_block' && isOrderingOnlyIssue(issue)
    ? { ...issue, severity: 'warning', explanation: `Before ordering: ${issue.explanation}` }
    : issue);
}
