#!/usr/bin/env python3
"""Normalize the pinned Norman workbook without changing its ordering identities."""
import argparse
import hashlib
import json
from pathlib import Path

EXPECTED_SHA = "8c0adc07c0adcad07368dc4f715c497bf17f54e558edbcb6220a9206a8461b62"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("workbook", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    if hashlib.sha256(args.workbook.read_bytes()).hexdigest() != EXPECTED_SHA:
        raise SystemExit("Refusing unexpected PerfectSheer workbook bytes")
    from openpyxl import load_workbook
    workbook = load_workbook(args.workbook, read_only=True, data_only=True)
    clean = lambda value: " ".join(str(value or "").split())
    factory = {}
    for number, row in enumerate(workbook["Fabric Color List-PerfectSheer"].values, 1):
        if number < 3:
            continue
        factory[clean(row[2])] = (number, *map(clean, row[1:7]))
    rows = []
    for number, row in enumerate(workbook["PerfectSheer"].values, 1):
        if not 7 <= number <= 37:
            continue
        opacity, fabric, code, name, hardware, end_caps, cord, tension, ac, battery, dc = map(clean, row[:11])
        frow, customer_fabric, customer_color, customer_name, factory_fabric, factory_color, factory_name = factory[code]
        assert (fabric, code, name) == (customer_fabric, customer_color, customer_name)
        rows.append(dict(customerFabricCode=fabric, customerColorCode=code, colorName=name,
                         opacity=opacity, factoryFabricCode=factory_fabric, factoryColorCode=factory_color,
                         factoryColorName=factory_name, hardware=hardware, endCapsAndClutch=end_caps,
                         cord=cord, tensionDevice=tension, acConnectorBox=ac, batteryBox=battery, dcBox=dc,
                         coordinationRange=f"A{number}:K{number}", factoryRange=f"A{frow}:G{frow}"))
    assert len(rows) == len(factory) == len({r["customerColorCode"] for r in rows}) == 31
    assert "F1364" not in factory
    args.output.write_text("// Generated by scripts/generate-norman-perfectsheer-coordination.py.\n"
                           "// Source: norman-ps-sd-coordination-2026-08-11. Customer and factory codes are distinct.\n"
                           "export const PERFECTSHEER_COORDINATION = " + json.dumps(rows, indent=2) + " as const;\n")


if __name__ == "__main__":
    main()
