"""Generate the Fall additions' exact September appendix profiles; preserve prior offerings."""
import argparse
import hashlib
import importlib.util
import json
from datetime import date
from pathlib import Path
from openpyxl import load_workbook

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('workbook', type=Path)
args = parser.parse_args()
assert hashlib.sha256(args.workbook.read_bytes()).hexdigest() == '754e924e4b3c4429b5452e3de0d0ed330d7b2a376613783c9659766f61a04629'
repo = Path(__file__).resolve().parents[1]
release = json.loads((repo / 'src/lib/quote/catalog/norman-roller-fall-2026.json').read_text())
spec = importlib.util.spec_from_file_location('roller_parser', Path(__file__).with_name('generate-norman-roller-v2-source.py'))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.INGESTION_AS_OF = date(2026, 9, 12)
full = module.build_data(load_workbook(args.workbook, data_only=True), args.workbook, args.workbook)
# The 14 PG4 colors already have a published supplement; retain it untouched.
colors = {row['colorCode']: row for row in release['colors'] if row['priceGroup'] != 4}
offerings = [row for row in full['offerings'] if row['colorCode'] in colors]
assert len(offerings) == len(colors) == 76
for row in offerings:
    expected = colors[row['colorCode']]
    assert row['collection'] == expected['collection'] and row['colorName'] == expected['colorName']
    assert row['regionScope'] == 'all_regions'
codes = {row['fabricCode'] for row in offerings}
rows = [row for row in full['limitRows'] if codes.intersection(row['fabricCodes'])]
assert {row['sheet'] for row in rows} == set(module.LIMIT_SHEETS)
row_ids = {row['id'] for row in rows}
assignments = [row for row in full['profileAssignments'] if row['limitRowId'] in row_ids]
profile_ids = {row['profileId'] for row in assignments}
result = {key: full[key] for key in ['metadata', 'profileDefinitions']}
result.update(offerings=offerings, limitRows=rows, profileAssignments=assignments,
              limitProfiles=[row for row in full['limitProfiles'] if row['id'] in profile_ids])
output = repo / 'src/lib/quote-v2/generated/norman-roller-fall-2026.generated.ts'
content = '// Generated by scripts/generate-norman-roller-fall-2026-matrix.py.\n'
content += 'import type { NormanRollerV2Source } from "./norman-roller-v2.generated";\n'
fields = []
for key, value in result.items():
    if not isinstance(value, list):
        fields.append(key + ':' + json.dumps(value, separators=(',', ':')))
        continue
    names = []
    for offset in range(0, len(value), 100):
        name = key + str(offset // 100)
        names.append('...' + name)
        content += f'const {name}: NormanRollerV2Source["{key}"] = ' + json.dumps(value[offset:offset+100], separators=(',', ':')) + ';\n'
    fields.append(key + ':[' + ','.join(names) + ']')
content += 'export const normanRollerFall2026Source: Pick<NormanRollerV2Source, "metadata" | "profileDefinitions" | "offerings" | "limitRows" | "profileAssignments" | "limitProfiles"> = {' + ','.join(fields) + '};\n'
output.write_text(content)
print(json.dumps({key: len(value) for key, value in result.items() if isinstance(value, list)}))
