#!/usr/bin/env python3
"""Normalize SmartDrape ordering identities and component coordination from the pinned workbook."""
import argparse
import hashlib
import json
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("workbook", type=Path)
parser.add_argument("output", type=Path)
args = parser.parse_args()
assert hashlib.sha256(args.workbook.read_bytes()).hexdigest() == "8c0adc07c0adcad07368dc4f715c497bf17f54e558edbcb6220a9206a8461b62"
from openpyxl import load_workbook
book = load_workbook(args.workbook, data_only=True)

def value(sheet, row, col):
    cell = sheet.cell(row, col)
    for merged in sheet.merged_cells.ranges:
        if cell.coordinate in merged:
            cell = sheet.cell(merged.min_row, merged.min_col)
            break
    return " ".join(str(cell.value or "").split())

factory = book["Fabric Color List-SmartDrape"]
coord = book["SmartDrape"]
factories = {value(factory, r, 4): r for r in range(3, 80)}
rows, hardware = [], {}
for r in range(8, 86):
    v = [value(coord, r, c) for c in range(1, 18)]
    components = dict(zip(["finish", "headrail", "aluminumShim", "smartJoint", "endCap", "carrier", "motor", "gearBoxBatteryPackWandBase"], [v[i] for i in [6, 7, 8, 9, 10, 11, 14, 15]]))
    if v[5] in hardware:
        assert hardware[v[5]] == components
    hardware[v[5]] = components
    if r == 85:
        continue
    fr = factories[v[3]]
    f = [value(factory, fr, c) for c in range(1, 9)]
    assert v[2:5] == f[2:5]
    rows.append(dict(customerFabricCode=v[2], customerColorCode=v[3], colorName=v[4],
                     category=v[0], pattern=v[1], factoryFabricCode=f[5] or None,
                     factoryColorCode=f[6] or None, factoryColorName=f[7] or None,
                     defaultHeadrail=v[5], fabricClip=v[12], wand=v[13], chargingWand=v[16],
                     coordinationRange=f"A{r}:Q{r}", factoryRange=f"A{fr}:H{fr}"))
assert len(rows) == len(factories) == len({r["customerColorCode"] for r in rows}) == 77
assert [r["customerColorCode"] for r in rows if r["factoryColorCode"] is None] == ["F2128", "F2129", "F2130"]
args.output.write_text("// Generated by scripts/generate-norman-smartdrape-coordination.py.\n"
                       "// Source: norman-ps-sd-coordination-2026-08-11. Blank factory aliases remain null.\n"
                       "export const SMARTDRAPE_COORDINATION = " + json.dumps(rows, indent=2) + " as const;\n"
                       "export const SMARTDRAPE_HARDWARE = " + json.dumps(hardware, indent=2) + " as const;\n")
