#!/usr/bin/env python3
"""Generate the V2 Honeycomb color/restriction source from Norman's workbook.

The workbook remains the authoritative artifact.  This script intentionally
emits a deterministic TypeScript data file so production pricing does not need
Excel parsing or network access.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

EXPECTED_WORKBOOK_SHA256 = "56676b753c0255618439c77cf837ee93de579b555fe0bee33dada1e0f9b521e4"

CELL_COLUMNS = {
    6: '3/8" Single Cell',
    7: '9/16" Single Cell',
    8: '1/2" Double Cell',
    9: '3/4" Single Cell',
    10: '3/4" Double Cell',
    11: '1 1/4" Single Cell',
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def clean(value: object) -> str:
    if value is None:
        return ""
    return " ".join(str(value).replace("\u3000", " ").split())


def marked(value: object) -> bool:
    return clean(value) in {"√", "Y", "Yes", "yes", "1", "True"}


def fabric_rows(workbook) -> tuple[list[dict], list[dict]]:
    sheet = workbook["Fabric List"]
    active: list[dict] = []
    discontinued: list[dict] = []
    for row in range(7, sheet.max_row + 1):
        factory_code = clean(sheet.cell(row, 3).value).upper()
        customer_code = clean(sheet.cell(row, 4).value).upper()
        if not factory_code or not customer_code:
            continue
        record = {
            "family": clean(sheet.cell(row, 2).value),
            "factoryColorCode": factory_code,
            "customerColorCode": customer_code,
            "colorName": clean(sheet.cell(row, 5).value),
            "cellSizes": [
                label for column, label in CELL_COLUMNS.items() if marked(sheet.cell(row, column).value)
            ],
            "note": clean(sheet.cell(row, 12).value),
        }
        if isinstance(sheet.cell(row, 1).value, (int, float)) and int(sheet.cell(row, 1).value) <= 191:
            active.append(record)
        elif "discontinu" in record["note"].lower() or row >= 198:
            discontinued.append(record)
    return active, discontinued


def application_rows(workbook, sheet_name: str, start_row: int) -> list[dict]:
    sheet = workbook[sheet_name]
    rows: list[dict] = []
    for row in range(start_row, sheet.max_row + 1):
        number = sheet.cell(row, 1).value
        factory_code = clean(sheet.cell(row, 3).value).upper()
        if not isinstance(number, (int, float)) or not factory_code:
            continue
        rows.append(
            {
                "family": clean(sheet.cell(row, 2).value),
                "factoryColorCode": factory_code,
                "customerColorCode": clean(sheet.cell(row, 4).value).upper(),
                "colorName": clean(sheet.cell(row, 5).value),
                "availableCells": [
                    clean(sheet.cell(5 if sheet_name.startswith("Vertical") else 9, column).value)
                    for column in (6, 7)
                    if marked(sheet.cell(row, column).value)
                ],
                "coordination": {
                    "rail": clean(sheet.cell(row, 8).value),
                    "endCap": clean(sheet.cell(row, 9).value),
                    "cord": clean(sheet.cell(row, 10).value),
                    "bracket": clean(sheet.cell(row, 11).value),
                    "dustCover": clean(sheet.cell(row, 12).value),
                },
            }
        )
    return rows


def emit(output: Path, source: Path, digest: str, data: dict) -> None:
    payload = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True)
    content = (
        "// Generated by scripts/generate-norman-honeycomb-v2-source.py. Do not edit.\n"
        f"// Source: {source.name}; SHA-256: {digest}\n\n"
        f"export const NORMAN_HONEYCOMB_WORKBOOK_SHA256 = {json.dumps(digest)} as const;\n"
        f"export const normanHoneycombV2Source = {payload} as const;\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("workbook", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    digest = sha256(args.workbook)
    if digest != EXPECTED_WORKBOOK_SHA256:
        raise SystemExit(
            "Refusing unexpected Honeycomb workbook bytes: "
            f"expected SHA-256 {EXPECTED_WORKBOOK_SHA256}, found {digest}"
        )

    # Import the workbook parser only after source identity is accepted. This
    # keeps the hash guard independently testable and ensures unknown bytes are
    # never handed to a parser.
    from openpyxl import load_workbook

    workbook = load_workbook(args.workbook, data_only=True, read_only=True)
    active, discontinued = fabric_rows(workbook)
    data = {
        "revision": "2026-07-01",
        "activeColors": active,
        "discontinuedColors": discontinued,
        "verticalColors": application_rows(workbook, "Vertical(6 Rail Colors)", 9),
        "motorizedSkylightColors": application_rows(workbook, "MotorizedSkylight(4 RailColors)", 12),
    }
    if len(active) != 191:
        raise SystemExit(f"Expected 191 active colors, found {len(active)}")
    if len(data["verticalColors"]) != 142:
        raise SystemExit(f"Expected 142 vertical colors, found {len(data['verticalColors'])}")
    if len(data["motorizedSkylightColors"]) != 134:
        raise SystemExit(
            f"Expected 134 motorized-skylight colors, found {len(data['motorizedSkylightColors'])}"
        )
    emit(args.output, args.workbook, digest, data)


if __name__ == "__main__":
    main()
