-- Generated by scripts/generate-quote-v2-wholesale-phase1-seed.mjs.
-- Phase 1 evidence inventory only. No wholesale version is published here.
-- Quote-time lookup remains fail-closed until exact current-account evidence
-- is reviewed and a separate explicit publication changes lifecycle.

insert into public.sales_quote_v2_manufacturers (name, code)
values ('Lotus', 'lotus'), ('Norman', 'norman')
on conflict (code) do update set name = excluded.name;

insert into public.sales_quote_v2_wholesale_sources (
  source_key,
  manufacturer_code,
  source_type,
  file_name,
  title,
  revision,
  effective_from,
  received_on,
  sha256,
  authorities,
  runtime_authority,
  account_key,
  account_scope,
  product_keys,
  program_keys,
  product_scope,
  provenance,
  quarantine_reason
)
values
(
  'lotus-west-a26-v1',
  'lotus',
  'price_book',
  'Lotus.pdf',
  'Cost Book & Supplier Manual',
  'West A26.v1',
  null::date,
  '2026-07-20'::date,
  '4e9aba91a601e1212a3e8a1531c361caf033c28ef6ca1fdac3ad6247502a982f',
  array['dealer_cost','restrictions','options','freight','other_cost']::text[],
  false,
  null,
  'Manufacturer West-region dealer cost book',
  array['lotus_faux_wood_blinds']::text[],
  array['lotus_flx_2in_bright_white_custom']::text[],
  '{"products":["lotus_faux_wood_blinds"]}'::jsonb,
  '{"modifiedDate":"2026-04-01","pageCount":113,"effectiveDateEvidence":"No effective date stated in the supplied document"}'::jsonb,
  'The supplied dealer cost book states no effective date; normalized cells remain review evidence until current applicability is established.'
),
(
  'lotus-three-product-cart-2026-07-22',
  'lotus',
  'dealer_portal_snapshot',
  'lotus-three-product-cart-2026-07-22.md',
  'Current 805 Lotus three-product cart evidence receipt',
  'Read-only dealer cart observed 2026-07-22',
  null::date,
  '2026-07-22'::date,
  '01c9f02fd4c40ff93daa10c7021207f16081c2ef4de90f9c04f2eb4771c9be28',
  array['dealer_cost_observation']::text[],
  false,
  '805',
  'Current authenticated 805 Lotus dealer account',
  array['lotus_faux_wood_blinds']::text[],
  array['lotus_fcx_2in_soft_white_custom']::text[],
  '{"observedPrograms":["lotus_amx_1in_aluminum_custom","lotus_fcx_2in_soft_white_custom","lotus_vs_steel_complete_stock"]}'::jsonb,
  '{"captureMode":"read_only_unsubmitted_cart","customerDataRetained":false}'::jsonb,
  'The observed Soft White faux-wood cart price conflicts with the cost book and does not verify the requested Smooth Bright White program.'
),
(
  'norman-retail-guide-2026-07',
  'norman',
  'price_book',
  '2026Jul Retail Price Guide (1).pdf',
  '2026 Retail Guide',
  '2026-07',
  '2026-07-01'::date,
  '2026-07-20'::date,
  'ae102c19b833e5c20070c11ecaad61d68a79bf6b52b5402fad55415e2602d2f3',
  array['retail_pricing','options','freight']::text[],
  false,
  null,
  'Manufacturer retail guide',
  array['smartprivacy_faux','faux_wood']::text[],
  array['smartprivacy_faux_2in_and_2_1_2in_slats_cordless','faux_wood_2in_and_2_1_2in_slats_cordless']::text[],
  '{"products":["smartprivacy_faux","faux_wood"],"pages":[30,31]}'::jsonb,
  '{"effectiveDateEvidence":"Cover: Effective July 1st, 2026","pageCount":40}'::jsonb,
  'This source is authoritative for list pricing and options, not the current 805 dealer wholesale factor.'
),
(
  'norman-dealer-pricing-snapshot-2026-07-20',
  'norman',
  'dealer_portal_snapshot',
  'NORMAN PRICING.pdf',
  'Product Pricing (other dealer account)',
  'Other-dealer portal print dated 2026-07-20',
  null::date,
  '2026-07-20'::date,
  'fdf0af921d137d778d6890b7afa97342045bd50d05a4838afc116b6c400f3044',
  array['dealer_factor_observation','freight_observation']::text[],
  false,
  'other_dealer',
  'Other Norman dealer account, not the current 805 account',
  array['smartprivacy_faux','faux_wood']::text[],
  array['smartprivacy_faux_2in_and_2_1_2in_slats_cordless','faux_wood_2in_and_2_1_2in_slats_cordless']::text[],
  '{"products":["smartprivacy_faux","faux_wood"],"observedStandardFactor":0.3}'::jsonb,
  '{"captureDate":"2026-07-20","customerIdRedacted":true}'::jsonb,
  'The source belongs to a different dealer account and cannot authorize current 805 wholesale cost.'
),
(
  'norman-805-live-roller-portal-2026-07-21',
  'norman',
  'dealer_portal_snapshot',
  'Norman Roller Current Portal 2026-07-22.redacted.png',
  'Current 805 Norman Roller dealer-cost fixture',
  'Read-only unsubmitted Roller draft observed 2026-07-21',
  '2026-07-21'::date,
  '2026-07-22'::date,
  '34f7e0bb5703d8248549ec795e198208237d316a344b884199881d73c8a26869',
  array['dealer_cost','freight','processing']::text[],
  true,
  '805',
  'Current authenticated 805 Norman dealer account',
  array['roller']::text[],
  array['roller_cordless_fabric_price_group_1_pg1']::text[],
  '{"products":["roller"],"standardFactor":0.33,"slowerScheduleFactor":0.297}'::jsonb,
  '{"captureMode":"read_only_unsubmitted_draft","accountIdRedacted":true}'::jsonb,
  null
)
on conflict (source_key) do update set
  manufacturer_code = excluded.manufacturer_code,
  source_type = excluded.source_type,
  file_name = excluded.file_name,
  title = excluded.title,
  revision = excluded.revision,
  effective_from = excluded.effective_from,
  received_on = excluded.received_on,
  sha256 = excluded.sha256,
  authorities = excluded.authorities,
  runtime_authority = excluded.runtime_authority,
  account_key = excluded.account_key,
  account_scope = excluded.account_scope,
  product_keys = excluded.product_keys,
  program_keys = excluded.program_keys,
  product_scope = excluded.product_scope,
  provenance = excluded.provenance,
  quarantine_reason = excluded.quarantine_reason;

insert into public.sales_quote_v2_wholesale_versions (
  manufacturer_id,
  version_key,
  scope_key,
  lifecycle,
  effective_from,
  account_key,
  account_scope,
  coverage,
  content_sha256,
  review_notes
)
select
  manufacturers.id,
  'lotus-west-a26-v1-phase1-faux-wood',
  'lotus_faux_wood_blinds',
  'review',
  null,
  '805',
  'Current 805 quoting account',
  '{"phase":1,"product":"Lotus standard 2-inch faux wood","programKey":"lotus_flx_2in_bright_white_custom","styleKey":"smooth","colorKey":"bright_white","pricedCells":111,"blockedCells":8}'::jsonb,
  '6899db290ad2c0f1feadefc6639070dafe54825ea377cad4523ecbc024b61100',
  'Dealer-net matrix is documented. Publication is blocked by the absent source effective date, unresolved portal/book conflict on another faux-wood program, and the need to bind the requested generic white label to an exact program/color.'
from public.sales_quote_v2_manufacturers manufacturers
where manufacturers.code = 'lotus'
on conflict (manufacturer_id, account_key, scope_key, version_key) do update set
  lifecycle = excluded.lifecycle,
  effective_from = excluded.effective_from,
  account_key = excluded.account_key,
  account_scope = excluded.account_scope,
  coverage = excluded.coverage,
  content_sha256 = excluded.content_sha256,
  review_notes = excluded.review_notes,
  updated_at = now();

insert into public.sales_quote_v2_wholesale_versions (
  manufacturer_id,
  version_key,
  scope_key,
  lifecycle,
  effective_from,
  account_key,
  account_scope,
  coverage,
  content_sha256,
  review_notes
)
select
  manufacturers.id,
  'norman-805-faux-wood-phase1',
  'faux_wood_blinds',
  'draft',
  null,
  '805',
  'Current 805 Norman dealer account',
  '{"phase":1,"products":["Norman SmartPrivacy 2-inch Pure White","Norman Premium/Ultimate 2-inch Pure White"]}'::jsonb,
  '9e463daf30f328babde0362511cf38f2cf9be8aae14514d147810bb826be5fcc',
  'Current list grids and color identity exist. No exact current-805 dealer-cost fixture covers SmartPrivacy or Ultimate faux wood; the other-account .3000 factor is quarantined and the current .330/.297 fixture is Roller-only.'
from public.sales_quote_v2_manufacturers manufacturers
where manufacturers.code = 'norman'
on conflict (manufacturer_id, account_key, scope_key, version_key) do update set
  lifecycle = excluded.lifecycle,
  effective_from = excluded.effective_from,
  account_key = excluded.account_key,
  account_scope = excluded.account_scope,
  coverage = excluded.coverage,
  content_sha256 = excluded.content_sha256,
  review_notes = excluded.review_notes,
  updated_at = now();

insert into public.sales_quote_v2_wholesale_version_sources (
  wholesale_version_id,
  source_id,
  authority_scope,
  source_priority
)
select versions.id, sources.id, mapping.authority_scope, mapping.source_priority
from (
  values
    ('lotus-west-a26-v1-phase1-faux-wood', 'lotus-west-a26-v1',
      array['dealer_cost','options','freight','other_cost']::text[], 10),
    ('lotus-west-a26-v1-phase1-faux-wood',
      'lotus-three-product-cart-2026-07-22',
      array['conflict_observation']::text[], 20),
    ('norman-805-faux-wood-phase1', 'norman-retail-guide-2026-07',
      array['retail_grid','options']::text[], 10),
    ('norman-805-faux-wood-phase1',
      'norman-dealer-pricing-snapshot-2026-07-20',
      array['quarantined_other_account_factor']::text[], 20),
    ('norman-805-faux-wood-phase1',
      'norman-805-live-roller-portal-2026-07-21',
      array['roller_only_current_account_factor','freight']::text[], 30)
) as mapping(version_key, source_key, authority_scope, source_priority)
join public.sales_quote_v2_wholesale_versions versions
  on versions.version_key = mapping.version_key
join public.sales_quote_v2_wholesale_sources sources
  on sources.source_key = mapping.source_key
on conflict (wholesale_version_id, source_id) do update set
  authority_scope = excluded.authority_scope,
  source_priority = excluded.source_priority;

with version as (
  select versions.id
    from public.sales_quote_v2_wholesale_versions versions
    join public.sales_quote_v2_manufacturers manufacturers
      on manufacturers.id = versions.manufacturer_id
   where manufacturers.code = 'lotus'
     and versions.version_key = 'lotus-west-a26-v1-phase1-faux-wood'
), source as (
  select id
    from public.sales_quote_v2_wholesale_sources
   where source_key = 'lotus-west-a26-v1'
)
insert into public.sales_quote_v2_wholesale_programs (
  wholesale_version_id,
  manufacturer_code,
  product_key,
  program_key,
  style_key,
  color_key,
  display_name,
  cost_status,
  price_axis,
  max_width,
  max_height,
  configuration,
  option_schema,
  source_id,
  source_locator
)
select
  version.id,
  'lotus',
  'lotus_faux_wood_blinds',
  'lotus_flx_2in_bright_white_custom',
  'smooth',
  'bright_white',
  '2-inch Faux Wood, Smooth Bright White - Custom Cut',
  'documented_not_published',
  'width_height',
  95,
  96,
  '{"slatSize":"2","material":"faux_wood","finish":"smooth","color":"Bright White","dimensionRounding":"next_grid_cell"}'::jsonb,
  '{}'::jsonb,
  source.id,
  '{"page":99}'::jsonb
from version cross join source
on conflict (
  wholesale_version_id,
  product_key,
  program_key,
  style_key,
  color_key
) do update set
  display_name = excluded.display_name,
  cost_status = excluded.cost_status,
  price_axis = excluded.price_axis,
  max_width = excluded.max_width,
  max_height = excluded.max_height,
  configuration = excluded.configuration,
  option_schema = excluded.option_schema,
  source_id = excluded.source_id,
  source_locator = excluded.source_locator;

with program as (
  select programs.id
    from public.sales_quote_v2_wholesale_programs programs
    join public.sales_quote_v2_wholesale_versions versions
      on versions.id = programs.wholesale_version_id
   where versions.version_key = 'lotus-west-a26-v1-phase1-faux-wood'
     and programs.program_key = 'lotus_flx_2in_bright_white_custom'
), source as (
  select id
    from public.sales_quote_v2_wholesale_sources
   where source_key = 'lotus-west-a26-v1'
)
insert into public.sales_quote_v2_wholesale_price_cells (
  program_id,
  width_ceiling,
  height_ceiling,
  availability,
  cost_cents,
  currency,
  sku_codes,
  source_id,
  source_locator,
  cell_fingerprint
)
select
  program.id,
  generated.width_ceiling,
  generated.height_ceiling,
  generated.availability,
  generated.cost_cents,
  generated.currency,
  generated.sku_codes,
  source.id,
  generated.source_locator,
  generated.cell_fingerprint
from program
cross join source
cross join (
  values
(
  17,
  36,
  'priced',
  2357,
  'USD',
  array['CFLX1736BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '6c1127d96ad1d11b6fa136935d99433afd8176cd6cfe95257038f99b96ed862d'
),
(
  23,
  36,
  'priced',
  2693,
  'USD',
  array['CFLX2336BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'b4c2524ad014929875006ca830b187620db741faf392a774f2d52b2b7021bb18'
),
(
  27,
  36,
  'priced',
  3039,
  'USD',
  array['CFLX2736BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'cb95fe8a38dd37094f42a0f77ca0d3247a20dd7edaae739eb0f1c467738c6a53'
),
(
  30,
  36,
  'priced',
  3299,
  'USD',
  array['CFLX3036BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '88bf937b381987c51be774ebf24aaeed2cbcd58a7a216ef68c65bf45f2bed5ea'
),
(
  35,
  36,
  'priced',
  2937,
  'USD',
  array['CFLX3536BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '333592a594d71bbc106d2581da4ead893fc85a0e8d5bb3d9d1bdb9a6716d5186'
),
(
  39,
  36,
  'priced',
  3192,
  'USD',
  array['CFLX3936BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '00cb3b6bee76e217407c17fa9532ce33b9c134ed950fdff4094c5ece7fb1bd83'
),
(
  43,
  36,
  'priced',
  3447,
  'USD',
  array['CFLX4336BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '5cc00768bd5d6aace5af825862e62ce17ad3267526f22ce42f5ec08fa106939c'
),
(
  48,
  36,
  'priced',
  3767,
  'USD',
  array['CFLX4836BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '1fb35eec96f2a342d61d6e107e66bfc298faa3b1ce832bd3f2556e686cd5eed4'
),
(
  54,
  36,
  'priced',
  4150,
  'USD',
  array['CFLX5436BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'd7f25bf216a1acf417a66cf1e4f10bbd78feb0844f3e50d820c9d59cf2f52fdf'
),
(
  59,
  36,
  'priced',
  4469,
  'USD',
  array['CFLX5936BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '09ad9feb2ccb5312aaccbcdf93abd5886382e0829a8527e54112d58f0efc4b56'
),
(
  63,
  36,
  'priced',
  4725,
  'USD',
  array['CFLX6336BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'df2c3f52e40649cf2579f0feccb3a5caf72ff045478588e87b3fd37cc79e786b'
),
(
  69,
  36,
  'priced',
  5108,
  'USD',
  array['CFLX6936BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '673b8db68cea34f9dfd5029ff3e2dc8836113bc96e42a147a28780afebca3951'
),
(
  72,
  36,
  'priced',
  5300,
  'USD',
  array['CFLX7236BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '0cebc33c857bbecbf3c715113f876774722d9b3f3f5575c3af21737e3182e375'
),
(
  78,
  36,
  'priced',
  8746,
  'USD',
  array['CFLX7836BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '17299098ed2c60f412c7e431cb95ecf4f910c02afd15cf902e0dfd928aa3de31'
),
(
  82.5,
  36,
  'priced',
  9255,
  'USD',
  array['CFLX82536BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'f11a64f1f126caf7fb169e21ecf0126d108efa63fd59180bba4e8053d906fc7a'
),
(
  89,
  36,
  'priced',
  9866,
  'USD',
  array['CFLX8936BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '5da1fb6bbabe81e21c8a467513e67b12e4bbdb128cb0e82af1b0e11e85bcecf9'
),
(
  95,
  36,
  'priced',
  10478,
  'USD',
  array['CFLX9536BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '560b914b0e9cd02f13d49c88d3d40dc97ed2f7a40f999efd320701c81ae3cb4c'
),
(
  17,
  48,
  'priced',
  2664,
  'USD',
  array['CFLX1748BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '5fd94103596b843c5a71910d31dad37d0907983efbcde7593efc15760bd557ec'
),
(
  23,
  48,
  'priced',
  2660,
  'USD',
  array['CFLX2348BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '87ba12510d1f674ff16c4f241b03579f2c9e83c263b96a2c25b9be88292f0622'
),
(
  27,
  48,
  'priced',
  3001,
  'USD',
  array['CFLX2748BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'be65aa19f785560f720a2d119786a725c8e734c907d92aa93be6cadbfe1d66bf'
),
(
  30,
  48,
  'priced',
  2863,
  'USD',
  array['CFLX3048BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3f6f0b824833446df745f26ecd4ee6836239e488bdfff5eaf2c4c0e48267e698'
),
(
  35,
  48,
  'priced',
  3224,
  'USD',
  array['CFLX3548BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'c049f032f82809c0a3ef7a1a45a3799e2cd2b6896d183f07426f60db3cb3596c'
),
(
  39,
  48,
  'priced',
  3512,
  'USD',
  array['CFLX3948BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '6084511d1f3df9131a57bc8f4d8925558fa60aa066797d259cfb2e80f6a00110'
),
(
  43,
  48,
  'priced',
  3800,
  'USD',
  array['CFLX4348BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'a77265e8168862fb132c7856e55817bc78ff35153d869b34c97c0d835accedce'
),
(
  48,
  48,
  'priced',
  4161,
  'USD',
  array['CFLX4848BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'b6f44d5104d28b79e6b29fe360ec015f27cd7628f35157506b996425c0bead36'
),
(
  54,
  48,
  'priced',
  4593,
  'USD',
  array['CFLX5448BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'b032cb499ea409c505741b8e3a1dcf82da148d83ea1ad68953d88a5a934ddefb'
),
(
  59,
  48,
  'priced',
  4953,
  'USD',
  array['CFLX5948BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '0cc521571bc2ee0cc8d1b57b1d47db3223402c430c41571074e629d4d46d8e69'
),
(
  63,
  48,
  'priced',
  5242,
  'USD',
  array['CFLX6348BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'e73cd7ece3f9d38e1378c3ae32ae041c7dfeb558a14a6cad75ad5b656c92aa01'
),
(
  69,
  48,
  'priced',
  5675,
  'USD',
  array['CFLX6948BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'cb54a1098351b0ffc1128600f0747f342a3f85b6bd4716a6fb7ee85b29ef2f0b'
),
(
  72,
  48,
  'priced',
  5890,
  'USD',
  array['CFLX7248BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3ff615c57bedd9c7429005af97c119a211c8b217f922baf4cbfe5c2eca44932e'
),
(
  78,
  48,
  'priced',
  11394,
  'USD',
  array['CFLX7848BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'be94b934cb5bb638ec8f3256d45907893967ad97c45a920ef6509d2d582a25fe'
),
(
  82.5,
  48,
  'priced',
  12074,
  'USD',
  array['CFLX82548BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'f0c8088dc97124f0e295b401d742faa313acbaf8ed462f5e06b191024d6a33eb'
),
(
  89,
  48,
  'priced',
  12889,
  'USD',
  array['CFLX8948BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'b0ccb59770056fe6801649af59585af1efce737967391bb99b56016c75174765'
),
(
  95,
  48,
  'priced',
  13705,
  'USD',
  array['CFLX9548BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '2da70a8fc346e11ac8bb386b421f8cad42404bbab8aabadeade13129414ef76f'
),
(
  17,
  60,
  'priced',
  3155,
  'USD',
  array['CFLX1760BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '05737762e1335fdf3984e5a8faa19038cf3d590bd39d5f9bf6261db7f082a1c8'
),
(
  23,
  60,
  'priced',
  3149,
  'USD',
  array['CFLX2360BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'bbd5267f3659ee2591280eda9fa9881e3b5ed050a25187fdde8840d8e3b4ea29'
),
(
  27,
  60,
  'priced',
  2842,
  'USD',
  array['CFLX2760BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'f3334a60f4c9d586c57dd7bfc8fade93c36e8594870908749d10caa25aa76f95'
),
(
  30,
  60,
  'priced',
  3081,
  'USD',
  array['CFLX3060BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3a14757527bd19130bb65771068f57c43311e8a07e662969fa92c9f6bb662973'
),
(
  35,
  60,
  'priced',
  3477,
  'USD',
  array['CFLX3560BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'ae6a285629287d17e1d45f1d7b23d013c12b792dbd5756ba6d47c16506cf7ada'
),
(
  39,
  60,
  'priced',
  3795,
  'USD',
  array['CFLX3960BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '27a80a88ab57a9455324dd818438d76ab3781c88b3bfad6956094b0544127d4e'
),
(
  43,
  60,
  'priced',
  4112,
  'USD',
  array['CFLX4360BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'e242f8d9f5d99e54c23cc042a369d4a6a6e0d9452b9f503d3d3f0b7ceadd9ebc'
),
(
  48,
  60,
  'priced',
  4509,
  'USD',
  array['CFLX4860BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '65b75b562bc3d0be2684b1946935130d449f209da4d2ee56e61b90c67ad54c27'
),
(
  54,
  60,
  'priced',
  4985,
  'USD',
  array['CFLX5460BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '9db89bfb11624cd881251bd64d6530f8478a06e153f27efacea8c2193a8d89b6'
),
(
  59,
  60,
  'priced',
  5381,
  'USD',
  array['CFLX5960BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'cd52953a8bca844688009b38b09ca68515a2c8cf93c7e45c754e194bb59351f7'
),
(
  63,
  60,
  'priced',
  5699,
  'USD',
  array['CFLX6360BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '5d880fdb38bef017b3f0ab6a97412b2b2a81f67dbe597038ac2b6465b9152814'
),
(
  69,
  60,
  'priced',
  6175,
  'USD',
  array['CFLX6960BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'b29a276d161293ae779aceb8d4168c021d30102c2e4f2f7ee2a2d91c69cced7b'
),
(
  72,
  60,
  'priced',
  6413,
  'USD',
  array['CFLX7260BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'ae7bf250ef0e4adc9d91c2877717477b8bb0f8ccc8fb7846eb194dc55412d22e'
),
(
  78,
  60,
  'priced',
  12570,
  'USD',
  array['CFLX7860BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '2d7466bacad025ff9048eb77ac63ad895f4e4601e8d2b782091c0bf69c6b1535'
),
(
  82.5,
  60,
  'priced',
  13249,
  'USD',
  array['CFLX82560BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '2148072312c4499d0e8f464212c76c553875a8d10641e50f877a0262eaeca422'
),
(
  89,
  60,
  'priced',
  14228,
  'USD',
  array['CFLX8960BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '882029c1a625b0f57bf1d1e37ad6b4a52e28f8c1aad11e8dfa45e879f668ebac'
),
(
  95,
  60,
  'priced',
  15135,
  'USD',
  array['CFLX9560BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '21b6c4193f1990a074050ced1e79b6d4421a5f70a13339c4e26263b3f39d711b'
),
(
  17,
  64,
  'priced',
  3317,
  'USD',
  array['CFLX1764BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '0c70b46cdc0441e685c6451e7fa3c45cab9fa1f76b041d6b13cfe0b1bce86544'
),
(
  23,
  64,
  'priced',
  2646,
  'USD',
  array['CFLX2364BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '9a6e827b5b8c9e798acd9515c5c35c910eef32a2104c4e605053e12be22aec9d'
),
(
  27,
  64,
  'priced',
  2985,
  'USD',
  array['CFLX2764BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '7be81048d5d8d6e4cc2cff00ebd65832c3b98ca4c3e18e669c826e03d0279251'
),
(
  30,
  64,
  'priced',
  3239,
  'USD',
  array['CFLX3064BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'a248815b3d7199b9180c18d570a1bfa79b4b2ce415886978795099ac4d405230'
),
(
  35,
  64,
  'priced',
  3663,
  'USD',
  array['CFLX3564BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'acf9005e99238be7c7495a42ca70b6a11e101818b4b29ef8a60241b17588bfb3'
),
(
  39,
  64,
  'priced',
  4000,
  'USD',
  array['CFLX3964BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'e6c59582ee8b2fc05a78b204cae007b700576a19767e9b3383fa825250560b89'
),
(
  43,
  64,
  'priced',
  4339,
  'USD',
  array['CFLX4364BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '521fc34a5cbb77443dd0fa4bfd74bbfca13d4306b604995c5c1c7e24ced1d0dc'
),
(
  48,
  64,
  'priced',
  4762,
  'USD',
  array['CFLX4864BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '456e691af9ef6c29e181d046bd82dcdae7c7b4f4d66177509fc44519a38359a7'
),
(
  54,
  64,
  'priced',
  5270,
  'USD',
  array['CFLX5464BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '29fbab6ac57d3f7ca05270ac46c30ae920c6642528c98185fd36cfbbd2ca2737'
),
(
  59,
  64,
  'priced',
  5693,
  'USD',
  array['CFLX5964BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '75d53b3fc1b66b128d57478423f18a9a9d21f1866e69cc902823fec7dae91328'
),
(
  63,
  64,
  'priced',
  6032,
  'USD',
  array['CFLX6364BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '00755da0423e0b05e93d8b8d4590b6b9370083e3af9dd63ec221073f74d6f8d5'
),
(
  69,
  64,
  'priced',
  6540,
  'USD',
  array['CFLX6964BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'a4cd5893cdba95313534fe04e9fcb34c6bdc985ffd167f2771009ff34d785a9b'
),
(
  72,
  64,
  'priced',
  6793,
  'USD',
  array['CFLX7264BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'aca50cdc2f7b0a4481498815fa9540664573b16af82577d38a15222580148397'
),
(
  78,
  64,
  'priced',
  14924,
  'USD',
  array['CFLX7864BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '65d7bb863cbad34042690c17311abfdb42e4bdd45d6d52296d314471e6d333d3'
),
(
  82.5,
  64,
  'priced',
  15829,
  'USD',
  array['CFLX82564BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '6587692baddb96e5e0b98655ff8d3eb90fe48a86ded37b96d193c2da99bae22b'
),
(
  89,
  64,
  'priced',
  16915,
  'USD',
  array['CFLX8964BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '1956698268957d191c6f9136fc0c5fcb50960f3b57b0f24ec29f04b328fa5e23'
),
(
  95,
  64,
  'priced',
  18002,
  'USD',
  array['CFLX9564BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'ba33f318358ebc7ff6800baf17562e93ee849b9995534fef006fab42fb50bc3a'
),
(
  17,
  72,
  'priced',
  2873,
  'USD',
  array['CFLX1772BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '67621e95d1857d07ae73bd24e41f88e626f4c9ea9825b2818f4aec23e87f4546'
),
(
  23,
  72,
  'priced',
  2891,
  'USD',
  array['CFLX2372BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '976b77b35f9a134698bdb4a0813b867da5bf5b10305e1e1df05f75449747589e'
),
(
  27,
  72,
  'priced',
  3271,
  'USD',
  array['CFLX2772BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '86de459789ab14797fd880bd48b09d632d62ef5a8e2c87eeaa1405bbff9769d7'
),
(
  30,
  72,
  'priced',
  3557,
  'USD',
  array['CFLX3072BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '48de51d93fbb2ce680a1ff706e3fb6d2ed1bc4beff6cb2b1dba040f983496fd3'
),
(
  35,
  72,
  'priced',
  4032,
  'USD',
  array['CFLX3572BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'e6ee86944c28167b803098090dfbbbde7a55fac2d3e4627bb499dec7baff3d61'
),
(
  39,
  72,
  'priced',
  4413,
  'USD',
  array['CFLX3972BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'c27fa381e2c6da7cf948615a01f1fb3ef2e79d0baa3bbbd46927f04f63ea059e'
),
(
  43,
  72,
  'priced',
  4795,
  'USD',
  array['CFLX4372BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '6b7b222814e7097efbe104f7959484a3099e3050d0b8a1230fce457826a2be80'
),
(
  48,
  72,
  'priced',
  5270,
  'USD',
  array['CFLX4872BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '7593e2081a46b1004b3a29c0b03527ff99f31078c7430fd2ea66adfda629e078'
),
(
  54,
  72,
  'priced',
  5842,
  'USD',
  array['CFLX5472BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'f7b1d51e23f0900c673140d0715ea727dcf2e273e3fbea211e25947474af35ff'
),
(
  59,
  72,
  'priced',
  6317,
  'USD',
  array['CFLX5972BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '6b30ec2b07c93d24f145020aba9a0c27a529db7ca0605e4611d034e2434d18bc'
),
(
  63,
  72,
  'priced',
  6699,
  'USD',
  array['CFLX6372BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'c854bd6431b081e90d6281cb85aeac10ec2d53be0cff306c87415f2365dce80e'
),
(
  69,
  72,
  'priced',
  7270,
  'USD',
  array['CFLX6972BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '8e7e567ced32c8bb8b633d9fb4dc2e125f8b2c01e980949c3160e8dfe79f9c77'
),
(
  72,
  72,
  'priced',
  7556,
  'USD',
  array['CFLX7272BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'bfde502f6aed25742740016e28e2a5fcc0368991c6fa01b2f50853be6beb48f7'
),
(
  78,
  72,
  'priced',
  14924,
  'USD',
  array['CFLX7872BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '87693f023af750bc3ab88e8c847baaa76287672b8eac01cb851c173ee9ce81f3'
),
(
  82.5,
  72,
  'priced',
  15829,
  'USD',
  array['CFLX82572BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '619011bfe1984fcde8b724d93128590cb94000ab39630556b903fa711d1514e5'
),
(
  89,
  72,
  'priced',
  16915,
  'USD',
  array['CFLX8972BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'a25ba61d2734cec5364cabe4e973c5c983d52a598c3603edebf342f3fa4bba2d'
),
(
  95,
  72,
  'priced',
  18002,
  'USD',
  array['CFLX9572BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '61b6a8f719cb62aaa8c2716aa5834c1eef403ffa48624c55e5cdf368fb0a9e83'
),
(
  17,
  84,
  'priced',
  3235,
  'USD',
  array['CFLX1784BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '1e806fed7620fed7be78643f80deefe3739ce2ee08817ace1dc6b665c6ee31a7'
),
(
  23,
  84,
  'priced',
  3255,
  'USD',
  array['CFLX2384BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '9ba4818f5ce09b0426989b385924f464ab59564873e06e69a48f85b6264618d7'
),
(
  27,
  84,
  'priced',
  3699,
  'USD',
  array['CFLX2784BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'e5e3d8200dcb95859ab827c73370b728b1d97b1fc98c8e78539e48f00b6516be'
),
(
  30,
  84,
  'priced',
  4032,
  'USD',
  array['CFLX3084BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3fdd4619d5e1a5c3f4dc99c6bbc623216bd06b2c54a012b804550949bae55275'
),
(
  35,
  84,
  'priced',
  4588,
  'USD',
  array['CFLX3584BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '00433d3ae725af275b93a73dd3f5d109f42b72d1eb6e5919d60cd082166fec6a'
),
(
  39,
  84,
  'priced',
  5032,
  'USD',
  array['CFLX3984BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'bbf85a9e6f254ed152de82dd2b6d124e9487bb3be001e002684d2e65f7b39ed7'
),
(
  43,
  84,
  'priced',
  5477,
  'USD',
  array['CFLX4384BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '0d3a29f1e3c527cbb0beb782d5009f2fa7b87adf40844a725b145c55ee0f7450'
),
(
  48,
  84,
  'priced',
  6032,
  'USD',
  array['CFLX4884BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'dc09b76e808da04f7df3115ceebbd3bb1e1c80ed02e96a989278703d467e1886'
),
(
  54,
  84,
  'priced',
  6699,
  'USD',
  array['CFLX5484BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '0b99456ae9211216403b1dd9b3a5525853b7a14d363fbab4b3abb4ab4d6d572c'
),
(
  59,
  84,
  'priced',
  7254,
  'USD',
  array['CFLX5984BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '360ceb532bd598a62f86cb9d89148ae0b5c2844b8eb5980e9475e8e3646a8664'
),
(
  63,
  84,
  'priced',
  7698,
  'USD',
  array['CFLX6384BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'fd2a5c64b4c1b6ebcb82bfa44046482df6677e41bc6ce223ce70285101d63516'
),
(
  69,
  84,
  'priced',
  8364,
  'USD',
  array['CFLX6984BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '8655da2c19129e2b4d7e2eb5b5b19628e4eee7adaf896bb9d6bb509846967f6e'
),
(
  72,
  84,
  'priced',
  8697,
  'USD',
  array['CFLX7284BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '8f4f024e45bf9abcab3a56b38d7d4becba87244418ed78109d660cd2159971c9'
),
(
  78,
  84,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  'a8f2774cf4910cb806e7a08336a9d28f8dfe0010116c35b45988e9e5068ae1ca'
),
(
  82.5,
  84,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  '222aef7aeadcf3c3f3e0c52ec1099d1785af16d94cc75607a182eff6c1a9c727'
),
(
  89,
  84,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  'daaa4fac60545d078b6f22eb02406e8ab541944cc84bff9528220938a7bfac49'
),
(
  95,
  84,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  'ff942941e7b4a8eb9a3dfeb458ba2c1ee262b69f6c52f568f67f73781fa987a0'
),
(
  17,
  96,
  'priced',
  3150,
  'USD',
  array['CFLX1796BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3aeaf2b241af713a2b3ea07bde79f3f91392e545ab7ccf8345c58646b628bdeb'
),
(
  23,
  96,
  'priced',
  3620,
  'USD',
  array['CFLX2396BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3f6e8dd3db837f90e1b3d96bdbbfc7072b88d2886a2ca53905434cbd2bde7a30'
),
(
  27,
  96,
  'priced',
  4128,
  'USD',
  array['CFLX2796BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '2113ded1efef885eb8d028aca744754191b17f611f4df4c6ecd38c88c958e16f'
),
(
  30,
  96,
  'priced',
  5026,
  'USD',
  array['CFLX3096BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '5cb0d2f16b560b3416bcdbcf5da5b868169498a2422f71d2be58a99a652ed768'
),
(
  35,
  96,
  'priced',
  5143,
  'USD',
  array['CFLX3596BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'a133ddaf0689cfb0c941d7551c51205982f7853a7b06233142b58a833458de48'
),
(
  39,
  96,
  'priced',
  5652,
  'USD',
  array['CFLX3996BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'f6c64260b5d59947585c613b69a23e62d62aeac692315fefe268d5ab1487cfef'
),
(
  43,
  96,
  'priced',
  6160,
  'USD',
  array['CFLX4396BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '4be5c8b444ae515effe241dc48cce22a3dea4b56780f3ddfcfdbf636cda336ed'
),
(
  48,
  96,
  'priced',
  6793,
  'USD',
  array['CFLX4896BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '3ce3ab357aab00d464935075c12a105b1b3858c0f636c9ff5709b15e71da9b8c'
),
(
  54,
  96,
  'priced',
  7556,
  'USD',
  array['CFLX5496BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '889eb1845c13c0f7be6a5ced434ae720aedf8a41ef3a2bf5af7ac2f597d1969c'
),
(
  59,
  96,
  'priced',
  8189,
  'USD',
  array['CFLX5996BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '95fa75d6a5c7374193cfc754a2a84d813f41670f4578b8474a309a31ee0d646a'
),
(
  63,
  96,
  'priced',
  8697,
  'USD',
  array['CFLX6396BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'fdb778dd4743ca8128ba2f644a9908bbaaa4cae3c9eb4a891565d498163d5634'
),
(
  69,
  96,
  'priced',
  9460,
  'USD',
  array['CFLX6996BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  'fc50816be2763e1c84c03bb489535c32050257d4990f14d01603e61a0f5c744e'
),
(
  72,
  96,
  'priced',
  9840,
  'USD',
  array['CFLX7296BW']::text[],
  '{"page":99,"note":null}'::jsonb,
  '1fac782b598743a43164f64babba5c9ecda67fadd847a472a43ec4fe06b31744'
),
(
  78,
  96,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  '5410eb15d507971bdda0a32b46e98a9c6684a75b29f69669c825dc6048eae40f'
),
(
  82.5,
  96,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  '4b072931b9e8caaa6ffe00bc5a634a0b51c6df0e65564c959f6a01bfce0f1042'
),
(
  89,
  96,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  'df95b285a80da696339b554ad2a4246f0f2f213282fb2cfae44b340b7a2b6cba'
),
(
  95,
  96,
  'unavailable',
  null,
  'USD',
  '{}'::text[],
  '{"page":99,"note":"Use Two Blinds"}'::jsonb,
  'f08b345426893f70e10fdf9a04058a0d3fada8673640b993038f2b495adfd290'
)
) as generated(
  width_ceiling,
  height_ceiling,
  availability,
  cost_cents,
  currency,
  sku_codes,
  source_locator,
  cell_fingerprint
)
on conflict (program_id, width_ceiling, height_ceiling) do update set
  availability = excluded.availability,
  cost_cents = excluded.cost_cents,
  currency = excluded.currency,
  sku_codes = excluded.sku_codes,
  source_id = excluded.source_id,
  source_locator = excluded.source_locator,
  cell_fingerprint = excluded.cell_fingerprint;

with version as (
  select versions.id
    from public.sales_quote_v2_wholesale_versions versions
   where versions.version_key = 'norman-805-faux-wood-phase1'
), source as (
  select id
    from public.sales_quote_v2_wholesale_sources
   where source_key = 'norman-retail-guide-2026-07'
)
insert into public.sales_quote_v2_wholesale_programs (
  wholesale_version_id,
  manufacturer_code,
  product_key,
  program_key,
  style_key,
  color_key,
  display_name,
  cost_status,
  price_axis,
  configuration,
  option_schema,
  source_id,
  source_locator
)
select version.id, 'norman', rows.product_key, rows.program_key,
       rows.style_key, 'pure_white', rows.display_name,
       'account_scope_unverified', 'width_height',
       rows.configuration, '{}'::jsonb, source.id, rows.source_locator
from version cross join source cross join (
  values
    (
      'smartprivacy_faux',
      'smartprivacy_faux_2in_and_2_1_2in_slats_cordless',
      '',
      'Norman SmartPrivacy 2-inch Pure White',
      '{"slatSize":"2","colorName":"Pure White","wholesaleGap":"current_805_product_factor_unverified"}'::jsonb,
      '{"page":31}'::jsonb
    ),
    (
      'faux_wood',
      'faux_wood_2in_and_2_1_2in_slats_cordless',
      'premium_ultimate',
      'Norman Premium / Ultimate 2-inch Pure White',
      '{"slatSize":"2","colorName":"Pure White","productAlias":"Premium","catalogProductName":"Ultimate","wholesaleGap":"current_805_product_factor_unverified"}'::jsonb,
      '{"page":30}'::jsonb
    )
) as rows(
  product_key,
  program_key,
  style_key,
  display_name,
  configuration,
  source_locator
)
on conflict (
  wholesale_version_id,
  product_key,
  program_key,
  style_key,
  color_key
) do update set
  display_name = excluded.display_name,
  cost_status = excluded.cost_status,
  configuration = excluded.configuration,
  source_id = excluded.source_id,
  source_locator = excluded.source_locator;

with versions as (
  select versions.id, manufacturers.code
    from public.sales_quote_v2_wholesale_versions versions
    join public.sales_quote_v2_manufacturers manufacturers
      on manufacturers.id = versions.manufacturer_id
   where versions.version_key in (
     'lotus-west-a26-v1-phase1-faux-wood',
     'norman-805-faux-wood-phase1'
   )
), sources as (
  select id, source_key
    from public.sales_quote_v2_wholesale_sources
   where source_key = 'lotus-west-a26-v1'
)
insert into public.sales_quote_v2_wholesale_order_cost_rules (
  wholesale_version_id,
  manufacturer_code,
  product_key,
  program_key,
  rule_key,
  label,
  rule_kind,
  calculation,
  first_unit_cost_cents,
  additional_unit_cost_cents,
  flat_cost_cents,
  rate_basis_points,
  threshold_cents,
  threshold_operator,
  required_options,
  rule_status,
  source_id,
  source_locator
)
select versions.id, rows.manufacturer_code, rows.product_key, rows.program_key,
       rows.rule_key, rows.label, rows.rule_kind, rows.calculation,
       rows.first_unit_cost_cents, rows.additional_unit_cost_cents,
       rows.flat_cost_cents, rows.rate_basis_points, rows.threshold_cents,
       rows.threshold_operator, rows.required_options, rows.rule_status,
       sources.id, rows.source_locator
from (
  values
    (
      'lotus', 'lotus_faux_wood_blinds',
      'lotus_flx_2in_bright_white_custom',
      'lotus_small_order_under_50',
      'Small order under $50',
      'other', 'flat', null::bigint, null::bigint, 500::bigint,
      null::integer, 5000::bigint, 'subtotal_lt', '{}'::jsonb, 'authoritative',
      'lotus-west-a26-v1', '{"page":2}'::jsonb
    ),
    (
      'lotus', 'lotus_faux_wood_blinds',
      'lotus_flx_2in_bright_white_custom',
      'lotus_freight_free_above_2500',
      'Complimentary prepaid freight above $2,500',
      'freight', 'free_above_threshold', null::bigint, null::bigint,
      0::bigint, null::integer, 250000::bigint, 'subtotal_gte', '{}'::jsonb,
      'authoritative', 'lotus-west-a26-v1', '{"page":2}'::jsonb
    ),
    (
      'lotus', 'lotus_faux_wood_blinds',
      'lotus_flx_2in_bright_white_custom',
      'lotus_freight_below_2500_unresolved',
      'Freight below $2,500 is not priced by the source',
      'freight', 'unresolved', null::bigint, null::bigint, null::bigint,
      null::integer, 250000::bigint, 'subtotal_lt', '{}'::jsonb, 'unresolved',
      'lotus-west-a26-v1', '{"page":2}'::jsonb
    )
) as rows(
  manufacturer_code,
  product_key,
  program_key,
  rule_key,
  label,
  rule_kind,
  calculation,
  first_unit_cost_cents,
  additional_unit_cost_cents,
  flat_cost_cents,
  rate_basis_points,
  threshold_cents,
  threshold_operator,
  required_options,
  rule_status,
  source_key,
  source_locator
)
join versions on versions.code = rows.manufacturer_code
join sources on sources.source_key = rows.source_key
on conflict (wholesale_version_id, product_key, program_key, rule_key)
do update set
  label = excluded.label,
  rule_kind = excluded.rule_kind,
  calculation = excluded.calculation,
  first_unit_cost_cents = excluded.first_unit_cost_cents,
  additional_unit_cost_cents = excluded.additional_unit_cost_cents,
  flat_cost_cents = excluded.flat_cost_cents,
  rate_basis_points = excluded.rate_basis_points,
  threshold_cents = excluded.threshold_cents,
  threshold_operator = excluded.threshold_operator,
  required_options = excluded.required_options,
  rule_status = excluded.rule_status,
  source_id = excluded.source_id,
  source_locator = excluded.source_locator;

update public.sales_quote_v2_wholesale_versions versions
   set content_sha256 =
       public.compute_quote_v2_wholesale_version_content_sha256(versions.id),
       updated_at = now()
 where versions.version_key in (
   'lotus-west-a26-v1-phase1-faux-wood',
   'norman-805-faux-wood-phase1'
 );
