// Generated by scripts/generate-roman-dealer-fabrics.mjs from the Norman
// dealer Roman Shades order form data service. Do not edit by hand.
// Captured collections/styles: dealer form 2026-07-01 (account-level lists).

export interface NormanRomanDealerFabricRow {
  collection: string;
  colorCode: string;
  colorName: string;
  clothCode: string;
  maxWidth: string;
  joinable: string;
  openness: string;
  discontinued: boolean;
  priceGroup: "group1" | "group2" | "group3";
  needsPriceGroupReview: boolean;
  imageUrl: string;
  styles: readonly string[];
}

export const normanRomanDealerFabricRows: readonly NormanRomanDealerFabricRow[] = [
  {
    "collection": "Alma",
    "colorCode": "F1621",
    "colorName": "Dusk Blue",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1622",
    "colorName": "Coronet Blue",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1623",
    "colorName": "Dark Shadow",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1624",
    "colorName": "Paloma",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1625",
    "colorName": "Cloudburst",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1626",
    "colorName": "Whitecap Gray",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1627",
    "colorName": "Doeskin",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1628",
    "colorName": "Whisper White",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1629",
    "colorName": "Chalk White",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Alma",
    "colorCode": "F1631",
    "colorName": "Plum",
    "clothCode": "AA0355",
    "maxWidth": "108",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2071",
    "colorName": "Extra White",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2071-Extra-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2072",
    "colorName": "Warm White",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2072-Warm-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2073",
    "colorName": "Dovetail",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2073-Dovetail.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2074",
    "colorName": "Sand Canyon",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2074-Sand-Canyon.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2075",
    "colorName": "Driftwood",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2075-Driftwood.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ashley",
    "colorCode": "F2076",
    "colorName": "Light Fawn",
    "clothCode": "AA0387",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Ashley-F2076-Light-Fawn.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F0668",
    "colorName": "Black Walnut",
    "clothCode": "A90105",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Bali-F0668-Black-Walnut.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F1668",
    "colorName": "Sand",
    "clothCode": "A90105",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Bali-F1668-Sand.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F1669",
    "colorName": "Flax",
    "clothCode": "A90105",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Bali-F1669-Flax.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F1926",
    "colorName": "Latte",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Bail-F1926-Latte.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F1927",
    "colorName": "Stone Gray",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Bail-F1927-Stone-Gray.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F2023",
    "colorName": "Desert Beige",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Bali-F2023-Desert-Beige.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F2024",
    "colorName": "Warm Mocha",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Bali-F2024-Warm-Mocha.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F2025",
    "colorName": "Soft Sandstone",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Bali-F2025-Soft-Sandstone.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F2026",
    "colorName": "Gentle Ash",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Bali-F2026-Gentle-Ash.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bali",
    "colorCode": "F2027",
    "colorName": "Gray",
    "clothCode": "A90105",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Bali-F2027-Gray.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Belgian Linen",
    "colorCode": "F1051",
    "colorName": "Warm Gray 8029",
    "clothCode": "AA0901",
    "maxWidth": "54",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Belgian-Linen-F1051-Warm-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Belgian Linen",
    "colorCode": "F1057",
    "colorName": "Champagne 2598",
    "clothCode": "AA0902",
    "maxWidth": "114",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Belgian-Linen-F1057-Champagne.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Belgian Linen",
    "colorCode": "F1058",
    "colorName": "Gray 3232",
    "clothCode": "AA0902",
    "maxWidth": "114",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Belgian-Linen-F1058-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Belgian Linen",
    "colorCode": "F1061",
    "colorName": "Sag Harbor 0006",
    "clothCode": "AB0704",
    "maxWidth": "102",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Belgian-Linen-F1061-Sag-Harbor.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Blake",
    "colorCode": "F0247",
    "colorName": "Dark Slate",
    "clothCode": "AA0215",
    "maxWidth": "122",
    "joinable": "N",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Bora Bora",
    "colorCode": "F0662",
    "colorName": "Seashell White",
    "clothCode": "A90104",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bora Bora",
    "colorCode": "F0663",
    "colorName": "Straw",
    "clothCode": "A90104",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Bora-Bora-F0663-Straw.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Bora Bora",
    "colorCode": "F0869",
    "colorName": "Cinnamon",
    "clothCode": "A90104",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Bora-Bora-F0869-Cinnamon.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1897",
    "colorName": "Linen Natural",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1897-Linen-Natural.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1898",
    "colorName": "Linen Khaki",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1898-Linen-Khaki.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1899",
    "colorName": "Linen Graphite",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1899-Linen-Graphite.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1900",
    "colorName": "Linen Almond Milk",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1900-Linen-Almond-Milk.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1901",
    "colorName": "Linen Stone",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1901-Linen-Stone.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1902",
    "colorName": "Linen Warm Ivory",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1902-Linen-Warm-Ivory.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Breeze",
    "colorCode": "F1903",
    "colorName": "Linen Cloud ",
    "clothCode": "AB0699",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Breeze-F1903-Linen-Cloud.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F0867",
    "colorName": "White Sand",
    "clothCode": "AB0608",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Caroline-F0867-White-Sand.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1089",
    "colorName": "Optic White",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1090",
    "colorName": "Warm White",
    "clothCode": "AA0206-A",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1091",
    "colorName": "Taupe",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1092",
    "colorName": "Sky Gray",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1093",
    "colorName": "Dove Gray",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1094",
    "colorName": "Pale Green",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1095",
    "colorName": "Deep Khaki",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1096",
    "colorName": "Light Brown",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1097",
    "colorName": "Terra Cotta",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1098",
    "colorName": "Dark Brown",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1099",
    "colorName": "Navy",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1100",
    "colorName": "Medium Blue",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Caroline",
    "colorCode": "F1102",
    "colorName": "Greige",
    "clothCode": "AA0206",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Catalina",
    "colorCode": "F1605",
    "colorName": "Sea Salt",
    "clothCode": "AB0675",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Catalina-F1605-Sea-Salt.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Catalina",
    "colorCode": "F1712",
    "colorName": "Oatmeal",
    "clothCode": "AB0675",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Catalina-F1712-Oatmeal.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Ella",
    "colorCode": "F0178",
    "colorName": "Java",
    "clothCode": "AB0203",
    "maxWidth": "56",
    "joinable": "Y",
    "openness": "Opaque",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Ella-F0178-Java.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ella",
    "colorCode": "F0182",
    "colorName": "Spice",
    "clothCode": "AB0203",
    "maxWidth": "56",
    "joinable": "Y",
    "openness": "Opaque",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ellie",
    "colorCode": "F1939",
    "colorName": "Linen White",
    "clothCode": "AA0372",
    "maxWidth": "60.5",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Ellie-F1939-Linen-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ellie",
    "colorCode": "F1940",
    "colorName": "Wheat",
    "clothCode": "AA0372",
    "maxWidth": "60.5",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Ellie-F1940-Wheat.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Ellie",
    "colorCode": "F1941",
    "colorName": "Mist Gray",
    "clothCode": "AA0372",
    "maxWidth": "60.5",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Ellie-F1941-Mist-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1904",
    "colorName": "White",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1904-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1905",
    "colorName": "Weathered White",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1905-Weathered-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1906",
    "colorName": "Broken White",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1906-Broken-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1907",
    "colorName": "Soft Sandstone",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1907-Soft-Sandstone.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1908",
    "colorName": "Desert Beige",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1908-Desert-Beige.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1909",
    "colorName": "Rich Truffle",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1909-Rich-Truffle.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1932",
    "colorName": "Oatmeal",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1932-Oatmeal.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1933",
    "colorName": "Black",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Francis-F1933-Black.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1984",
    "colorName": "Soft Gray",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1984-Soft-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1985",
    "colorName": "Cloudy Gray",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1985-Cloudy-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1986",
    "colorName": "Natural Beige",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1986-Natural-Beige.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1987",
    "colorName": "Warm Mocha",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1987-Warm-Mocha-1.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1988",
    "colorName": "Graphite",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1988-Graphite.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1989",
    "colorName": "Stone Gray",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1989-Stone-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1990",
    "colorName": "Soothing Gray",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1990-Soothing-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Francis",
    "colorCode": "F1991",
    "colorName": "Gentle Ash",
    "clothCode": "AA0369",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Francis-F1991-Gentle-Ash.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1695",
    "colorName": "Gris Perle",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1695-Gris-PerleReverse.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1719",
    "colorName": "Almond Ash",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1719-Almond-AshReverse.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1720",
    "colorName": "Rose Dust",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1720-Rose-DustReverse.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1721",
    "colorName": "Coastal Sandstone",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1721-Coastal-SandstoneReverse.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1794",
    "colorName": "Ice White",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1794-Ice-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Impressions",
    "colorCode": "F1795",
    "colorName": "Warm White",
    "clothCode": "AA0361",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Impressions-F1795-Warm-WhiteReverse.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Java",
    "colorCode": "F0856",
    "colorName": "Raffia",
    "clothCode": "AB0609",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Java-F0856-Raffia.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Java",
    "colorCode": "F0857",
    "colorName": "Haystack",
    "clothCode": "AB0609",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Java-F0857-Haystack.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Java",
    "colorCode": "F0858",
    "colorName": "Natural",
    "clothCode": "AB0609",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Java-F0858-Natural.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Java",
    "colorCode": "F0859",
    "colorName": "Sage",
    "clothCode": "AB0609",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Java-F0859-Sage.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Java",
    "colorCode": "F1562",
    "colorName": "Toasted Brown",
    "clothCode": "AB0609",
    "maxWidth": "78",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Java-F1562-Toasted-Brown.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0183",
    "colorName": "Milk",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0184",
    "colorName": "Warm White",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0185",
    "colorName": "Pebble",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0186",
    "colorName": "Rich Gold",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0187",
    "colorName": "Steel Gray",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0188",
    "colorName": "Chocolate Brown",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0189",
    "colorName": "Loden Green",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0190",
    "colorName": "Deep Ocean",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0191",
    "colorName": "Claret",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lakeside",
    "colorCode": "F0192",
    "colorName": "Jet Black",
    "clothCode": "AA0210",
    "maxWidth": "53",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Edge Banded"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0031",
    "colorName": "Black Gingham",
    "clothCode": "AB0103",
    "maxWidth": "56",
    "joinable": "R",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0058",
    "colorName": "Seal Brown",
    "clothCode": "AA0201",
    "maxWidth": "58",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0193",
    "colorName": "Vanilla Ice",
    "clothCode": "AB0204",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Lorraine-F0193-Vanilla-Ice.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0194",
    "colorName": "Sand",
    "clothCode": "AB0204",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Lorraine-F0194-Sand.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0195",
    "colorName": "Espresso",
    "clothCode": "AB0204",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Lorraine-F0195-Espresso.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Lorraine",
    "colorCode": "F0196",
    "colorName": "Sedona Sage",
    "clothCode": "AB0204",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Lorraine-F0196-Sedona-Sage.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Louise",
    "colorCode": "F1708",
    "colorName": "Glacier Blue",
    "clothCode": "AB0681",
    "maxWidth": "126",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Louise-F1708-Glacier-Blue.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Louise",
    "colorCode": "F1709",
    "colorName": "White Jade",
    "clothCode": "AB0681",
    "maxWidth": "126",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Louise-F1709-White-Jade.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Louise",
    "colorCode": "F1710",
    "colorName": "Light Apricot",
    "clothCode": "AB0681",
    "maxWidth": "126",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Louise-F1710-Light-Apricot.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Louise",
    "colorCode": "F1711",
    "colorName": "Sepia",
    "clothCode": "AB0681",
    "maxWidth": "126",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Louise-F1711-Sepia.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1070",
    "colorName": "Woolen Gray",
    "clothCode": "AB0634",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1071",
    "colorName": "Woolen White",
    "clothCode": "AB0634",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1072",
    "colorName": "Olive Green",
    "clothCode": "AB0635",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1073",
    "colorName": "Sky Blue",
    "clothCode": "AB0635",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1074",
    "colorName": "Camel",
    "clothCode": "AB0635",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1075",
    "colorName": "Cadet Gray",
    "clothCode": "AB0635",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1076",
    "colorName": "Cosmic Latte",
    "clothCode": "AB0636",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1077",
    "colorName": "Charcoal",
    "clothCode": "AB0636",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1078",
    "colorName": "Ash Gray",
    "clothCode": "AB0636",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1079",
    "colorName": "Dark Cerulean",
    "clothCode": "AB0636",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1080",
    "colorName": "Snow White",
    "clothCode": "AB0637",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1081",
    "colorName": "Field Drab",
    "clothCode": "AB0637",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Patterns",
    "colorCode": "F1101",
    "colorName": "Moss Green",
    "clothCode": "AB0637",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0656",
    "colorName": "Snow White",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0656-Snow-White.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0657",
    "colorName": "Honey",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0657-Honey.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0659",
    "colorName": "Black Olive",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0659-Black-Olive.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0660",
    "colorName": "Grey Fog",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0660-Grey-Fog.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0661",
    "colorName": "Dust",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0661-Dust.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F0868",
    "colorName": "Dough",
    "clothCode": "A90103 ",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F0868-Dough.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Phuket",
    "colorCode": "F1670",
    "colorName": "Mocha",
    "clothCode": "A90103",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Phuket-F1670-Mocha.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Riviera",
    "colorCode": "F1290",
    "colorName": "Frost",
    "clothCode": "AB0651",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Riviera-F1290-Frost.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Riviera",
    "colorCode": "F1291",
    "colorName": "Sugar Cane",
    "clothCode": "AB0651",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Riviera-F1291-Sugar-Cane.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Riviera",
    "colorCode": "F1292",
    "colorName": "Honey",
    "clothCode": "AB0651",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Riviera-F1292-Honey.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Riviera",
    "colorCode": "F1293",
    "colorName": "Metal",
    "clothCode": "AB0651",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Riviera-F1293-Metal.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Riviera",
    "colorCode": "F1713",
    "colorName": "Silver Fox",
    "clothCode": "AB0651",
    "maxWidth": "94.5",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Riviera-F1713-Silver-Fox.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Rochelle",
    "colorCode": "F0228",
    "colorName": "French Roast",
    "clothCode": "AB0301",
    "maxWidth": "55",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Scarlett",
    "colorCode": "F1599",
    "colorName": "Cottage Linen",
    "clothCode": "AB0674",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "Sheer",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Scarlett-F1599-Cottage-Linen.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Scarlett",
    "colorCode": "F1600",
    "colorName": "Seashell",
    "clothCode": "AB0674",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "Sheer",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Scarlett-F1600-Seashell.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Scarlett",
    "colorCode": "F1601",
    "colorName": "Crema",
    "clothCode": "AB0674",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "Sheer",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Scarlett-F1601-Crema.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Scarlett",
    "colorCode": "F1602",
    "colorName": "Stone",
    "clothCode": "AB0674",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "Sheer",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Scarlett-F1602-Stone.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F0235",
    "colorName": "Egret",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Seabreeze-F0235-Egret.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F0236",
    "colorName": "Rich Cream",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Seabreeze-F0236-Rich-Cream.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F0238",
    "colorName": "Ebony",
    "clothCode": "AA0307",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Opaque",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Seabreeze-F0238-Ebony.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F0239",
    "colorName": "Tapestry Gold",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Seabreeze-F0239-Tapestry-Gold.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1956",
    "colorName": "Vanilla White",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1956-Vanilla-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1968",
    "colorName": "Gentle Ash",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1968-Gentle-Ash.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1969",
    "colorName": "Soft Sandstone",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1969-Soft-Sandstone.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1970",
    "colorName": "Desert Beige",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1970-Desert-Beige.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1971",
    "colorName": "Warm Mocha",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1971-Warm-Mocha.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1972",
    "colorName": "Anthracite Gray",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1972-Anthracite-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1973",
    "colorName": "Gray",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1973-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1974",
    "colorName": "Graphite",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1974-Graphite.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1975",
    "colorName": "Soothing Gray",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1975-Soothing-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1994",
    "colorName": "Cloudy Gray",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1994-Cloudy-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Seabreeze",
    "colorCode": "F1995",
    "colorName": "Rich Truffle",
    "clothCode": "AA0307-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "RD",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Seabreeze-F1995-Rich-Truffle.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sheer Elegance",
    "colorCode": "F1082",
    "colorName": "Corn White",
    "clothCode": "AC0401",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Sheer Elegance",
    "colorCode": "F1083",
    "colorName": "Sea Green",
    "clothCode": "AC0401",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Sheer Elegance",
    "colorCode": "F1085",
    "colorName": "Dim Ecru",
    "clothCode": "AC0402",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group1",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Sheer Elegance",
    "colorCode": "F1470",
    "colorName": "Cloud White",
    "clothCode": "AB0665",
    "maxWidth": "129",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group1",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2023/09/F1470-Cloud-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Sheer Elegance",
    "colorCode": "F1657",
    "colorName": "Floral White",
    "clothCode": "AB0665",
    "maxWidth": "129",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group1",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Sheer-Elegance-F1657-Floral-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1916",
    "colorName": "Snow",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1916-Snow.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1917",
    "colorName": "Cream",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1917-Cream.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1918",
    "colorName": "Natural",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1918-Natural.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1919",
    "colorName": "Silverware",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1919-Silverware.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1920",
    "colorName": "Canvas",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1920-Canvas.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1921",
    "colorName": "Graphite",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1921-Graphite.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1922",
    "colorName": "Stone",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1922-Stone.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sierra",
    "colorCode": "F1923",
    "colorName": "Caviar",
    "clothCode": "AB06100",
    "maxWidth": "110",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/04/Sierra-F1923-Caviar.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Solids",
    "colorCode": "F1063",
    "colorName": "Slate Gray",
    "clothCode": "AA0319",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Solids-F1063-Slate-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Solids",
    "colorCode": "F1064",
    "colorName": "Anti White",
    "clothCode": "AA0319",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Solids-F1064-Anti-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Solids",
    "colorCode": "F1067",
    "colorName": "Taupe",
    "clothCode": "AB0320",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group3",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Solids-F1067-Taupe.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Solids",
    "colorCode": "F1069",
    "colorName": "Linen White",
    "clothCode": "AA0802-A",
    "maxWidth": "110",
    "joinable": "Y",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Sumatra",
    "colorCode": "F0854",
    "colorName": "Fog",
    "clothCode": "AB0605",
    "maxWidth": "96",
    "joinable": "N",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Sumatra-F0854-Fog.jpg",
    "styles": [
      "Flat Fold with Batten Back"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0210",
    "colorName": "Corn Silk White",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0210-Corn-Silk-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Ribbon Banded",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0211",
    "colorName": "Khaki",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0211-Khaki.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0214",
    "colorName": "Sky Blue",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0214-Sky-Blue.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0217",
    "colorName": "India Ink",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0217-India-Ink.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0219",
    "colorName": "Puce",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0219-Puce.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0220",
    "colorName": "Tango Red",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0220-Tango-Red.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0221",
    "colorName": "Orange Spice",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0221-Orange-Spice.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Taylor",
    "colorCode": "F0261",
    "colorName": "Navy",
    "clothCode": "AA0305",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Taylor-F0261-Navy.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Valencia",
    "colorCode": "F0145",
    "colorName": "Rich Wheat",
    "clothCode": "AB0202",
    "maxWidth": "55",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Valencia",
    "colorCode": "F0255",
    "colorName": "Greige",
    "clothCode": "AA0217",
    "maxWidth": "57",
    "joinable": "Y",
    "openness": "Semi-transparent",
    "discontinued": false,
    "priceGroup": "group1",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Whispering Willow",
    "colorCode": "F2081",
    "colorName": "Diamond",
    "clothCode": "AB06103",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Whispering-Willow-F2081-Diamond.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Whispering Willow",
    "colorCode": "F2082",
    "colorName": "Dove",
    "clothCode": "AB06103",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Whispering-Willow-F2082-Dove.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Whispering Willow",
    "colorCode": "F2083",
    "colorName": "Cottage Straw",
    "clothCode": "AB06103",
    "maxWidth": "118",
    "joinable": "N",
    "openness": "",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2026/02/Whispering-Willow-F2083-Cottage-Straw.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0229",
    "colorName": "Pearl White",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Windsor-F0229-Pearl-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0230",
    "colorName": "Neutral Gray",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Windsor-F0230-Neutral-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0231",
    "colorName": "Smoke",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Windsor-F0231-Smoke.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0232",
    "colorName": "Earth",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Windsor-F0232-Earth.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0233",
    "colorName": "Toast",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F0234",
    "colorName": "Tarmac",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2020/03/Windsor-F0234-Tarmac.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1957",
    "colorName": "Lotus White",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1957-Lotus-White.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1976",
    "colorName": "Gentle Ash",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1976-Gentle-Ash.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1977",
    "colorName": "Soft Sandstone",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1977-Soft-Sandstone.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1978",
    "colorName": "Desert Beige",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1978-Desert-Beige.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1979",
    "colorName": "Warm Mocha",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1979-Warm-Mocha.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1980",
    "colorName": "Anthracite Gray",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1980-Anthracite-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1981",
    "colorName": "Gray",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1981-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1982",
    "colorName": "Graphite",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1982-Graphite.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1983",
    "colorName": "Soothing Gray",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1983-Soothing-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1992",
    "colorName": "Cloudy Gray",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1992-Cloudy-Gray.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  },
  {
    "collection": "Windsor",
    "colorCode": "F1993",
    "colorName": "Rich Truffle",
    "clothCode": "AA0306-A",
    "maxWidth": "60",
    "joinable": "Y",
    "openness": "LF",
    "discontinued": false,
    "priceGroup": "group2",
    "needsPriceGroupReview": false,
    "imageUrl": "https://normanusa.com/app/uploads/2025/08/Windsor-F1993-Rich-Truffle.jpg",
    "styles": [
      "Flat Fold without Seams",
      "Flat Fold with Batten Back",
      "Soft Fold"
    ]
  }
];
