"use client";
import {emptyNormanShutterDividerRecord,normanShutterDividerSizes,normanShutterDividerDeviation,normanShutterLouverSectionCount,type NormanShutterDividerRecord} from '@/lib/quote/norman-shutter-dividers';
export function NormanShutterDividerOptions({pricingOnly=false,value,panelNumber,programId,louver,splitOnly=false,onChange}:{pricingOnly?:boolean;value:NormanShutterDividerRecord|undefined;panelNumber:number;programId:string;louver:unknown;splitOnly?:boolean;onChange:(value:NormanShutterDividerRecord)=>void}){
 const r=value??{...emptyNormanShutterDividerRecord(),...(splitOnly?{rails:[]}:{}),splitTiltMode:'' as const};
 const update=(patch:Partial<NormanShutterDividerRecord>)=>{const next={...r,...patch};const gaps=Math.max(0,next.rails.length+next.splitTiltCentersInches.length-1);onChange({...next,clearLouverCounts:Array.from({length:gaps},(_,i)=>next.clearLouverCounts[i]??0)});};
 const railUpdate=(index:number,patch:Partial<NormanShutterDividerRecord['rails'][number]>)=>update({rails:r.rails.map((rail,i)=>i===index?{...rail,...patch}:rail)});
 const cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const prefix=`Norman panel ${panelNumber}`,deviation=normanShutterDividerDeviation(louver);
 if(pricingOnly)return <fieldset className="col-span-2 space-y-3"><legend>Panel {panelNumber} divider price options</legend>
  {r.rails.map((rail,index)=><div key={index}><label>Divider {index+1} size<select className={cls} aria-label={`${prefix} divider ${index+1} size`} value={rail.heightInches??''} onChange={e=>railUpdate(index,{heightInches:e.target.value===''?null:Number(e.target.value)})}><option value="">Select</option>{normanShutterDividerSizes(programId).map(size=><option key={size} value={size}>{size} inches{size>3?' · surcharge unverified':''}</option>)}</select></label>{r.rails.length>1&&<button type="button" onClick={()=>update({rails:r.rails.filter((_,i)=>i!==index)})}>Remove divider {index+1}</button>}</div>)}
  {!splitOnly&&<button type="button" onClick={()=>update({rails:[...r.rails,{heightInches:3,location:'',centerInches:null,exactLocation:null}]})}>Add divider for panel {panelNumber}</button>}
 </fieldset>;
 return <fieldset className="col-span-2 space-y-3 rounded border border-slate-200 p-3"><legend className="text-sm">Panel {panelNumber} {splitOnly?"split-tilt":"divider and split-tilt"} schedule</legend>
  <label className="block text-sm">Split-tilt location mode<select className={cls} aria-label={`${prefix} split tilt mode`} value={r.splitTiltMode??''} onChange={e=>update({splitTiltMode:e.target.value as 'equal'|'custom'|''})}><option value="">Select when using split tilt</option><option value="equal">Equal split by louver count</option><option value="custom">Custom measured locations</option></select></label>
  <label className="block text-sm">Location measurement basis<select className={cls} aria-label={`${prefix} divider basis`} value={r.measurementBasis} onChange={e=>update({measurementBasis:e.target.value as NormanShutterDividerRecord['measurementBasis'],referenceHeightInches:null,rails:r.rails.map(x=>({...x,centerInches:null})),splitTiltCentersInches:r.splitTiltCentersInches.map(()=>0)})}><option value="">Select</option><option value="window">From bottom of window</option><option value="max_frame">From bottom of frame</option>{splitOnly&&<option value="panel">From bottom of panel · no bottom frame, sill or sill cap</option>}</select></label>
  <label className="block text-sm">Actual reference height (inches)<input className={cls} aria-label={`${prefix} divider reference height`} type="number" min="0" step="0.0625" value={r.referenceHeightInches??''} onChange={e=>update({referenceHeightInches:e.target.value===''?null:Number(e.target.value)})}/></label>
  {r.rails.map((rail,index)=><div key={index} className="grid grid-cols-2 gap-3 rounded border border-slate-100 p-2">
   <label className="text-sm">Divider {index+1} size<select className={cls} aria-label={`${prefix} divider ${index+1} size`} value={rail.heightInches??''} onChange={e=>railUpdate(index,{heightInches:e.target.value===''?null:Number(e.target.value)})}><option value="">Select</option>{normanShutterDividerSizes(programId).map(size=><option key={size} value={size}>{size} inches{size>3?' · surcharge unverified':''}</option>)}</select></label>
   <label className="text-sm">Divider {index+1} location<select className={cls} aria-label={`${prefix} divider ${index+1} location`} value={rail.location} onChange={e=>railUpdate(index,{location:e.target.value as typeof rail.location})}><option value="">Select</option><option value="center">Default panel center</option><option value="specified">Specified measured center</option></select></label>
   {rail.location==='specified'&&<label className="text-sm">Center above selected datum (inches)<input className={cls} aria-label={`${prefix} divider ${index+1} center`} type="number" min="0" step="0.0625" value={rail.centerInches??''} onChange={e=>railUpdate(index,{centerInches:e.target.value===''?null:Number(e.target.value)})}/></label>}
   <label className="text-sm">Exact location required<select className={cls} aria-label={`${prefix} divider ${index+1} exact location`} value={rail.exactLocation===null?'':String(rail.exactLocation)} onChange={e=>railUpdate(index,{exactLocation:e.target.value===''?null:e.target.value==='true'})}><option value="">Select</option><option value="false">No · manufacturer tolerance applies</option><option value="true">Yes · exact location requested</option></select></label>
   {r.rails.length>1&&<button type="button" onClick={()=>update({rails:r.rails.filter((_,i)=>i!==index)})}>Remove divider {index+1}</button>}
  </div>)}
  {!splitOnly&&<button type="button" className={cls} onClick={()=>update({rails:[...r.rails,{heightInches:3,location:'',centerInches:null,exactLocation:null}]})}>Add divider for panel {panelNumber}</button>}
  {r.splitTiltCentersInches.map((center,index)=><div key={index} className="flex gap-3"><label className="text-sm">Split tilt {index+1} top of closed louver above datum<input className={cls} aria-label={`${prefix} split tilt ${index+1} top of closed louver`} type="number" min="0" step="0.0625" value={center||''} onChange={e=>update({splitTiltCentersInches:r.splitTiltCentersInches.map((n,i)=>i===index?Number(e.target.value):n)})}/></label><label className="text-sm">Exact split location required<select className={cls} aria-label={`${prefix} split tilt ${index+1} exact location`} value={r.splitTiltExactLocations?.[index]==null?'':String(r.splitTiltExactLocations[index])} onChange={e=>update({splitTiltExactLocations:r.splitTiltCentersInches.map((_,i)=>i===index?(e.target.value===''?null:e.target.value==='true'):r.splitTiltExactLocations?.[i]??null)})}><option value="">Select</option><option value="false">Allow deviations</option><option value="true">Exact location requested</option></select></label><button type="button" onClick={()=>update({splitTiltCentersInches:r.splitTiltCentersInches.filter((_,i)=>i!==index),splitTiltExactLocations:r.splitTiltExactLocations?.filter((_,i)=>i!==index)})}>Remove split tilt {index+1}</button></div>)}
  <button type="button" className={cls} onClick={()=>update({splitTiltMode:'custom',splitTiltCentersInches:[...r.splitTiltCentersInches,0],splitTiltExactLocations:[...(r.splitTiltExactLocations??[]),null]})}>Add split-tilt location for panel {panelNumber}</button>
  {r.splitTiltCentersInches.length>0&&<label className="flex gap-2 text-sm"><input type="checkbox" aria-label={`${prefix} split locations measured to top of closed louver`} checked={r.splitTiltReference==='top_closed_louver'} onChange={e=>update({splitTiltReference:e.target.checked?'top_closed_louver':undefined})}/>Custom split measurements are to the top of each closed louver, not a louver center.</label>}
  {r.splitTiltMode==='equal'&&<p className="text-sm">Equal split uses louver count: an odd total gives the bottom section one additional louver. Final rail and louver layout remains unverified.</p>}
  {Array.from({length:normanShutterLouverSectionCount(r)},(_,index)=><label key={`section-${index}`} className="block text-sm">Actual louvers in section {index+1}, bottom to top<input className={cls} aria-label={`${prefix} section ${index+1} louver count`} type="number" min="0" step="1" value={r.sectionLouverCounts?.[index]??''} onChange={e=>update({sectionLouverCounts:Array.from({length:normanShutterLouverSectionCount(r)},(_,i)=>i===index?Number(e.target.value):r.sectionLouverCounts?.[i]??0)})}/></label>)}
  <p className="text-sm">Include the bottom and top sections. A one-louver section cannot use divider rails or split tilt. Enter actual factory layout counts; opening height does not establish these counts.</p>
  {r.clearLouverCounts.map((count,index)=><label key={index} className="block text-sm">Clear louvers between consecutive locations {index+1} and {index+2}, bottom to top<input className={cls} aria-label={`${prefix} clear louver interval ${index+1}`} type="number" min="0" step="1" value={count||''} onChange={e=>update({clearLouverCounts:r.clearLouverCounts.map((n,i)=>i===index?Number(e.target.value):n)})}/></label>)}
  <p className="text-sm">Nonmotorized shutters require at least two actual clear louvers between adjacent rail/split locations. {deviation!==null?`The guide's location tolerance for this louver is ${deviation} inch(es), unless exact location is requested.`:''} Final louver layout and any custom-size charge remain subject to verification.</p>
 </fieldset>;
}
