'use client';
import {useEffect,useState} from 'react';
import type {SalesQuoteDesign} from '@mts/types/quote';
import {ROLLER_LIGHT_GUARD_KEY as KEY,ROLLER_BASIC_GUARD_COLORS,ROLLER_WOOD_GUARD_COLORS,emptyRollerLightGuard,parseRollerLightGuard,type RollerLightGuard} from '@/lib/quote/norman-roller-light-guard';
export function NormanRollerLightGuardOptions({design,onUpdateFields}:{design:SalesQuoteDesign|undefined;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const options=(design?.options_json??{}) as Record<string,unknown>,incoming=parseRollerLightGuard(options[KEY])??emptyRollerLightGuard(),serialized=JSON.stringify(incoming),key=design?.id??'';
 const [state,setState]=useState(()=>({key,base:serialized,draft:incoming,submitted:null as string|null}));
 useEffect(()=>setState(s=>{if(s.key!==key||JSON.stringify(s.draft)===serialized)return {key,base:serialized,draft:JSON.parse(serialized),submitted:null};if(s.submitted===serialized)return {...s,base:serialized,submitted:null};return s.submitted||JSON.stringify(s.draft)!==s.base?s:{key,base:serialized,draft:JSON.parse(serialized),submitted:null};}),[key,serialized]);
 const r=state.draft,dirty=JSON.stringify(r)!==(state.submitted??state.base),edit=(p:Partial<RollerLightGuard>)=>setState(s=>({...s,draft:{...s.draft,...p}})),cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const mount=String(design?.mount_type??options.mount_type??''),inside=/^(inside( mount)?|im|ib)$/i.test(mount),cassette=/cassette/i.test([design?.valance,options.roller_top_treatment,options.top_treatment_class].join(' ')),lg360=/light\s*guard\s*360/i.test([options.roller_application,design?.shade_type,design?.valance].join(' '));
 if(!inside||lg360)return <section className="text-sm"><p>Basic and Premium Wood Light Guard require Inside Mount and are separate from LightGuard360.</p>{options[KEY]!=null&&<button type="button" onClick={()=>onUpdateFields({options_json:{...options,[KEY]:null}})}>Clear Roller Light Guard selection</button>}</section>;
 return <section className="space-y-3 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">Roller Light Guard</h3><label className="block text-sm">Light Guard type<select className={cls} aria-label="Roller Light Guard type" value={r.kind} onChange={e=>edit({kind:e.target.value as RollerLightGuard['kind'],color:'',leftLength:null,rightLength:null})}>{(cassette?['None','Basic']:['None','Basic','Premium Wood']).map(v=><option key={v}>{v}</option>)}</select></label>
 {r.kind!=='None'&&<><label className="block text-sm">Light Guard finish<select className={cls} aria-label="Roller Light Guard finish" value={r.color} onChange={e=>edit({color:e.target.value})}><option value="">Select exact finish</option>{(r.kind==='Basic'?ROLLER_BASIC_GUARD_COLORS:ROLLER_WOOD_GUARD_COLORS).map(v=><option key={v}>{v}</option>)}</select></label>{(['leftLength','rightLength'] as const).map((field,i)=><label className="block text-sm" key={field}>{i?'Right':'Left'} requested channel length (inches)<input className={cls} type="number" step="any" aria-label={`Roller ${i?'right':'left'} Light Guard channel length`} value={r[field]??''} onChange={e=>edit({[field]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<p className="text-xs">One set contains two side channels. Common valances and coupled shades receive one set per assembly. Cassette uses Basic only, without a top block. Basic channels above 96 inches are spliced; Premium Wood splicing requires confirmation; no unlisted factory cutting deduction is assumed.</p>{r.kind==='Premium Wood'&&<p className="text-xs">Stone Gray and Limed White use the larger 35 mm channel. Other finishes retain the documented 30 mm width until the running change is confirmed.</p>}</>}
 <button className={cls} type="button" disabled={!dirty} onClick={()=>{setState(s=>({...s,submitted:JSON.stringify(s.draft)}));onUpdateFields({options_json:{...options,[KEY]:r}});}}>Save Roller Light Guard</button><p role="status">{dirty?'Unsaved Roller Light Guard':state.submitted?'Roller Light Guard submitted':'No unsaved Roller Light Guard'}</p></section>;
}
