'use client';
import {useEffect,useState} from 'react';
import type {SalesQuoteDesign} from '@mts/types/quote';
import {normanRollerFabricColors} from '@/lib/quote/norman-roller-fabrics';
import {ROLLER_VALANCE_KEY as KEY,ROLLER_SEPARATE_VALANCE,ROLLER_VALANCE_STYLES,ROLLER_FASCIA_COLORS,ROLLER_CAP_COLORS,ROLLER_VALANCE_HOLD,emptyRollerValance,parseRollerValance,newRollerValanceDraft,syncRollerValanceDraft,rollerValanceDirty,type RollerValanceRecord} from '@/lib/quote/norman-roller-valance-only';
export function NormanRollerValanceOptions({design,productId,lineOptions,onUpdateFields}:{design:SalesQuoteDesign|undefined;productId:string;lineOptions:readonly {lineId:string;label:string;design:SalesQuoteDesign}[];onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const options=(design?.options_json??{}) as Record<string,unknown>,key=`${design?.id??''}:${productId}`,incoming=parseRollerValance(options[KEY])??emptyRollerValance(),serialized=JSON.stringify(incoming);
 const [state,setState]=useState(()=>newRollerValanceDraft(key,incoming));
 useEffect(()=>setState(old=>syncRollerValanceDraft(old,key,JSON.parse(serialized) as RollerValanceRecord)),[key,serialized]);
 const r=state.record,patch=(p:Partial<RollerValanceRecord>)=>setState(old=>({...old,record:{...old.record,...p}})),cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const select=(label:string,value:string,values:readonly string[],change:(v:string)=>void)=><label className="block text-sm">{label}<select aria-label={label} className={cls} value={value} onChange={e=>change(e.target.value)}><option value="">Select</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
 const number=(label:string,value:number|null,change:(v:number|null)=>void)=><label className="block text-sm">{label}<input aria-label={label} className={cls} type="number" step="any" value={value??''} onChange={e=>change(e.target.value===''?null:Number(e.target.value))}/></label>;
 const separate=productId===ROLLER_SEPARATE_VALANCE,fabric=/Fabric/.test(r.style),wrapped=/with Fabric/.test(r.style),lines=lineOptions.filter(l=>(l.design.options_json?.catalog_product_id??l.design.options_json?.quote_lab_product_id)==='roller'&&l.design.supplier==='Norman');
 return <section data-testid="norman-roller-valance-options" className="space-y-3 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">Roller {separate?'Separate Valance':'Valance Only'}</h3><p role="status" className="text-sm text-amber-900">{ROLLER_VALANCE_HOLD}</p>
 {select('Roller valance style',r.style,ROLLER_VALANCE_STYLES,v=>patch({style:v,fabricCode:'',fasciaColor:'',endCapColor:''}))}
 {number('Roller valance end-to-end width in inches',r.width,v=>patch({width:v}))}
 {select('Roller valance mount',r.mount,['Inside','Outside'],v=>patch({mount:v as RollerValanceRecord['mount']}))}
 {number('Roller valance return length in inches',r.returnLength,v=>patch({returnLength:v}))}
 <p className="text-xs">Specify the return length; there is no default. Zero records no returns. The valance line has no raceway and uses large valance brackets.</p>
 {fabric?<label className="block text-sm">Roller valance fabric and color<select aria-label="Roller valance fabric and color" className={cls} value={r.fabricCode} onChange={e=>patch({fabricCode:e.target.value})}><option value="">Select exact fabric/color</option>{normanRollerFabricColors.filter(c=>c.available).map(c=><option key={c.colorCode} value={c.colorCode}>{c.collection} · {c.colorCode} · {c.colorName} · {c.fabricType}</option>)}</select></label>:select('Roller valance fascia color',r.fasciaColor,ROLLER_FASCIA_COLORS,v=>patch({fasciaColor:v}))}
 {wrapped&&select('Roller valance end cap color',r.endCapColor,ROLLER_CAP_COLORS,v=>patch({endCapColor:v}))}
 {select('Roller valance joinery',r.joinery,['Connector','Keystone'],v=>patch(v==='Keystone'?{joinery:'Keystone',keystoneCount:1}:{joinery:'Connector',layout:'Equally Centered',keystoneShape:'',keystoneCount:0,locations:[]}))}
 {r.joinery==='Keystone'&&<>
 {select('Roller valance keystone shape',r.keystoneShape,['V-Shape','Square'],v=>patch({keystoneShape:v as RollerValanceRecord['keystoneShape']}))}
 {select('Roller valance keystone count',String(r.keystoneCount),['1','2','3','4','5'],v=>patch({keystoneCount:Number(v),locations:r.layout==='Custom'?Array.from({length:Number(v)},(_,i)=>r.locations[i]??null):[]}))}
 {select('Roller valance splice layout',r.layout,['Equally Centered','Custom'],v=>patch({layout:v as RollerValanceRecord['layout'],locations:v==='Custom'?Array.from({length:r.keystoneCount},()=>null):[]}))}
 {r.layout==='Custom'&&r.locations.map((v,i)=><div key={i}>{number(`Roller valance keystone ${i+1} center from left`,v,n=>patch({locations:r.locations.map((old,j)=>i===j?n:old)}))}</div>)}
 </>}
 {separate&&<fieldset className="space-y-2"><legend>Associated Roller shades</legend><p className="text-xs">Select the shade lines covered by this valance. Mixed lift systems are allowed; all shades require raceway and the same mount. Single and Dual shades cannot mix. Coupled shades count as one assembly.</p>{lines.map(l=><label className="block text-sm" key={l.lineId}><input type="checkbox" checked={r.associatedLineIds.includes(l.lineId)} onChange={e=>patch({associatedLineIds:e.target.checked?[...r.associatedLineIds,l.lineId]:r.associatedLineIds.filter(id=>id!==l.lineId)})}/>{l.label}</label>)}{!lines.length&&<p className="text-sm">Add the associated Norman Roller shades to this quote first.</p>}<label className="block text-sm"><input type="checkbox" checked={r.controlClearanceConfirmed} onChange={e=>patch({controlClearanceConfirmed:e.target.checked})}/>Space is available for all required tension devices or AutoWand hooks</label></fieldset>}
 <p className="text-xs">Minimum width 8 inches. Sections are limited to 95 inches or the smaller fabric limit. Custom keystones require 18 inches from ends and one another. At Gaps is unavailable for Separate Valance. Fabric roll widths are checked by exact color code. Associated hardware compatibility remains held until derived.</p>
 <div className="flex items-center gap-3"><button type="button" className={cls} disabled={!rollerValanceDirty(state)} onClick={()=>{setState(old=>({...old,submitted:old.record}));onUpdateFields({valance:r.style||null,options_json:{...options,catalog_program_id:`${productId}_source`,quote_lab_program_id:`${productId}_source`,[KEY]:r}});}}>Save Roller valance</button><span role="status">{rollerValanceDirty(state)?'Unsaved selection':state.submitted?'Selection submitted':'No unsaved selection'}</span></div></section>;
}
