"use client";
import type {SalesQuoteDesign} from "@mts/types/quote";
export function NormanRollerPanelOptions({design,onUpdateFields}:{design:SalesQuoteDesign|undefined;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const c=(design?.options_json??{}) as Record<string,unknown>;
 const eligible=/motor/i.test(String(design?.lift_system))&&(c.roller_power_configuration??c.power_configuration)==="Automate Low Voltage DC Motor";
 const active=/distribution panel/i.test(String(c.dc_power_supply));
 if(!eligible)return active?<section className="rounded-lg border border-amber-200 p-3"><p>The saved Automate shared panel requires a compatible low-voltage motor.</p><button type="button" onClick={()=>onUpdateFields({options_json:{...c,dc_power_supply:null,shared_power_panel_id:null}})}>Clear Roller shared panel</button></section>:null;
 return <section data-testid="norman-roller-panel" className="space-y-2 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">Automate shared power panel</h3><label className="block text-sm">Connect motors to panel<select aria-label="Roller Automate shared power panel" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm" value={active?String(c.shared_power_panel_id??""):""} onChange={e=>onUpdateFields({options_json:{...c,dc_power_supply:e.target.value?"DC Distribution Panel":null,shared_power_panel_id:e.target.value||null}})}><option value="">No shared panel selected</option>{Array.from({length:50},(_,i)=>`Panel ${i+1}`).map(p=><option key={p}>{p}</option>)}</select></label><p className="text-xs text-slate-600">Up to 18 Automate low-voltage motors across connected Roller, Roman and PerfectSheer lines. Dual shades use two motor connections. One black AC power cord is included per white panel and one white connector harness per motor. The panel is charged once.</p></section>;
}
