"use client";
import {normanDoubleHungLayouts,type NormanDoubleHungRecord} from '@/lib/quote/norman-shutter-double-hung';
export function NormanShutterDoubleHungOptions({value,programId,onChange,onLayout}:{value:NormanDoubleHungRecord|undefined;programId:string;onChange:(v:NormanDoubleHungRecord)=>void;onLayout:(layout:string)=>void}){
 const r=value??{version:1,rowLayout:'',divisionMode:'',customDivisionPointInches:null,customReference:'',horizontalTPost:null,tPostSectionLengthsInches:[]} satisfies NormanDoubleHungRecord;
 const update=(patch:Partial<NormanDoubleHungRecord>)=>onChange({...r,...patch});
 const cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 return <fieldset className="space-y-3"><legend className="font-semibold">Double Hung upper and lower rows</legend>
  <label className="block text-sm">Layout in each row<select aria-label="Norman Double Hung row layout" className={cls} value={r.rowLayout} onChange={e=>onLayout(e.target.value)}><option value="">Select</option>{normanDoubleHungLayouts(programId).map(layout=><option key={layout}>{layout}</option>)}</select></label>
  <p className="text-sm text-slate-600">Enter the upper row left to right, then the lower row left to right. Both rows count toward the total number of panels; each finished panel has its own measurements.</p>
  <label className="block text-sm">Division position<select aria-label="Norman Double Hung division" className={cls} value={r.divisionMode} onChange={e=>update({divisionMode:e.target.value as NormanDoubleHungRecord['divisionMode']})}><option value="">Select</option><option value="center">Center · source default</option><option value="custom">Custom measured division</option></select></label>
  {r.divisionMode==='custom'&&<><label className="block text-sm">Custom division location (inches)<input aria-label="Norman Double Hung division location" className={cls} type="number" min="0" step="0.0625" value={r.customDivisionPointInches??''} onChange={e=>update({customDivisionPointInches:e.target.value===''?null:Number(e.target.value)})}/></label><label className="block text-sm">Measurement reference<input aria-label="Norman Double Hung division reference" className={cls} value={r.customReference} onChange={e=>update({customReference:e.target.value})}/></label></>}
  <label className="block text-sm">Horizontal T-post<select aria-label="Norman Double Hung horizontal T-post" className={cls} value={r.horizontalTPost===null?'':r.horizontalTPost?'yes':'no'} onChange={e=>update({horizontalTPost:e.target.value===''?null:e.target.value==='yes',tPostSectionLengthsInches:e.target.value==='no'?[]:r.tPostSectionLengthsInches})}><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select></label>
  {r.horizontalTPost===true&&<><label className="block text-sm">Horizontal T-post sections<select aria-label="Norman Double Hung T-post section count" className={cls} value={r.tPostSectionLengthsInches.length||''} onChange={e=>update({tPostSectionLengthsInches:Array.from({length:Number(e.target.value)},(_,i)=>r.tPostSectionLengthsInches[i]??null)})}><option value="">Select</option>{Array.from({length:16},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>{r.tPostSectionLengthsInches.map((length,index)=><label key={index} className="block text-sm">Horizontal T-post section {index+1} length (inches)<input aria-label={`Norman Double Hung T-post section ${index+1} length`} className={cls} type="number" min="0" max="48" step="0.0625" value={length??''} onChange={e=>update({tPostSectionLengthsInches:r.tPostSectionLengthsInches.map((v,i)=>i===index?(e.target.value===''?null:Number(e.target.value)):v)})}/></label>)}</>}
  <p className="text-sm text-amber-900">Final division geometry, rail sizes, hinges, mounting and account pricing remain under review. No opening-size division or factory rail adjustment is assumed.</p>
 </fieldset>;
}
