"use client";
import {useEffect,useState} from "react";
import type {SalesQuoteDesign} from "@mts/types/quote";
import {SMARTFOLD_CLEARANCE_KEY as KEY,emptySmartfoldClearance,parseSmartfoldClearance,newSmartfoldClearanceDraft,syncSmartfoldClearanceDraft,smartfoldClearanceDirty,type SmartfoldClearance} from "@/lib/quote/norman-smartfold-clearance";
export function NormanSmartfoldClearanceOptions({design,onUpdateFields}:{design:SalesQuoteDesign|undefined;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const c=(design?.options_json??{}) as Record<string,unknown>,key=design?.id??"",incoming=parseSmartfoldClearance(c[KEY])??emptySmartfoldClearance(),serialized=JSON.stringify(incoming);
 const [draft,setDraft]=useState(()=>newSmartfoldClearanceDraft(key,incoming));useEffect(()=>setDraft(s=>syncSmartfoldClearanceDraft(s,key,JSON.parse(serialized) as SmartfoldClearance)),[key,serialized]);
 if(!/outside/i.test(String(design?.mount_type)))return null;
 const field=(label:string,k:"mountingAreaHeight"|"mountingSpaceHeight")=><label className="block text-sm">{label}<input aria-label={label} className="w-full rounded-lg border border-slate-300 px-3 py-2" type="number" min={0} step="any" value={draft.record[k]??""} onChange={e=>setDraft(s=>({...s,record:{...s.record,[k]:e.target.value===""?null:Number(e.target.value)}}))}/></label>;
 return <section data-testid="norman-smartfold-clearance" className="space-y-3 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">SmartFold outside mounting clearance</h3>{field("Screw mounting-area height (inches)","mountingAreaHeight")}{field("Available shade mounting-space height (inches)","mountingSpaceHeight")}<p className="text-xs text-slate-600">Measure these separately. The 3½/4½-inch brackets need ¾-inch screw mounting area and 1½-inch shade space. Six-inch brackets need 1.15-inch screw area and 2-inch shade space. Source: SmartFold Guide page 34.</p><button type="button" className="rounded-lg border border-slate-300 px-3 py-2 text-sm" disabled={!smartfoldClearanceDirty(draft)} onClick={()=>{setDraft(s=>({...s,submitted:s.record}));onUpdateFields({options_json:{...c,[KEY]:draft.record}});}}>Save SmartFold mounting clearance</button><p role="status">{smartfoldClearanceDirty(draft)?"Unsaved SmartFold mounting clearance":draft.submitted?"SmartFold mounting clearance submitted":"No unsaved SmartFold mounting clearance"}</p></section>;
}
