"use client";
import {emptyNormanSpecialtyGeometry,NORMAN_SPECIALTY_ARCH_SHAPES,NORMAN_SPECIALTY_QUARTER_LEG_SHAPES,NORMAN_SPECIALTY_TWO_LEG_SHAPES,NORMAN_SPECIALTY_T_POST_SHAPES,type NormanSpecialtyGeometryRecord} from '@/lib/quote/norman-shutter-specialty-geometry';
export function NormanShutterSpecialtyGeometryOptions({value,shapeCode,onChange}:{value:NormanSpecialtyGeometryRecord|undefined;shapeCode:string;onChange:(r:NormanSpecialtyGeometryRecord)=>void}){
 const g=value??emptyNormanSpecialtyGeometry(),update=(p:Partial<NormanSpecialtyGeometryRecord>)=>onChange({...g,...p}),cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const number=(key:'widthInches'|'heightInches'|'legHeightInches'|'middleHeightInches'|'leftLegHeightInches'|'rightLegHeightInches'|'peakWidthAInches',label:string)=><label className="block text-sm" key={key}>{label}<input type="number" className={cls} aria-label={`Norman specialty ${label}`} min="0" step="0.0625" value={g[key]??''} onChange={e=>update({[key]:e.target.value===''?null:Number(e.target.value)})}/></label>;
 return <fieldset className="space-y-3"><legend>Specialty order outline and template</legend>
  <p className="text-sm">These are order-outline measurements, separate from the opening and finished panels. Save with panel construction.</p>
  {number('widthInches','order width (inches)')}{number('heightInches','order height (inches)')}
  <label className="block text-sm">Outline classification<select className={cls} aria-label="Norman specialty outline" value={g.outline} onChange={e=>update({outline:e.target.value as NormanSpecialtyGeometryRecord['outline']})}><option value="">Select</option>{!NORMAN_SPECIALTY_ARCH_SHAPES.includes(shapeCode)&&<option value="not_arch">Not an arch</option>}<option value="perfect">Perfect arch · same radius and center throughout</option><option value="imperfect">Imperfect arch · template required</option></select></label>
  <label className="block text-sm">Mounting on existing molding<select className={cls} aria-label="Norman specialty existing molding" value={g.existingMolding===null?'':String(g.existingMolding)} onChange={e=>update({existingMolding:e.target.value===''?null:e.target.value==='true'})}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label>
  {(NORMAN_SPECIALTY_QUARTER_LEG_SHAPES.includes(shapeCode)||shapeCode==='YS56')&&number('legHeightInches','order leg height (inches)')}
  {(NORMAN_SPECIALTY_QUARTER_LEG_SHAPES.includes(shapeCode)||['YS02','YS06'].includes(shapeCode))&&number('middleHeightInches','order middle height (inches)')}
  {NORMAN_SPECIALTY_TWO_LEG_SHAPES.includes(shapeCode)&&<>{number('leftLegHeightInches','order left leg height (inches)')}{number('rightLegHeightInches','order right leg height (inches)')}</>}
  {NORMAN_SPECIALTY_T_POST_SHAPES.includes(shapeCode)&&<>
   <label className="block text-sm">Vertical T-post count<input type="number" className={cls} aria-label="Norman specialty vertical T-post count" min="2" step="1" value={g.verticalTPostCount??''} onChange={e=>update({verticalTPostCount:e.target.value===''?null:Number(e.target.value),verticalTPostLocationsInches:[]})}/></label>
   <p className="text-sm">Two posts require no custom positions. Three require the middle post position. More than three require every position. Final outer locations follow the actual outline.</p>
   {Array.from({length:g.verticalTPostCount===3?1:g.verticalTPostCount!==null&&Number.isInteger(g.verticalTPostCount)&&g.verticalTPostCount>3?Math.min(g.verticalTPostCount,64):0},(_,i)=><label className="block text-sm" key={i}>{g.verticalTPostCount===3?'Middle (second)':'T-post '+(i+1)} requested location from left (inches)<input className={cls} type="number" min="0" step="0.0625" aria-label={`Norman specialty T-post requested location ${i+1}`} value={g.verticalTPostLocationsInches[i]??''} onChange={e=>{const positions=Array.from({length:Math.max(i+1,g.verticalTPostLocationsInches.length)},(_,index)=>g.verticalTPostLocationsInches[index]??0);positions[i]=e.target.value===''?0:Number(e.target.value);update({verticalTPostLocationsInches:positions});}}/></label>)}
  </>}
  {shapeCode==='YS62'&&<><label className="block text-sm">Peak centered<select className={cls} aria-label="Norman specialty peak centered" value={g.centeredPeak===null?'':String(g.centeredPeak)} onChange={e=>update({centeredPeak:e.target.value===''?null:e.target.value==='true',peakWidthAInches:null})}><option value="">Select</option><option value="true">Yes · WA equals half order width</option><option value="false">No · measure WA</option></select></label>{g.centeredPeak===false&&number('peakWidthAInches','peak WA from left (inches)')}</>}
  <label className="block text-sm">Template submission reference<input className={cls} aria-label="Norman specialty template reference" value={g.templateReference} onChange={e=>update({templateReference:e.target.value})}/></label>
  <p className="text-sm text-amber-900">Inside mount, imperfect arches, existing molding and oval shapes require a template. Resend templates older than one year. A reference does not establish factory acceptance; final outline and pricing remain held.</p>
 </fieldset>;
}
