"use client";
import {useEffect,useState} from 'react';
import type {SalesQuoteDesign} from '@mts/types/quote';
import {SMARTDRAPE_REPLACEMENT as ID,SMARTDRAPE_REPLACEMENT_RECORD as KEY,SMARTDRAPE_REPLACEMENT_HOLD,parseReplacementRequest,emptyReplacementRequest,replacementColors,replacementStacks,replacementComposition,type ReplacementRequest} from '@/lib/quote/norman-smartdrape-replacement';
export function NormanSmartdrapeReplacementOptions({design,onUpdateFields,pricingOnly=false}:{design:SalesQuoteDesign|undefined;pricingOnly?:boolean;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const options=(design?.options_json??{}) as Record<string,unknown>,incoming=parseReplacementRequest(options[KEY])??emptyReplacementRequest(),serialized=JSON.stringify(incoming),key=design?.id??'';
 const [state,setState]=useState(()=>({key,base:serialized,record:incoming,submitted:''}));
 useEffect(()=>{setState(s=>{if(s.key!==key||JSON.stringify(s.record)===serialized)return {key,base:serialized,record:JSON.parse(serialized),submitted:''};if(s.submitted===serialized)return {...s,base:serialized,submitted:''};if(s.submitted||JSON.stringify(s.record)!==s.base)return s;return {key,base:serialized,record:JSON.parse(serialized),submitted:''};});},[key,serialized]);
 const r=state.record,update=(patch:Partial<ReplacementRequest>)=>setState(s=>({...s,record:{...s.record,...patch}})),dirty=JSON.stringify(r)!==(state.submitted||state.base),first=replacementColors.find(f=>f.customerColorCode===r.firstColor),composition=replacementComposition(r);
 const save=()=>{setState(s=>({...s,submitted:JSON.stringify(s.record)}));onUpdateFields({fabric:first?.category??null,options_json:{...options,catalog_program_id:`${ID}_source`,quote_lab_program_id:`${ID}_source`,[KEY]:r,fabric_color_code:r.firstColor,fabric_color_name:first?.colorName??null,fabric_color_collection:first?.category??null}});};
 const cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const colorOptions=(category?:string)=><><option value="">Select color</option>{replacementColors.filter(f=>!category||f.category===category).map(f=><option key={f.customerColorCode} value={f.customerColorCode}>{f.category} · {f.customerColorCode} · {f.colorName}</option>)}</>;
 return <section data-testid="norman-smartdrape-replacement-options" className="space-y-3 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">Standalone SmartDrape vane packs</h3><p role="status" className="text-sm text-amber-900">{SMARTDRAPE_REPLACEMENT_HOLD}</p>
 {!pricingOnly&&<label className="block text-sm">Original Norman work-order number<input aria-label="Original Norman work-order number" className={cls} value={r.originalWorkOrder} onChange={e=>update({originalWorkOrder:e.target.value})}/></label>}
 <label className="block text-sm">Pack style<select aria-label="Replacement pack style" className={cls} value={r.style} onChange={e=>update({style:e.target.value as ReplacementRequest['style']})}><option value="">Select style</option><option value="A">A · first, middle and last vanes</option><option value="B">B · six middle vanes</option></select></label>
 <label className="block text-sm">Original shade arrangement<select aria-label="Original shade arrangement" className={cls} value={r.shadeType} onChange={e=>update({shadeType:e.target.value as ReplacementRequest['shadeType'],stack:''})}><option>Single</option><option>Side by Side</option></select></label>
 <label className="block text-sm">Original stack<select aria-label="Original SmartDrape stack" className={cls} value={r.stack} onChange={e=>update({stack:e.target.value as ReplacementRequest['stack']})}><option value="">Select stack</option>{replacementStacks.filter(v=>r.shadeType==='Single'||!['Center Opening','Center Stack (Motorized)'].includes(v)).map(v=><option key={v}>{v}</option>)}</select></label>
 <label className="block text-sm">Color arrangement<select aria-label="Replacement color arrangement" className={cls} value={r.colorMode} onChange={e=>update({colorMode:e.target.value as ReplacementRequest['colorMode'],secondColor:'',originalVaneCount:null})}><option>Single Color</option><option>Alternating</option></select></label>
 <label className="block text-sm">First fabric color<select aria-label="Replacement first fabric color" className={cls} value={r.firstColor} onChange={e=>update({firstColor:e.target.value,secondColor:''})}>{colorOptions()}</select></label>
 {r.colorMode==='Alternating'&&<><label className="block text-sm">Second fabric color<select aria-label="Replacement second fabric color" className={cls} value={r.secondColor} onChange={e=>update({secondColor:e.target.value})}>{colorOptions(first?.category)}</select></label>{r.style==='A'&&<label className="block text-sm">Original total vane count<input aria-label="Original total vane count" className={cls} type="number" min="1" step="1" value={r.originalVaneCount??''} onChange={e=>update({originalVaneCount:e.target.value===''?null:Number(e.target.value)})}/></label>}</>}
 <label className="block text-sm">Requested finished vane length (inches)<input aria-label="Requested finished vane length" className={cls} type="number" min="0" step="any" value={r.vaneLengthInches??''} onChange={e=>update({vaneLengthInches:e.target.value===''?null:Number(e.target.value)})}/></label>
 <p className="text-sm">Line quantity is the number of six-vane packs. Each pack: {composition.first.quantity} first, {composition.middle.reduce((n,v)=>n+v.quantity,0)} middle, {composition.last.quantity} last. Exact length and availability remain subject to original-order confirmation.</p>
 <button type="button" className={cls} disabled={!dirty} onClick={save}>Save replacement request</button><p role="status" className="text-sm">{dirty?'Unsaved replacement request':state.submitted?'Replacement request submitted':'No unsaved replacement request'}</p></section>;
}
