"use client";
import {normanSpecialtyNeedsCurvedTilt} from '@/lib/quote/norman-shutter-specialty-tilt';
import {NORMAN_SPECIALTY_FRAME_CONSTRUCTIONS,normanSpecialtyFrameConstruction} from '@/lib/quote/norman-shutter-specialty-frame';
import {NormanShutterSpecialtyGeometryOptions} from './NormanShutterSpecialtyGeometryOptions';
import {emptyNormanSpecialtyRecord,NORMAN_CONTINUOUS_ARCH_SHAPES,NORMAN_FRAME_IN_RAIL_SHAPES,normanSpecialtyFrames,normanSpecialtyIsSunburst,normanSpecialtyShapes,type NormanSpecialtyRecord} from '@/lib/quote/norman-shutter-specialty';
export function NormanShutterSpecialtyOptions({pricingOnly=false,value,programId,panelCount,tiltType,onChange,onPanelCount}:{pricingOnly?:boolean;value:NormanSpecialtyRecord|undefined;programId:string;panelCount:number;tiltType?:string|null;onChange:(r:NormanSpecialtyRecord)=>void;onPanelCount:(n:number)=>void}){
 const r=value??emptyNormanSpecialtyRecord(),update=(p:Partial<NormanSpecialtyRecord>)=>onChange({...r,...p});
 const cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const expectedConstruction=normanSpecialtyFrameConstruction(programId,r);
 const shapes=normanSpecialtyShapes(programId).filter(([code])=>!r.frameIncludeInRail||NORMAN_FRAME_IN_RAIL_SHAPES.includes(code));
 const allowsYes=(key:string)=>!(r.frameIncludeInRail&&['hinges','magnets'].includes(key))&&!(key==='hangStripBehind'&&['YS11','YS12','YS14'].includes(r.shapeCode))&&!(key==='frameIncludeInRail'&&r.shapeCode&&!NORMAN_FRAME_IN_RAIL_SHAPES.includes(r.shapeCode));
 return <section aria-label="Norman specialty construction" className="space-y-3">
  {shapes.length===0&&<p className="text-sm text-amber-900">This program's specialty assortment still needs source verification.</p>}
  <label className="block text-sm">Exact specialty shape<select className={cls} aria-label="Norman specialty shape" value={r.shapeCode} onChange={e=>update({shapeCode:e.target.value,archStyle:'',sunburstHubInches:null,geometry:undefined,frameConstruction:undefined,curvedTilt:undefined,hingeGeometry:undefined})}><option value="">Select</option>{shapes.map(([code,label])=><option value={code} key={code}>{code} · {label}</option>)}</select></label>
  {NORMAN_CONTINUOUS_ARCH_SHAPES.includes(r.shapeCode)&&<label className="block text-sm">Arch construction<select className={cls} aria-label="Norman specialty arch style" value={r.archStyle} onChange={e=>update({archStyle:e.target.value as NormanSpecialtyRecord['archStyle']})}><option value="">Select</option><option value="standard">Standard Louvered Arch</option>{programId!=='woodlore_aquashield'&&<option value="continuous">Continuous Arch</option>}</select></label>}
  {!pricingOnly&&normanSpecialtyNeedsCurvedTilt(programId,r.shapeCode,tiltType)&&<fieldset className="space-y-2"><legend className="text-sm font-semibold">Curved-section louver control</legend>
   <p className="text-sm">Invisible Tilt operates the straight section only. The curved horizontal louvers use a separate Standard Tilt rod on the back; the top louver is fixed.</p>
   <label className="block text-sm">Curved section control<select className={cls} aria-label="Norman specialty curved section control" value={r.curvedTilt?.control??''} onChange={e=>update({curvedTilt:{version:1,topLouverFixed:r.curvedTilt?.topLouverFixed??null,control:e.target.value as 'rear_standard'|''}})}><option value="">Confirm curved section control</option><option value="rear_standard">Separate rear Standard Tilt rod</option></select></label>
   <label className="flex gap-2 text-sm"><input aria-label="Norman specialty fixed top louver" type="checkbox" checked={r.curvedTilt?.topLouverFixed===true} onChange={e=>update({curvedTilt:{version:1,control:r.curvedTilt?.control??'',topLouverFixed:e.target.checked}})}/>Fixed top louver confirmed</label>
  </fieldset>}
  {([['frameIncludeInRail','Frame Include In Rail'],['hinges','Hinges required'],['magnets','Magnets required'],['hangStripBehind','Hang strip behind panel']] as const).filter(([key])=>!pricingOnly||key==='frameIncludeInRail').map(([key,label])=><label key={key} className="block text-sm">{label}<select className={cls} aria-label={`Norman specialty ${label}`} value={r[key]===null?'':String(r[key])} onChange={e=>update({[key]:e.target.value===''?null:e.target.value==='true',...(key==='frameIncludeInRail'?{frameType:''}:{}),...(key==='hinges'&&e.target.value!=='true'?{hingeGeometry:undefined}:{})})}><option value="">Select</option>{allowsYes(key)&&<option value="true">Yes</option>}<option value="false">No</option></select></label>)}
  {!pricingOnly&&r.hinges===true&&<fieldset className="space-y-2"><legend className="text-sm font-semibold">Measured specialty hinge geometry</legend>
   <label className="block text-sm">Hinge series<select className={cls} aria-label="Norman specialty hinge series" value={r.hingeGeometry?.series??''} onChange={e=>update({hingeGeometry:{version:1,smallestNetLegInches:r.hingeGeometry?.smallestNetLegInches??null,measurementReference:r.hingeGeometry?.measurementReference??'',series:e.target.value as 'direct_mount_3'|'standard_2_375'|''}})}><option value="">Select exact series</option><option value="direct_mount_3">Direct Mount 3-inch</option><option value="standard_2_375">2⅜-inch series — boundary confirmation required</option></select></label>
   {r.hingeGeometry&&<><label className="block text-sm">Smallest vertical stile straight height — net panel leg (inches)<input className={cls} aria-label="Norman specialty smallest net leg" type="number" step="0.0625" value={r.hingeGeometry.smallestNetLegInches??''} onChange={e=>update({hingeGeometry:{...r.hingeGeometry!,smallestNetLegInches:e.target.value===''?null:Number(e.target.value)}})}/></label><label className="block text-sm">Net-leg measurement reference<input className={cls} aria-label="Norman specialty hinge measurement reference" value={r.hingeGeometry.measurementReference} onChange={e=>update({hingeGeometry:{...r.hingeGeometry!,measurementReference:e.target.value}})}/></label></>}
   <p className="text-xs text-amber-900">Direct Mount 3-inch requires greater than 9¾ inches. Measure the actual smallest straight net stile; order leg height cannot substitute. RTL/T-post support, other hinge boundaries and final factory geometry remain held.</p>
  </fieldset>}
  <label className="block text-sm">Specialty frame<select className={cls} aria-label="Norman specialty frame" value={r.frameType} onChange={e=>update({frameType:e.target.value,frameConstruction:undefined})}><option value="">Select</option>{normanSpecialtyFrames(programId,r.frameIncludeInRail).map(f=><option key={f.code} value={f.label}>{f.label}</option>)}</select></label>
  {!pricingOnly&&r.shapeCode==='YS05'&&<label className="block text-sm">Louvered Arch has eyebrow curve<select className={cls} aria-label="Norman specialty eyebrow curve" value={r.frameConstruction?.eyebrowCurve==null?'':String(r.frameConstruction.eyebrowCurve)} onChange={e=>update({frameConstruction:{version:1,style:'',eyebrowCurve:e.target.value===''?null:e.target.value==='true'}})}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label>}
  {!pricingOnly&&(expectedConstruction?<label className="block text-sm">Frame manufacturing construction<select className={cls} aria-label="Norman specialty frame construction" value={r.frameConstruction?.style??''} onChange={e=>update({frameConstruction:{version:1,eyebrowCurve:r.frameConstruction?.eyebrowCurve??null,style:e.target.value as NonNullable<NormanSpecialtyRecord['frameConstruction']>['style']}})}><option value="">Confirm source construction</option>{NORMAN_SPECIALTY_FRAME_CONSTRUCTIONS.filter(([code])=>code===expectedConstruction).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label>:<p className="text-sm text-amber-900">Exact frame manufacturing construction remains unresolved for this combination.</p>)}
  <label className="block text-sm">Specialty frame sides<select className={cls} aria-label="Norman specialty frame sides" value={r.frameSides} onChange={e=>update({frameSides:e.target.value as NormanSpecialtyRecord['frameSides']})}><option value="">Select</option><option value="2">2 sides</option><option value="3">3 sides</option><option value="4">4 sides</option><option value="all">All around</option></select></label>
  {!pricingOnly&&normanSpecialtyIsSunburst(r.shapeCode)&&<label className="block text-sm">Largest actual sunburst hub size (inches)<input className={cls} aria-label="Norman specialty sunburst hub" type="number" min="0" max="12" step="0.0625" value={r.sunburstHubInches??''} onChange={e=>update({sunburstHubInches:e.target.value===''?null:Number(e.target.value)})}/></label>}
  {!pricingOnly&&r.archStyle==='continuous'&&<label className="block text-sm">Continuous arch stile width (inches)<input className={cls} aria-label="Norman specialty stile width" type="number" min="0" step="0.125" value={r.stileWidthInches??''} onChange={e=>update({stileWidthInches:e.target.value===''?null:Number(e.target.value)})}/></label>}
  <label className="block text-sm">Finished specialty panel count<select className={cls} aria-label="Norman specialty panel count" value={panelCount} onChange={e=>onPanelCount(Number(e.target.value))}><option value="0">Select</option>{Array.from({length:16},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label>
  {!pricingOnly&&r.shapeCode&&<NormanShutterSpecialtyGeometryOptions value={r.geometry} shapeCode={r.shapeCode} onChange={geometry=>update({geometry})}/>}
  {!pricingOnly&&<p className="text-sm text-amber-900">Frame Include In Rail is fixed, without hinges or magnets. Shape dimensions, templates, hardware and pricing remain under review. Save with panel construction.</p>}
 </section>;
}
