"use client";
import {emptyNormanSpecialtyRecord,NORMAN_CONTINUOUS_ARCH_SHAPES,NORMAN_FRAME_IN_RAIL_SHAPES,normanSpecialtyFrames,normanSpecialtyIsSunburst,normanSpecialtyShapes,type NormanSpecialtyRecord} from '@/lib/quote/norman-shutter-specialty';
export function NormanShutterSpecialtyOptions({value,programId,panelCount,onChange,onPanelCount}:{value:NormanSpecialtyRecord|undefined;programId:string;panelCount:number;onChange:(r:NormanSpecialtyRecord)=>void;onPanelCount:(n:number)=>void}){
 const r=value??emptyNormanSpecialtyRecord(),update=(p:Partial<NormanSpecialtyRecord>)=>onChange({...r,...p});
 const cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 const shapes=normanSpecialtyShapes(programId).filter(([code])=>!r.frameIncludeInRail||NORMAN_FRAME_IN_RAIL_SHAPES.includes(code));
 const allowsYes=(key:string)=>!(r.frameIncludeInRail&&['hinges','magnets'].includes(key))&&!(key==='hangStripBehind'&&['YS11','YS12','YS14'].includes(r.shapeCode))&&!(key==='frameIncludeInRail'&&r.shapeCode&&!NORMAN_FRAME_IN_RAIL_SHAPES.includes(r.shapeCode));
 return <section aria-label="Norman specialty construction" className="space-y-3">
  {shapes.length===0&&<p className="text-sm text-amber-900">This program's specialty assortment still needs source verification.</p>}
  <label className="block text-sm">Exact specialty shape<select className={cls} aria-label="Norman specialty shape" value={r.shapeCode} onChange={e=>update({shapeCode:e.target.value,archStyle:'',sunburstHubInches:null})}><option value="">Select</option>{shapes.map(([code,label])=><option value={code} key={code}>{code} · {label}</option>)}</select></label>
  {NORMAN_CONTINUOUS_ARCH_SHAPES.includes(r.shapeCode)&&<label className="block text-sm">Arch construction<select className={cls} aria-label="Norman specialty arch style" value={r.archStyle} onChange={e=>update({archStyle:e.target.value as NormanSpecialtyRecord['archStyle']})}><option value="">Select</option><option value="standard">Standard Louvered Arch</option>{programId!=='woodlore_aquashield'&&<option value="continuous">Continuous Arch</option>}</select></label>}
  {([['frameIncludeInRail','Frame Include In Rail'],['hinges','Hinges required'],['magnets','Magnets required'],['hangStripBehind','Hang strip behind panel']] as const).map(([key,label])=><label key={key} className="block text-sm">{label}<select className={cls} aria-label={`Norman specialty ${label}`} value={r[key]===null?'':String(r[key])} onChange={e=>update({[key]:e.target.value===''?null:e.target.value==='true',...(key==='frameIncludeInRail'?{frameType:''}:{})})}><option value="">Select</option>{allowsYes(key)&&<option value="true">Yes</option>}<option value="false">No</option></select></label>)}
  <label className="block text-sm">Specialty frame<select className={cls} aria-label="Norman specialty frame" value={r.frameType} onChange={e=>update({frameType:e.target.value})}><option value="">Select</option>{normanSpecialtyFrames(programId,r.frameIncludeInRail).map(f=><option key={f.code} value={f.label}>{f.label}</option>)}</select></label>
  <label className="block text-sm">Specialty frame sides<select className={cls} aria-label="Norman specialty frame sides" value={r.frameSides} onChange={e=>update({frameSides:e.target.value as NormanSpecialtyRecord['frameSides']})}><option value="">Select</option><option value="2">2 sides</option><option value="3">3 sides</option><option value="4">4 sides</option><option value="all">All around</option></select></label>
  {normanSpecialtyIsSunburst(r.shapeCode)&&<label className="block text-sm">Largest actual sunburst hub size (inches)<input className={cls} aria-label="Norman specialty sunburst hub" type="number" min="0" max="12" step="0.0625" value={r.sunburstHubInches??''} onChange={e=>update({sunburstHubInches:e.target.value===''?null:Number(e.target.value)})}/></label>}
  {r.archStyle==='continuous'&&<label className="block text-sm">Continuous arch stile width (inches)<input className={cls} aria-label="Norman specialty stile width" type="number" min="0" step="0.125" value={r.stileWidthInches??''} onChange={e=>update({stileWidthInches:e.target.value===''?null:Number(e.target.value)})}/></label>}
  <label className="block text-sm">Finished specialty panel count<select className={cls} aria-label="Norman specialty panel count" value={panelCount} onChange={e=>onPanelCount(Number(e.target.value))}><option value="0">Select</option>{Array.from({length:16},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label>
  <p className="text-sm text-amber-900">Frame Include In Rail is fixed, without hinges or magnets. Shape dimensions, templates, hardware and pricing remain under review. Save with panel construction.</p>
 </section>;
}
