'use client';
import {useEffect,useState} from 'react';
import type {SalesQuoteDesign} from '@mts/types/quote';
import {ROLLER_POLE_KEY as KEY,ROLLER_POLES,emptyRollerPole,parseRollerPole,type RollerPole} from '@/lib/quote/norman-roller-poles';
export function NormanRollerPoleOptions({design,onUpdateFields}:{design:SalesQuoteDesign|undefined;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const options=(design?.options_json??{}) as Record<string,unknown>,incoming=parseRollerPole(options[KEY])??emptyRollerPole(),serialized=JSON.stringify(incoming),key=design?.id??'';
 const [state,setState]=useState(()=>({key,base:serialized,draft:incoming,submitted:null as string|null}));
 useEffect(()=>setState(s=>{if(s.key!==key||JSON.stringify(s.draft)===serialized)return {key,base:serialized,draft:JSON.parse(serialized),submitted:null};if(s.submitted===serialized)return {...s,base:serialized,submitted:null};return s.submitted||JSON.stringify(s.draft)!==s.base?s:{key,base:serialized,draft:JSON.parse(serialized),submitted:null};}),[key,serialized]);
 const r=state.draft,dirty=JSON.stringify(r)!==(state.submitted??state.base),edit=(p:Partial<RollerPole>)=>setState(s=>({...s,draft:{...s.draft,...p}})),cls='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
 if(!/cordless/i.test(String(design?.lift_system??options.lift_system??'')))return options[KEY]?<button type="button" onClick={()=>onUpdateFields({options_json:{...options,[KEY]:null}})}>Clear Roller pole selection</button>:null;
 return <section className="space-y-3 rounded-lg border border-slate-200 p-3"><h3 className="font-semibold">Roller poles and attachments</h3><p className="text-sm">One complimentary fiberglass pole is included per order: 30 inches when every eligible shade is at most 96 inches high; otherwise 58 inches. Extra quantities below exclude that included pole.</p><label className="block text-sm">Additional pole or attachment<select className={cls} aria-label="Roller additional pole" value={r.kind} onChange={e=>edit({kind:e.target.value as RollerPole['kind'],quantityPerAssembly:e.target.value==='None'?0:1})}>{ROLLER_POLES.map(v=><option key={v}>{v}</option>)}</select></label>{r.kind!=='None'&&<label className="block text-sm">Extra quantity per shade assembly<input className={cls} type="number" min="1" step="1" aria-label="Roller extra pole quantity per assembly" value={r.quantityPerAssembly} onChange={e=>edit({quantityPerAssembly:Number(e.target.value)})}/></label>}<p className="text-xs">Maximum one extra pole or attachment per physical shade. The black attachment fits screw-tip poles; it is not a replacement for the fixed-head cordless pole. All listed poles and attachments are unavailable with LightGuard360.</p><button type="button" className={cls} disabled={!dirty} onClick={()=>{setState(s=>({...s,submitted:JSON.stringify(s.draft)}));onUpdateFields({options_json:{...options,[KEY]:r}});}}>Save Roller pole selection</button><p role="status">{dirty?'Unsaved Roller pole selection':state.submitted?'Roller pole selection submitted':'No unsaved Roller pole selection'}</p></section>;
}
