'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeftRight, Banknote, CreditCard, NotebookPen, Send, Smartphone, Wallet } from 'lucide-react';
import { hubRecord, paymentMethods, paymentPurposes, type HubMethod, type HubPurpose, type HubTransaction } from '@/lib/crm/payment-hub';

const icons={credit_card:CreditCard,apple_pay:Smartphone,check:NotebookPen,cash:Banknote,zelle:ArrowLeftRight,venmo:Send,other:Wallet};
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'America/Los_Angeles'});
const money=(cents:number,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100);
const displayDate=(v:string)=>!v?'Date unavailable':new Date(v.length===10?`${v}T12:00:00`:v).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'medium',...(v.length===10?{}:{timeStyle:'short'})});
const statusLabel=(s:string)=>({ADJUSTMENT:'Ledger correction',UNVERIFIED:'Clearance unverified',RECEIVED:'Received · not deposited',DEPOSITED:'Deposited · awaiting clearance',CLEARED:'Cleared',RETURNED:'Returned · credit removed',RECORDED:'Recorded',COMPLETED:'Completed',APPROVED:'Approved',PENDING:'Pending',FAILED:'Failed',CANCELED:'Canceled'}[s]||s);
export function PaymentMethodTag({method}:{method:HubMethod}) { const Icon=icons[method]; return <span className="hub-method" data-method={method}><Icon size={14} aria-hidden="true"/>{method==='check'?'Check':paymentMethods[method]}</span>; }

export function PaymentHubFeed({rows,targets,token,canReview,query,onSquare,onReload,onOpenChange}:{
  rows:HubTransaction[]; targets:{key:string;id:string;customer_name:string;total?:number}[];token:string;canReview:boolean;query:string;
  onSquare:(id:string)=>void;onReload:()=>Promise<void>;onOpenChange:(open:boolean)=>void;
}) {
  const [method,setMethod]=useState<HubMethod|'all'>('all'),[purpose,setPurpose]=useState<HubPurpose|'all'>('all');
  const [selected,setSelected]=useState<HubTransaction|null>(null),[recording,setRecording]=useState(false);
  const [saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [receipt,setReceipt]=useState({requestId:'',target:'',method:'check',purpose:'',amount:'',receivedAt:today(),reference:'',payer:'',bank:'',notes:''});
  const [step,setStep]=useState({eventId:'',status:'',date:today(),evidence:''});
  const formRef=useRef<HTMLElement>(null), savingRef=useRef(false);
  useEffect(()=>{onOpenChange(recording||Boolean(selected));return()=>onOpenChange(false);},[recording,selected,onOpenChange]);
  useEffect(()=>{if(recording||selected) formRef.current?.focus();},[recording,selected]);
  const filtered=useMemo(()=>rows.filter(r=>(method==='all'||r.method===method)&&(purpose==='all'||r.purposes.includes(purpose))&&`${r.customer} ${r.id} ${r.reference} ${r.status} ${r.detail} ${r.ledger?.payment_label||''} ${r.purposes.map(p=>paymentPurposes[p]).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[rows,method,purpose,query]);
  async function save(body:Record<string,unknown>) {
    if(savingRef.current)return;
    savingRef.current=true;setSaving(true);setError('');setNotice('');
    try {
      const response=await fetch('/api/crm/payment-hub/',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
      const result=await response.json();
      if(!response.ok)throw new Error(result.message||'Payment could not be saved.');
      setNotice(result.reused?'This receipt or update was already saved. No duplicate was added.':'Saved to the customer ledger.');
      setRecording(false);setSelected(null);await onReload();
    } catch(e){setError(e instanceof Error?e.message:'Payment could not be saved. Retry this same form.');}
    finally{savingRef.current=false;setSaving(false);}
  }
  function exportRows(){
    const cell=(v:unknown)=>{const s=String(v??'');return `"${(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')}"`;};
    const csv=[['Payment ID','Customer','Method','Purpose','Received date','Date basis','Amount','Currency','CRM credit','Status','Reference'],...filtered.map(r=>[r.id,r.customer,paymentMethods[r.method],r.purposes.map(p=>paymentPurposes[p]).join(' / '),r.occurredAt,r.dateIsRecorded?'Recorded date; receipt date missing':'Received',r.amountCents/100,r.currency,r.creditCents/100,statusLabel(r.status),r.reference])].map(r=>r.map(cell).join(',')).join('\r\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`805-payment-hub-${today()}.csv`;a.click();URL.revokeObjectURL(url);
  }
  const check=hubRecord(hubRecord(selected?.ledger?.meta.payment_hub).check);
  const options:Record<string,string[]>={UNVERIFIED:['RECEIVED','DEPOSITED','CLEARED','RETURNED'],RECEIVED:['DEPOSITED','RETURNED'],DEPOSITED:['CLEARED','RETURNED'],CLEARED:['RETURNED']};
  return <>
    <div className="hub-filters" role="group" aria-label="Payment method filters"><button aria-pressed={method==='all'} onClick={()=>setMethod('all')}>All payments <span>{rows.length}</span></button>{(Object.keys(paymentMethods) as HubMethod[]).map(m=><button key={m} aria-pressed={method===m} onClick={()=>setMethod(m)}><PaymentMethodTag method={m}/><span>{rows.filter(r=>r.method===m).length}</span></button>)}</div>
    <div className="hub-toolbar"><label>Payment purpose<select value={purpose} onChange={e=>setPurpose(e.target.value as HubPurpose|'all')}><option value="all">All purposes</option>{Object.entries(paymentPurposes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="square-actions">{canReview&&<button className="square-primary" disabled={saving} onClick={()=>{setSelected(null);setError('');setRecording(true);setReceipt({requestId:crypto.randomUUID(),target:'',method:'check',purpose:'',amount:'',receivedAt:today(),reference:'',payer:'',bank:'',notes:''});}}>Record payment</button>}<button onClick={exportRows}>Export these payments</button></div></div>
    {error&&<p className="square-alert" role="alert">{error}</p>}{notice&&<p className="square-notice" role="status">{notice}</p>}
    <p className="hub-count" role="status">{filtered.length} {filtered.length===1?'payment':'payments'} · Newest first{method==='check'?' · Receiving a check does not confirm bank clearance.':''}</p>
    <div className="square-table-scroll"><table className="hub-transactions"><thead><tr><th>Customer / received</th><th>Method / purpose</th><th>Amount</th><th>Status</th><th><span className="square-sr-only">Details</span></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.customer}</strong><small>{displayDate(r.occurredAt)}{r.dateIsRecorded?' · recorded date':''}</small></td><td><div className="hub-tags"><PaymentMethodTag method={r.method}/>{r.purposes.map(p=><span key={p} className="hub-purpose" data-purpose={p}>{paymentPurposes[p]}</span>)}</div></td><td className="square-money">{money(r.amountCents,r.currency)}{r.squareId&&<small>{r.feeCents===null?'Fee awaiting Square':`${money(r.feeCents,r.currency)} fee`}</small>}</td><td><span className="square-status" data-status={r.status}>{statusLabel(r.status)}</span><small>{r.detail}</small></td><td><button disabled={saving} aria-label={`View payment ${r.squareId||r.ledger?.id}`} onClick={()=>{if(r.squareId){setRecording(false);setSelected(null);onSquare(r.squareId);}else{setRecording(false);setSelected(r);setError('');setStep({eventId:crypto.randomUUID(),status:'',date:today(),evidence:''});}}}>View details ↗</button></td></tr>)}</tbody></table>{!filtered.length&&<p>No payments match these filters.</p>}</div>
    {recording&&<section className="square-review" ref={formRef} tabIndex={-1} aria-label="Record received payment"><div className="square-actions"><h2>Record a received payment</h2><button disabled={saving} onClick={()=>setRecording(false)}>Close</button></div><p>Record money you have already received. Square and Apple Pay arrive through Square automatically.</p><form onSubmit={e=>{e.preventDefault();const [targetKind,targetId]=receipt.target.split(':');const amountCents=/^\d+(?:\.\d{1,2})?$/.test(receipt.amount)?Math.round(Number(receipt.amount)*100):NaN;void save({...receipt,action:'record',targetKind,targetId,amountCents});}}>
      <label>Customer / job<select required value={receipt.target} onChange={e=>setReceipt({...receipt,target:e.target.value})}><option value="">Choose the exact job</option>{targets.map(t=><option key={t.key} value={t.key}>{t.customer_name} · {money(Number(t.total)*100)} · {t.key.startsWith('quote:')?'Quote':'Ledger'} {t.id.slice(0,8)}</option>)}</select></label>
      <div className="hub-form-grid"><label>Payment method<select value={receipt.method} onChange={e=>setReceipt({...receipt,method:e.target.value,reference:''})}>{['check','cash','zelle','venmo','other'].map(m=><option key={m} value={m}>{paymentMethods[m as HubMethod]}</option>)}</select></label><label>What is this payment for?<select required value={receipt.purpose} onChange={e=>setReceipt({...receipt,purpose:e.target.value})}><option value="">Choose what this covers</option>{Object.entries(paymentPurposes).filter(([p])=>p!=='unspecified').map(([p,label])=><option key={p} value={p}>{label}</option>)}</select></label><label>Amount received ($)<input required type="number" min="0.01" step="0.01" value={receipt.amount} onChange={e=>setReceipt({...receipt,amount:e.target.value})}/></label><label>Date received<input required type="date" max={today()} value={receipt.receivedAt} onChange={e=>setReceipt({...receipt,receivedAt:e.target.value})}/></label></div>
      <label>{receipt.method==='check'?'Check number':'Receipt / transaction reference'}<input required={receipt.method!=='cash'} maxLength={300} value={receipt.reference} onChange={e=>setReceipt({...receipt,reference:e.target.value})}/></label>
      {receipt.method==='check'&&<><div className="hub-form-grid"><label>Name printed on check<input required maxLength={300} value={receipt.payer} onChange={e=>setReceipt({...receipt,payer:e.target.value})}/></label><label>Issuing bank name<input required maxLength={300} value={receipt.bank} onChange={e=>setReceipt({...receipt,bank:e.target.value})} placeholder="Bank name only"/></label></div><p>This credits the job as received. Mark the check deposited and cleared when you have bank evidence.</p></>}
      <label>Notes<textarea maxLength={2000} value={receipt.notes} onChange={e=>setReceipt({...receipt,notes:e.target.value})}/></label><button className="square-primary" disabled={saving} type="submit">{saving?'Saving…':'Save received payment'}</button>
    </form></section>}
    {selected?.ledger&&<section ref={formRef} tabIndex={-1} className="square-review" aria-label="CRM payment details"><div className="square-actions"><h2>{selected.customer}</h2><button disabled={saving} onClick={()=>setSelected(null)}>Close</button></div><div className="hub-tags"><PaymentMethodTag method={selected.method}/>{selected.purposes.map(p=><span className="hub-purpose" key={p}>{paymentPurposes[p]}</span>)}</div><p>{money(selected.amountCents)} · {statusLabel(selected.status)} · Customer credit {money(selected.creditCents)}</p><p>{selected.reference||selected.ledger.payment_label}</p><small>Payment record {selected.ledger.id}</small>
      {selected.method==='check'&&<><h3>Check history</h3><p>{check.number?`Check #${String(check.number)} · ${String(check.payer)} · ${String(check.bank)}`:'Historical check — receipt and clearance details have not been verified.'}</p>{Array.isArray(check.history)&&check.history.map((h:unknown)=>{const event=hubRecord(h);return <p key={String(event.id)}>{displayDate(String(event.date))} · {statusLabel(String(event.status))}<small>{String(event.evidence)} · {String(event.actor)}</small></p>;})}
        {canReview&&(options[selected.status]?.length||0)>0&&<form onSubmit={e=>{e.preventDefault();void save({action:'check',paymentId:selected.ledger!.id,version:selected.ledger!.updated_at,...step});}}><label>Update check status<select required value={step.status} onChange={e=>setStep({...step,status:e.target.value})}><option value="">Choose the confirmed step</option>{options[selected.status].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Date of this step<input required type="date" max={today()} value={step.date} onChange={e=>setStep({...step,date:e.target.value})}/></label><label>Bank / receipt evidence<textarea required minLength={8} maxLength={2000} value={step.evidence} onChange={e=>setStep({...step,evidence:e.target.value})} placeholder="Deposit reference, statement date, or bank return notice"/></label>{step.status==='RETURNED'&&<p className="square-alert">This removes {money(selected.creditCents)} from the customer’s payment credit and reopens that amount on their balance. The original check and history stay visible.</p>}<button disabled={saving||!step.status}>{saving?'Saving…':step.status==='RETURNED'?`Confirm returned check — remove ${money(selected.creditCents)} credit`:'Save check status'}</button></form>}
      </>}
    </section>}
  </>;
}
