'use client';
import { sundanceCellularAccessories, sundanceCellularAccessoryKey, sundanceCellularOptionEvidence } from '@/lib/quote/sundance/cellular-option-schedules';
export function SundanceCellularAccessories({ options, widthInches, onChange }: { options: Record<string, unknown>; widthInches: number; onChange: (key: string, value: string) => void }) {
  const system = String(options.sundance_cellular_system ?? '');
  const choices = sundanceCellularAccessories.filter(a => (a.systems as readonly string[]).includes(system));
  const evidence = sundanceCellularOptionEvidence(options, widthInches);
  return <>
    {choices.length > 0 && <div className="space-y-2"><p className="text-sm font-medium">Motor accessories allocated to this line</p>{choices.map(accessory => <label className="block text-sm" key={accessory.key}>{accessory.label}<input type="number" min="0" step="1" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2" aria-label={`Sundance cellular ${accessory.label} quantity`} value={String(options[sundanceCellularAccessoryKey(accessory.key)] ?? '')} onChange={e => onChange(sundanceCellularAccessoryKey(accessory.key), e.target.value)} /></label>)}<p className="text-sm text-amber-900">Allocate shared controls and power accessories once. Required quantities, motor compatibility and order-wide sharing need review before approving the manual price.</p></div>}
    <details className="text-sm"><summary className="cursor-pointer">Cut-outs and extension poles</summary>{[['sundance_cellular_cutout_qty','Cut-outs'],['sundance_cellular_pole_short_qty','3–5-foot extension poles'],['sundance_cellular_pole_long_qty','5–9-foot extension poles']].map(([key,label])=><label key={key} className="block text-sm">{label}<input type="number" min="0" step="1" aria-label={`Sundance cellular ${label} quantity`} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2" value={String(options[key]??'')} onChange={e=>onChange(key,e.target.value)}/></label>)}{Number(options.sundance_cellular_cutout_qty)>0&&<label className="block text-sm">Cut-out dimensions and template reference<textarea aria-label="Sundance cellular cut-out details" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2" value={String(options.sundance_cellular_cutout_details??'')} onChange={e=>onChange('sundance_cellular_cutout_details',e.target.value)}/></label>}<p className="text-amber-900">Cut-out geometry and pole reach/operating compatibility require confirmation. Keep manufacturer template details with the quote.</p></details>
    <details className="text-sm"><summary className="cursor-pointer">Published cellular option evidence</summary><ul>{evidence.entries.map((e,index) => <li key={`${e.label}-${index}`}>{e.label}: {e.quantity} × ${e.unitPrice.toFixed(2)} {e.basis} (PDF {e.page}{e.matchedWidth ? `, width band ${e.matchedWidth} inches` : ''})</li>)}</ul><p>Retail options subtotal: ${evidence.retailSubtotal.toFixed(2)}. Net options subtotal: ${evidence.netSubtotal.toFixed(2)}. These are separate source amounts, not a customer price. Base fabrics, account terms, tax and unresolved order charges are excluded.</p>{evidence.unresolved.map(message => <p className="text-amber-900" key={message}>{message}</p>)}</details>
  </>;
}
