'use client';
import { nonNormanQuoteIssues } from "@/lib/quote/non-norman-ordering-only";
import {SundanceWaldenTwinOptions} from './SundanceWaldenTwinOptions';
import type {SalesQuoteDesign} from '@mts/types/quote';
import type {SelectionRecord} from '@/lib/quote-v2/core';
import {sundanceWaldenControls,validateSundanceWaldenConfiguration} from '@/lib/quote/sundance/walden-configuration';
import {sundanceWaldenAccessories,sundanceWaldenAccessoryKey,sundanceWaldenControlPatch,sundanceWaldenStylePatch,sundanceWaldenOptionEvidence} from '@/lib/quote/sundance/walden-option-schedules';
export function SundanceWaldenConfiguration({productId,options,widthInches,heightInches,onUpdateFields, pricingOnly = true}:{ pricingOnly?: boolean; productId:string;options:Record<string,unknown>;widthInches:number;heightInches:number;onUpdateFields:(fields:Partial<SalesQuoteDesign>)=>void}){
 const classes='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm',p=productId,valanceOnly=options.sundance_walden_style==='Valance Only',control=String(options.sundance_walden_control??'');
 const field=(key:string,value:string)=>onUpdateFields(key==='sundance_walden_style'?{options_json:sundanceWaldenStylePatch(options,value)}:{...(key==='mount_type'?{mount_type:value}:{}),options_json:{...options,[key]:value||null}});
 const select=(key:string,label:string,values:string[])=><label className="block text-sm">{label}<select aria-label={`Sundance Walden ${label}`} className={classes} value={String(options[key]??'')} onChange={e=>field(key,e.target.value)}><option value="">Select</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
 const number=(key:string,label:string,step='1')=><label className="block text-sm">{label}<input aria-label={`Sundance Walden ${label}`} type="number" min="0" step={step} className={classes} value={String(options[key]??'')} onChange={e=>field(key,e.target.value)}/></label>;
 const issues=nonNormanQuoteIssues(validateSundanceWaldenConfiguration({productId:p,programId:String(options.catalog_program_id??''),widthInches,heightInches,configuration:options as SelectionRecord}), pricingOnly);
 const evidence=sundanceWaldenOptionEvidence(p,options,widthInches,heightInches);
 return <>
 {select('sundance_walden_style','Style',['Standard','Waterfall','Valance Only'])}
 {!valanceOnly&&<label className="block text-sm">Operating system<select aria-label="Sundance Walden operating system" className={classes} value={control} onChange={e=>onUpdateFields({options_json:sundanceWaldenControlPatch(options,e.target.value)})}><option value="">Select system</option>{sundanceWaldenControls(p).map(v=><option key={v}>{v}</option>)}</select></label>}
 {!valanceOnly&&control==='Pro Wand'&&select('sundance_walden_wand_length','White Pro Wand length',['24','36','48','60'])}
 {!valanceOnly&&control==='Clutch and Loop'&&select('sundance_walden_chain','Chain',p==='sundance_walden_select'?['Nickel-plated standard','Stainless Steel']:['Metal standard'])}
 {!valanceOnly&&options.sundance_walden_style==='Waterfall'&&<>{select('sundance_walden_back_valance','Back valance',['None','Shade fabric',...(options.catalog_sundance_liner_grid_id?['Liner fabric']:[])])}{select('sundance_walden_interior_valance','Interior valance',['Standard when unlined or light-filtering','Requested interior valance'])}</>}
 {select('mount_type','Mount',['Inside','Outside'])}
 {!pricingOnly&&!valanceOnly&&options.mount_type==='Inside'&&<>{select('sundance_walden_flush','Flush mount',['No','Yes'])}{number('sundance_walden_depth','Mounting depth in inches','0.0625')}</>}
 {select('sundance_walden_returns','Returns',['None','Standard','Extended'])}
 {options.sundance_walden_returns&&options.sundance_walden_returns!=='None'&&select('sundance_walden_return_material','Return material',['Shade fabric','Edge binding fabric'])}
 {select('sundance_walden_assembly','Assembly',['Single','Two on one','Three on one'])}
 {!valanceOnly&&<>{select('sundance_walden_hold_down','Hold-down brackets',['No','Yes'])}{number('sundance_walden_spacers','Spacer blocks per bracket')}{number('sundance_walden_cutout_qty','Cut-out quantity')}{!pricingOnly&&Number(options.sundance_walden_cutout_qty)>0&&<label className="block text-sm">Cut-out dimensions and template reference<textarea aria-label="Sundance Walden cut-out details" className={classes} value={String(options.sundance_walden_cutout_details??'')} onChange={e=>field('sundance_walden_cutout_details',e.target.value)}/></label>}</>}
 {valanceOnly&&select('sundance_walden_valance_headrail','Valance headrail depth (inches)',['Loose','1','1.5','2.5','3.5','5'])}
 {!valanceOnly&&<details className="text-sm"><summary className="cursor-pointer">Motor accessories allocated to this line</summary>{sundanceWaldenAccessories.filter(a=>a.controls.includes(control)).map(a=><div key={a.key}>{number(sundanceWaldenAccessoryKey(a.key),`${a.label} quantity`)}</div>)}<p>Chargers are separate. Allocate shared remotes, hubs and chargers once per order; confirm the complete quantity and compatibility.</p></details>}
 <p className="text-sm">Standard shade: included 6-inch lined front valance. Waterfall: no front valance; interior/back valances follow liner and control requirements. TDBU includes lined front and back valances.{!pricingOnly && <> Inside factory width deduction is ⅜ inch; keep the opening dimensions. Clutch-adjacent and Pro Wand fabric offsets depend on returns and do not change the ordered grid width. Twin and common-headrail shades require independent components.</>}</p>
 {!pricingOnly&&!valanceOnly&&<details className="text-sm"><summary>Published Walden installation references</summary><p>Approximate raised stack: 8–10 inches for all lengths. First fold starts 3½ inches above the bottom bar; subsequent rings are 7 inches apart. Brackets are 1½ inches high ×1¾ deep. Middle supports are supplied for shades over41 inches wide.</p><p>Inside mounting: overall factory width deduction is⅜ inch. With returns, the headrail is an additional½ inch narrower than the finished fabric/valance to fit the returns. Outside mounting: fabric has no deduction; standard-shade front valance is½ inch wider than ordered width. Waterfall with returns has a headrail½ inch narrower. Standard returns match headrail depth; outside extended returns add½ inch depth. These are fabrication references; retain the ordered opening and measured component sizes.</p><p>Published flush depths include the standard bracket and vary slightly with fabric thickness. Mixed-control twin clearances require factory confirmation.</p></details>}
 <details className="text-sm"><summary className="cursor-pointer">Published Walden option evidence</summary>{evidence.entries.map(e=><p key={e.label}>{e.label}: ${e.retail.toFixed(2)} source retail (PDF {e.page})</p>)}<p>Selected source retail evidence: ${evidence.sourceRetailSubtotal.toFixed(2)}. This is not a customer price. Shade base, attached liner/binding grids, shared component allocations, account factors and freight remain separate.</p>{evidence.unresolved.map(message=><p key={message} className="text-amber-900">{message}</p>)}</details>
 <SundanceWaldenTwinOptions productId={productId} options={options} widthInches={widthInches} heightInches={heightInches} onUpdateFields={onUpdateFields} />
 {issues.length>0&&<div role="alert" className="text-sm text-amber-900">{issues.map(i=><p key={i.ruleId}>{i.explanation}</p>)}</div>}
 </>;
}
