"use client";
import {SundanceAccessoryOptions} from "./SundanceAccessoryOptions";
import type { SelectionRecord } from "@/lib/quote-v2/core";
import { sundanceSheerviewFlatFinishes, sundanceSheerviewHeadrailDepths, sundanceSheerviewControls, sundanceSheerviewHeadrails, sundanceSheerviewCordOptions, sundanceSheerviewControlPatch, sundanceSheerviewHeadrailPatch, validateSundanceSheerviewConfiguration } from "@/lib/quote/sundance/sheerview-configuration";
import type { SalesQuoteDesign } from "@mts/types/quote";
import { sundanceSheerviewColors, sundanceSheerviewColorMatchesContext, sundanceSheerviewColorPatch, sundanceSheerviewFilterPatch, sundanceSheerviewSource } from "@/lib/quote/sundance/sheerview-assortment";

export function SundanceSheerviewOptions({options,onUpdateFields,widthInches=0,heightInches=0}: {
  options: Record<string,unknown>; widthInches?:number; heightInches?:number; onUpdateFields: (fields: Partial<SalesQuoteDesign>) => void;
}) {
  const rows=sundanceSheerviewColors.filter(row=>sundanceSheerviewColorMatchesContext(row,options));
  const selected=sundanceSheerviewSource.rows.find(row=>row.id===options.fabric_color_id);
  const classes="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
  const filter=(field:"vane_size"|"light_control",value:string)=>onUpdateFields({fabric:null,options_json:sundanceSheerviewFilterPatch(options,field,value)});
  const issues=validateSundanceSheerviewConfiguration({widthInches,heightInches,programId:String(options.catalog_program_id??""),configuration:options as SelectionRecord});
  return <>
    <label className="block text-sm">Vane size<select aria-label="Sundance SheerView vane size" className={classes} value={String(options.vane_size??"")} onChange={e=>filter("vane_size",e.target.value)}><option value="">All sizes</option>{["2","2.5","3"].map(size=><option key={size} value={size}>{size}-inch</option>)}</select></label>
    <label className="block text-sm">Light control<select aria-label="Sundance SheerView light control" className={classes} value={String(options.light_control??"")} onChange={e=>filter("light_control",e.target.value)}><option value="">All light controls</option><option>Light Filtering</option><option>Room Darkening</option></select></label>
    <label className="block text-sm">Fabric and color<select aria-label="Sundance SheerView fabric and color" className={classes} value={String(options.fabric_color_id??"")} onChange={e=>{
      const row=rows.find(row=>row.id===e.target.value);const patch=sundanceSheerviewColorPatch(options,e.target.value);
      if(row&&patch)onUpdateFields({fabric:`${row.colorCode} · ${row.colorName}`,options_json:patch});
    }}><option value="">Select fabric and color</option>{rows.map(row=><option key={row.id} value={row.id}>{row.colorCode} · {row.colorName} · {row.collection} · {row.fabricType}</option>)}</select></label>
    <label className="block text-sm">Control<select aria-label="Sundance SheerView control" className={classes} value={String(options.sundance_sheerview_control??"")} onChange={e=>onUpdateFields({options_json:sundanceSheerviewControlPatch(options,e.target.value)})}><option value="">Select control</option>{sundanceSheerviewControls.map(control=><option key={control}>{control}</option>)}</select></label>
    <label className="block text-sm">Headrail<select aria-label="Sundance SheerView headrail" className={classes} value={String(options.sundance_sheerview_headrail??"")} onChange={e=>{const patch=sundanceSheerviewHeadrailPatch(options,e.target.value);if(patch)onUpdateFields({options_json:patch});}}><option value="">Select headrail</option>{sundanceSheerviewHeadrails.filter(rail=>rail!=="No Drill"||options.sundance_sheerview_control==="Cordless").map(rail=><option key={rail}>{rail}</option>)}</select></label>
    {options.sundance_sheerview_headrail==="Flat Square"&&<label className="block text-sm">Painted headrail finish<select aria-label="Sundance SheerView painted headrail finish" className={classes} value={String(options.sundance_sheerview_headrail_finish??"")} onChange={e=>onUpdateFields({options_json:{...options,sundance_sheerview_headrail_finish:e.target.value||null}})}><option value="">Select finish</option>{sundanceSheerviewFlatFinishes.map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select></label>}
    <label className="block text-sm">Mount<select aria-label="Sundance SheerView mount" className={classes} value={String(options.mount_type??"")} onChange={e=>onUpdateFields({mount_type:e.target.value,options_json:{...options,mount_type:e.target.value,sundance_sheerview_mount_depth:null,sundance_sheerview_recess:null}})}><option value="">Select mount</option><option>Inside</option><option>Outside</option></select></label>
    {options.mount_type==="Inside"&&<><label className="block text-sm">Available mounting depth (inches)<input aria-label="Sundance SheerView mount depth" className={classes} type="number" step="0.0625" value={String(options.sundance_sheerview_mount_depth??"")} onChange={e=>onUpdateFields({options_json:{...options,sundance_sheerview_mount_depth:e.target.value||null}})}/></label><label className="block text-sm">Recess<select aria-label="Sundance SheerView recess" className={classes} value={String(options.sundance_sheerview_recess??"")} onChange={e=>onUpdateFields({options_json:{...options,sundance_sheerview_recess:e.target.value||null}})}><option value="">Select recess</option><option>Flush</option><option>Partial recess</option></select></label><p className="text-sm text-amber-900">Published headrail depth: {sundanceSheerviewHeadrailDepths[String(options.sundance_sheerview_headrail)]??"select headrail"} inches. The factory deducts ⅛–3/16 inch from inside order width; do not apply that deduction again.</p></>}
    {options.sundance_sheerview_control==="Continuous Cord Loop"&&<label className="block text-sm">Cord option<select aria-label="Sundance SheerView cord option" className={classes} value={String(options.sundance_sheerview_cord_option??"")} onChange={e=>onUpdateFields({options_json:{...options,sundance_sheerview_cord_option:e.target.value||null}})}><option value="">Select cord option</option>{sundanceSheerviewCordOptions.map(cord=><option key={cord}>{cord}</option>)}</select></label>}
    <label className="block text-sm">Assembly<select aria-label="Sundance SheerView assembly" className={classes} value={String(options.sundance_sheerview_assembly??"")} onChange={e=>onUpdateFields({options_json:{...options,sundance_sheerview_assembly:e.target.value||null}})}><option value="">Select assembly</option><option>Single</option><option>Two on one</option></select></label>
    {options.roman_style!=="Valance Only"&&<SundanceAccessoryOptions product="sheerview" options={options} widthInches={widthInches} onChange={(key,value)=>onUpdateFields({options_json:{...options,[key]:value||null}})}/>}
    {issues.length>0&&<div role="alert" className="space-y-1 text-sm text-amber-900">{issues.map(issue=><p key={issue.ruleId}>{issue.explanation}</p>)}</div>}
    {selected?.portalStatus==="current_guide_only"&&<p className="text-sm text-amber-900">This exact color is in the current guide but absent from the captured dealer menu. Confirm ordering availability and price with Sundance.</p>}
    {selected?.name==="Blh"&&<p className="text-sm text-amber-900">The guide lists this code as Blh; the dealer calls it Blush. Confirm the finish using its exact code.</p>}
    <p className="text-sm text-amber-900">The base grid is for continuous cord loop. Cordless, motor, headrail and oversize charges require confirmation in the manual price. Flat headrails have lower height limits than the base grid.</p>
  </>;
}
